### ISSUE TITLE
Allow keyboard navigation in JComboBox

### ISSUE THREAD

**Issue by weisJ** [weisJ/darklaf#10]
When a JComboBox is focused one should be able to scroll through the entries of the selection model using the arrow keys on the keyboard.

**Comment by artg3-dev** [comment]
Is there documentation somewhere on what the default keybinds are for the JComboBox? I'd be willing to take a stab at this

**Comment by Bios-Marcel** [comment]
I think this might actually differ depending on the platform and therefore the platform L&Fs

**Comment by weisJ** [comment]
Apparently this behaviour is already present and I wasn't aware of it. Generally keyboard-actions are located in ````loadActionMap()```` and ````installKeyboardActions()```` methods.
