### ISSUE TITLE
combobox: editable combobox looks too aggressive in IntelliJ

### ISSUE THREAD

**Issue by vlsi** [weisJ/darklaf#103]
d43a3aa4be51a6e84c08b613e4a790c579286bcb

plain:
<img width="90" alt="Снимок экрана 2020-03-20 в 14 28 37" src="https://user-images.githubusercontent.com/213894/77159806-1c9f9000-6ab7-11ea-9a04-fe9ee9f73ac1.png">

editable:
<img width="90" alt="Снимок экрана 2020-03-20 в 14 24 07" src="https://user-images.githubusercontent.com/213894/77159551-9edb8480-6ab6-11ea-9b90-8461c648e790.png">

It looks like this blue color is too much for a passive component.

Sample from IDEA 2020.1 (the first field is not editable, and the second one is editable):

<img width="622" alt="Снимок экрана 2020-03-20 в 14 26 05" src="https://user-images.githubusercontent.com/213894/77159631-c6cae800-6ab6-11ea-93dc-76b40efea0f6.png">

**Comment by weisJ** [comment]
I totally forgot about that. I implemented it experimentally to see how it would look but was never quite satisfied with the result.  Removed with 0e7c76f648bbfb2c7c0ff0e3aa1b048c254ff003
