### ISSUE TITLE
button: shadow naming is extremely confusing

### ISSUE THREAD

**Issue by vlsi** [weisJ/darklaf#108]
E.g. KEY_NO_SHADOW_OVERWRITE, noShadowOverwrite, Button.shadow.click.

It is really confusing, especially when it comes to ToolTip.borderShadowColor (which is shadow as well, however, it is a completely different shadow).

It would be great if `shadow` button style could be renamed to something else.

**Comment by weisJ** [comment]
Do you think naming them `hover` would be better or is this still confusing? Essentially that is what they are. Buttons that utilize rollover painting.

**Comment by vlsi** [comment]
Well, regular buttons can have `hover` effects as well :-/

Material design calls it `text` button: https://material.io/components/buttons/#text-button

**Comment by weisJ** [comment]
Which is even more confusing in my opinion. Especially because the style is intended for buttons without text.

**Comment by vlsi** [comment]
What do you think of `borderless`?

**Comment by weisJ** [comment]
Its definitely better. I think I'll use it.

**Comment by vlsi** [comment]
Well, it does not cover `fullShadow`, and I don't think I remember the difference between `shadow` vs `fullShadow` :)

Apparently, `fullBorderless` or `borderlessIndeed` won't work great :)

**Comment by weisJ** [comment]
The difference is that `fullShadow` will fill the whole content area instead of the rounded background with `shadow`.

**Comment by weisJ** [comment]
What do you think of `borderlessNoMargin`, `borderlessRectangular` or `borderlessNonRounded`?

**Comment by vlsi** [comment]
> borderlessNoMargin, borderlessRectangular

^^  this sounds good

> borderlessNonRounded

^^ this is a bit worse as it makes me think of what it could be **else** besides `rounded`

**Comment by weisJ** [comment]
I think I'll use `borderlessRectangular` then. Actually `borderlessNoMargin` might be irritating as even though effectively there is no margin the theme can change it to include one.
