### ISSUE TITLE
Paint performance

### ISSUE THREAD

**Issue by vlsi** [weisJ/darklaf#111]
Test:
1) Launch JMeter
2) Create "thread group" element
3) Try resizing the splitter between the tree and the thread group configuration

The resizing is not fluent.
With Metal, Nimbus, etc the resizing is much more responsive.

It is not very annoying, but it is noticeable.

**Comment by weisJ** [comment]
I’ll have to look into what may cause this issue but I fear this could be a bigger task of optimising the painting of each component.

**Comment by weisJ** [comment]
Closing in favor of #161.
