### ISSUE TITLE
Expose DarkScrollBarUI#getThickness via UIDefaults

### ISSUE THREAD

**Issue by vlsi** [weisJ/darklaf#114]
`thickness` is hardcoded, so there's no way for the application to increase scrollbar size.

This does not play well with in-app scaling (which is updating UIDefaults after setting LaF and before updating Swing components to a new UI).

Note: there are default UI properties like `ScrollBar.width`, `ScrollBar.minimumThumbSize`, `ScrollBar.maximumThumbSize`

Note: there's a semi-standard `JComponent.sizeVariant` with values like `large`, `small`, `mini`. Does it replace darklaf's `JScrollBar.thin`?

intellij:
<img width="966" alt="intellij" src="https://user-images.githubusercontent.com/213894/77248409-37eed480-6c4a-11ea-859a-e11ee63f088d.png">

metal:
<img width="966" alt="metal" src="https://user-images.githubusercontent.com/213894/77248413-3f15e280-6c4a-11ea-8972-7ce55e090a25.png">

**Comment by weisJ** [comment]
I have added the propertes `ScrollBar.width` and `ScrollBar.smallWidth`. Also `DarkScrollBarUI.KEY_THIN` was renamed to `KEY_SMALL` and essentially is `JComponent.small` now.
