### ISSUE TITLE
Please avoid use of PropertyChangeListener for LaF initialization

### ISSUE THREAD

**Issue by vlsi** [weisJ/darklaf#115]
I guess `com.github.weisj.darklaf.DarkLaf#propertyChange` can be replaced with `UIDefault.ActiveValue` and `LazyValue`.

**Comment by vlsi** [comment]
Is this closed in https://github.com/weisJ/darklaf/commit/34811ae8035940e2c0bfecab866368841a5e50d1#diff-435c6307fc43874f035bf6f37778a57d ?

Should https://github.com/weisJ/darklaf/blob/65d0bb4bb9c64648252fe14f94ddb540ad818eb1/core/src/main/java/com/github/weisj/darklaf/DarkLaf.java#L61 be removed as well?

Could you please cut a release, so the [workaround](https://github.com/apache/jmeter/pull/572/files#diff-21c0afdebc6f2c164f9e6257664e0c88R144) can be removed?

**Comment by weisJ** [comment]
Not fully. There is still `DarkBorders#update` which I’ll probably replace with the approach of `ThemedSVGIcon`.
