### ISSUE TITLE
ButtonGroup not focus traversable.

### ISSUE THREAD

**Issue by weisJ** [weisJ/darklaf#116]
Relevant jdk bug: https://bugs.openjdk.java.net/browse/JDK-8130893
It is marked as `not an issue` with the comment that the industry standard for a button-group is that tab should only move into or out of a group. Navigation inside the group should use the arrow keys.
Then another issue is linked where this originally was decided:
https://bugs.openjdk.java.net/browse/JDK-8033699

But it __only__ works for `JRadioButton`.

This is the commit that fixes it for RadioButtons. 
http://hg.openjdk.java.net/jdk7u/jdk7u/jdk/rev/84c3e31f3c4a
The problem is that it only expects a `JRadioButton` to be a valid focus target.

I guess the solution is to port this fix to `JCheckBox` and `JToggleButton`.

_Originally posted by @weisJ in https://github.com/weisJ/darklaf/issues/96#issuecomment-601919639_

**Comment by weisJ** [comment]
Currently using the arrow keys instantly selected the next button in the group (for `JRadioButton` at least). Now there are several option of how to implement this:
1. Like for `JRadioButton` using the arrow keys changes the selection in the button group for all types of `JToggleButton`.
   1.1 Using tab still treats the group as one focus object.
   1.2 Tab cycles through all buttons of the group.
2. The arrow buttons cycle the focus of inside the group.
   1.1 Using tab still treats the group as one focus object.
   1.2 Tab cycles through all buttons of the group.

@vlsi WDYT?

**Comment by vlsi** [comment]
I guess 2.1

macOS has the following:
a) tab treats button group as a single item
b) arrows move the focus within the group
c) items are activated with `space`
d) `enter` does nothing

**Comment by weisJ** [comment]
@Bios-Marcel any opinions on this? I would too favour option 2.1.

**Comment by Bios-Marcel** [comment]
The only real usage i see for a button group is really JRadioButtons and for that usecase it is fine to treat them as one focusable item, as i'd see the groip synonmously with a JComboBox for example.

However, I think the arrow keys should behave the same with all button types, just for the sake of consistency and the fact that this doesn't really lead to any problems.
