### ISSUE TITLE
Hard-dependencies on signing and maven publishing should be optional

### ISSUE THREAD

**Issue by Bios-Marcel** [weisJ/darklaf#12]
I just git-pulled and ran `gradlew tasks` and instantly ran into errors. While quickly stripping the build file of the problematic parts wasn't a problem, this should be solvable in a less dumb way than I did :D 

I don't know too much about gradle though, therefore I can't provide any insight.

**Comment by weisJ** [comment]
The newest commit should have fixed the issue.

**Comment by Bios-Marcel** [comment]
Yup, thanks :)
