### ISSUE TITLE
Formatter rules, linting rules and so on ...

### ISSUE THREAD

**Issue by Bios-Marcel** [weisJ/darklaf#120]
We recently checked out the darklaf code to see whether some things are fixable and noticed that there's no formatter or linter and whatever else one might want/need. We personally use eclipse, therefore eclipse settings would be nice, I am assuming most other people use IntelliJ though. Anyhow, there's settings for neither of those. The downside of this is, that there's potentially a lot of differently formatted code and it'd be nice if we were able to avoid this somehow. Even an external formatter would be fine. Maybe there's a formatting plugin for maven for example?

I also wondered whether the code should start following best practices, such as preventing name shadowing, using `final` wherever possible, always annotating overriden methods with `@Override` and whatever else there might be. All those things should be linting errors in my opinion.

**Comment by weisJ** [comment]
For now I have included the intelliJ settings in `.editorconfig`. I'll have to look into appropriate gradle plugins to enforce the style (after some research I think one might first need to convert the settings to the eclipse format).

 >I also wondered whether the code should start following best practices....
Preferably  this would also be checked by the plugin mentioned above. Though one should keep in mind that if there is a `final` member in a `*UI` class it should probably be replaced with one that can is `non-final` or is created by calling a method to allow extending classes to overwrite it (I know this isn't  currently the case in some classes).
With the other point I do agree.

The first step would probably be to create the appropriate eclipse settings. From there on [spotless](https://github.com/diffplug/spotless/tree/master/plugin-gradle) could work as it supports the eclipse formatter (which also has an IntelliJ plugin).

**Comment by vlsi** [comment]
>From there on spotless could work

I would suggest https://github.com/autostyle/autostyle :)

> . Though one should keep in mind that if there is a final member in a *UI class it should probably be replaced with one that can is non-final or is created by calling a method to allow extending classes to overwrite

That might be a slightly different story, but I'm planning to use **delegation** for TextFieldUI and friends in Apache JMeter.
The case there is as follows: we want a consistent undo/redo implementation, and it looks like adding JMeter-related TextFieldUI to UIDefaults would enable JMeter to catch and patch all the text fields in the application.

**Comment by weisJ** [comment]
> I would suggest https://github.com/autostyle/autostyle :)
👍 

@Bios-Marcel Would it be possible for you to create the eclipse style sheet?

**Comment by weisJ** [comment]
Autostyle is now configured.
