### ISSUE TITLE
table, editing: the text is hard to read

### ISSUE THREAD

**Issue by vlsi** [weisJ/darklaf#121]
8251875d3a11255971103b7fd209314f436369ea
<img width="240" alt="Снимок экрана 2020-03-26 в 1 40 53" src="https://user-images.githubusercontent.com/213894/77592544-6d721700-6f03-11ea-9461-5394e375e683.png">

Darcula is slightly better:
<img width="238" alt="Снимок экрана 2020-03-26 в 1 45 36" src="https://user-images.githubusercontent.com/213894/77592582-84186e00-6f03-11ea-970f-b326acf55712.png">

I would suggest painting just 1px (or whatever) border instead of painting the full background.
And/or adjust foreground color.

**Comment by vlsi** [comment]
Here's how selection works:
<img width="234" alt="Снимок экрана 2020-03-26 в 1 47 15" src="https://user-images.githubusercontent.com/213894/77592679-c2159200-6f03-11ea-801b-7862dcb15e5c.png">

**Comment by weisJ** [comment]
This is not intended. The selection background should not be painted.
