### ISSUE TITLE
SolarizedLight: checkbox and radio background are not aligned with text field background

### ISSUE THREAD

**Issue by vlsi** [weisJ/darklaf#122]
<img width="381" alt="light" src="https://user-images.githubusercontent.com/213894/77684176-a31e0b00-6faa-11ea-811f-860d3cbb967a.png">

<img width="373" alt="dark" src="https://user-images.githubusercontent.com/213894/77684205-b0d39080-6faa-11ea-879b-4fd1e4f839d1.png">

**Comment by weisJ** [comment]
Did you mean `SolarizedLight`? The colours are such that they coincide with the Solarized theme for IntelliJ.

**Comment by vlsi** [comment]
That is strange.

In all Darcula / IntelliJ / SolarizedDark themes the background for checkbox and radio looks the same as the background for text fields.

However, in SolarizedLight the background for checkbox is just white.

**Comment by weisJ** [comment]
That is how it looks like in IntelliJ.
![solarized_light](https://user-images.githubusercontent.com/31143295/77685463-c42b2f80-6f9b-11ea-9efc-06eda6815484.png)

**Comment by vlsi** [comment]
Oh, that looks like a bug in SolarizedLight itself indeed.

**Comment by vlsi** [comment]
By the way: do you have a converter for IntelliJ-based themes?

That is: do you think it is a UI bug?
Do you wait for the upstream to fix it?
Do you just fix it in darkalf?

**Comment by weisJ** [comment]
I’ll just fix it in darklaf. There is currently no converter for IntelliJ themes but it is on my list. Would make it a lot easier to create new themes.
