### ISSUE TITLE
Select dark/light theme based on the OS setting

### ISSUE THREAD

**Issue by vlsi** [weisJ/darklaf#124]
For instance: if OS is configured for dark mode, select darcula otherwise intellij.

As an alternative, it might be a `LafManager` API like `getPreferredThemeStyle()` with output like

```java
class PreferredThemeStyle {
    ColorTone colorTone; // DARK, LIGHT
    Contrast contrast; // REGULAR, HIGH
    FontSize fontSize; // REGULAR, SMALL, BIG
}
```

Then, if the user selects high contrast in the OS setting, the app might use that by default.

WDYT?

**Comment by weisJ** [comment]
I think this is a good idea and would probably go for the second approach as any automatic changes should be optional.

Some thoughts on how to approach this.

First thing would be to provide a set of high contrast themes (dark and light).

I’m not sure how easy it is to retrieve the os settings for different platforms (specifically on Linux I don’t know if there is a consistent notion of light/dark low/high contrast and text size):
- On Windows all values should be available in the registry which can be read using JNA.
- I haven’t looked far into macOS but I presume that there is an api for getting these values.

Another question would be if there is a way to get notified by the os that the settings have changed and in this case give the user the option the add listeners for these events too e.g.  by a custom `ThemePreferenceChangeEvent`.

Additionally there should be the option to set the default themes for dark/light + contrast variations (Maybe themes should indicate that they are a contrast theme to ensure that only supported themes are set for these values).

**Comment by weisJ** [comment]
0bdb8525a0cafaf9848b59c456ba1b5955fe3421 adds a dark high contrast theme. Next up is a light variant (though it appears as there aren't many light high contrast themes so it will take some experimentation)

**Comment by weisJ** [comment]
e4a726f61d02f18eaba6523809c0dc5991d4d9fa adds a light version of the high contrast theme.

**Comment by weisJ** [comment]
I have now added initial support for a `PreferredThemeStyle` (a6998e123c003454e08c380836be9d79bf36e18a 4fc9f03de9f29a52a39ccaa1c71aa5318ef0026f):

You can install or get a theme from the `LafManager` by specifying:
- `ColorToneRule` either `DARK` or `LIGHT`
- `ContrastRule` either `HIGH_CONTRAST` or `STANDARD`
- `FontSizeRule` The value specifies the relative size to the default font. The values and the fact that these are relative can be changed if someone wanted to do so.
   - `DEFAULT` keeps the default font size. i.e. skips the font parsing step all together.
   - `TINY`: -6
   - `SMALLER` -4
   - `SMALL` -2
   - `MEDIUM` +/-0
   - `LARGE` +4
   - `LARGER` +8
   - `HUGE` +12

The names and values may need some adjustment. Now I'll need to figure out how to get the values from the os.
Another question would be whether some parts of the ui should scale according to the specified font size as they may look out of place for very large/small sizes? For example radiobuttons/checkboxes, icons (and maybe border sizes) could be adjusted..

**Comment by weisJ** [comment]
I guess there is no good way of checking the os settings without using any native code (there is the possibility to read the values using the command line but I don't want to do that).

Although JNA-Platform supports reading registry keys I think I wont use it as it for one would be a large dependency just for querying registry keys and for another subscribing to registry changes would still need to happen through native code anyway.

I haven't yet found any good information for macOS to check if `highContrast` is enabled and how to receive events if the theme/fonst-size/contrast changes.

**Comment by weisJ** [comment]
The API for `FontSizeRule` has changed to accommodate custom adjustment. The previous enum constants have moved to `FontSizePreset` and their respective `FontSizeRule` can by obtained by calling `FontSizeRule#fromPreset`.
In addition a `FontSizeRule` can be created using `FontSizeRrule#absoluteAdjustment` and `FontSizeRule#relativeAdjustment`.

3ee6d18f1f3d3e53fb65bb628be6a131d601d53c adds working support querying the user preferences on windows.

**Comment by weisJ** [comment]
b4df18f2dcaf01f4fa462739618e623f16ddf54c adds monitoring for changes in the preferences on windows. The feature is opt-in and needs to be enabled using `LafManager#enabledPreferenceChangeReporting`. Listeners can be added using `LafManager#addThemePreferenceChangeListener` (and removed with `LafManager#removeThemePreferenceChangeListener`).

Change reporting can also be disabled globally using the `darklaf.themePreferenceReporting` flag.
