### ISSUE TITLE
What do you think of adding CheckBox.icon default?

### ISSUE THREAD

**Issue by vlsi** [weisJ/darklaf#125]
I understand Darklaf does not need it, however, it turns out there are multiple third-party libraries that expect `CheckBox.icon` to be present.

For instance:
https://github.com/apache/jmeter/commit/01230139d3606ddc79d7d7c68996ce38a282648d

https://github.com/undera/jmeter-plugins-manager/blob/d801d8b8d8b7e7d31c8d55203f95b1702b93ec69/src/main/java/org/jmeterplugins/repository/CheckBoxList.java#L31

And so on.

Even though I think the use of `CheckBox.icon` should be removed from the app code (or at least it should be guarded with null checks), it would be great if Darklaf could work with old apps.

Originally reported in https://bz.apache.org/bugzilla/show_bug.cgi?id=64286

**Comment by vlsi** [comment]
https://stackoverflow.com/a/25740576/1261287 lists some defaults.

I guess if there should be a unit-test in Darklaf that ensures all the properties return non-null values (I'm not sure which ones are missing now, but it might make sense to add them for compatibility reasons).

**Comment by weisJ** [comment]
I can provide default icon for `CheckBox.icon`. As your usecase is only layout related there is no issue in only providing one single icon that is independent of the state of the checkbox.
For cases in which the icon should actually be painted another approach would be to create an Icon that correctly paints itself based on the component passed to `Icon#paintIcon`.

Regarding your solution something like this could work:
````java
JCheckBox checkBox = new JCheckBox();
checkBox.setBorder(null);
Dimension size = checkBox.getPrefferedSize();
````
as it would basically return the size of the icon itself.

>https://stackoverflow.com/a/25740576/1261287 lists some defaults.

All values that could possibly (and definitely will) return `null` are those set to `null` in the `.properties` file. This mostly affects colours and border but also `CheckBox.icon` and `RadioButton.icon` so after adding them in any missing properties are missing in Metal and Basic Laf as well.

**Comment by vlsi** [comment]
Well, in both cases above the only use for the checkbox was to get icon dimensions.

The case in JMeter was to implement a custom tri-state checkbox. Frankly speaking, I think the solution there is to migrate to Darklaf's tri-state checkbox or remove that control from the UI completely (e.g. replace with combo or whatever).

The case for jmeter-plugins-manager is a bit obscure to me.

> For cases in which the icon should actually be painted another approach would be to create

That is true.
However, my thought here is "bad looking UI" is way better than NullPointerException. That is it.

Here's how JMeter's tri-state looks with Darklaf:
<img width="417" alt="Снимок экрана 2020-03-29 в 22 37 10" src="https://user-images.githubusercontent.com/213894/77858719-df04da80-720d-11ea-8388-9f69015352de.png">

Of course, it does not look great, but it is used just one time in a quite rare component, so I don't really want to spend time investigating how it works :-/

For instance, if we converge that we keep just Darklaf UI in JMeter,  then we could migrate to Darklaf's tri-state component.

>JCheckBox checkBox = new JCheckBox();
>checkBox.setBorder(null);
>Dimension size = checkBox.getPrefferedSize();

Thanks. That is indeed trivial and powerful. However, the paint won't look great anyway. I guess tri-state checkbox should be managed by LaF completely, not like "two states are rendered by LaF, and the third is emulated by nobody knows which code".

**Comment by vlsi** [comment]
PS. https://github.com/weisJ/darklaf/blob/master/core/src/main/resources/com/github/weisj/darklaf/icons/control/checkBoxFocused.svg and https://github.com/weisJ/darklaf/blob/master/core/src/main/resources/com/github/weisj/darklaf/icons/control/checkBox.svg suggest that you manage checkbox border with just displaying different icons, so `getPrefferedSize` would return bigger dimension than the one that is consumed by the checkbox rectangle.

That probably explains why JMeter's third state is so much bigger than the other checkboxes JMeter does not know Darklaf's checkbox icons contain borders and even padding.

**Comment by weisJ** [comment]
I have added the values for `CheckBox.icon` and `RadioButton.icon` which will also paint accordingly.
