### ISSUE TITLE
Font rendering on macOS Catalina

### ISSUE THREAD

**Issue by weisJ** [weisJ/darklaf#128]
Using `.AppleSystemUIFont` as the font on Catalina apparently results in undesired kerning behaviour.
See [here](https://youtrack.jetbrains.com/issue/JBR-1915) and [here](https://github.com/kirill-grouchnikov/radiance/issues/224).

**Comment by slimzghal** [comment]
Here is a screenshot of JMeter 5.3 (Darklaf 2.1.1) on MacOS Catalina (Retina Display) with Oracle JDK8. There are issues with font kerning when using the default System font. (as in the word "Test").

<img width="1162" alt="jmeter_jdk8" src="https://user-images.githubusercontent.com/13177667/82350205-5596ab00-99fb-11ea-928e-61f84cf9ab27.png">

**Comment by weisJ** [comment]
How about java 9?

**Comment by weisJ** [comment]
Could you give me images of the following scenarios using darklaf?

1. `.AppleSystemUIFont` + fractional metrics:
   ````java
   UIManager.put(RenderingHints.KEY_FRACTIONALMETRICS, RenderingHints.VALUE_FRACTIONALMETRICS_ON);
   Font font = new Font(".AppleSystemUIFont", Font.PLAIN, 12);
   Map<AttributedCharacterIterator.Attribute, Integer> kerning= 
   Collections.singletonMap(TextAttribute.KERNING, TextAttribute.KERNING_ON);
   JLabel label = new JLabel("Test Plan");
   ````

2. `.SF NS Text`:
   ````java
   JLabel label = new JLabel("Test Plan");
   Font font = new Font(".SF NS Text", Font.PLAIN, 12); 
   Map<AttributedCharacterIterator.Attribute, Integer> kerning = Collections.singletonMap(TextAttribute.KERNING, TextAttribute.KERNING_ON);
   label.setFont(font.derive(kerning));
   ````

3. `.SF NS Text` + fractional metrics:
   ````java
   UIManager.put(RenderingHints.KEY_FRACTIONALMETRICS, RenderingHints.VALUE_FRACTIONALMETRICS_ON);
   JLabel label = new JLabel("Test Plan");
   Font font = new Font(".SF NS Text", Font.PLAIN, 12);
   Map<AttributedCharacterIterator.Attribute, Integer> kerning = Collections.singletonMap(TextAttribute.KERNING, TextAttribute.KERNING_ON);
   label.setFont(font.derive(kerning));
   ````
4. `Helvetica Neue`:
   ````java
   JLabel label = new JLabel("Test Plan");
   Font font = new Font("Helvetica Neue", Font.PLAIN, 12);
   Map<AttributedCharacterIterator.Attribute, Integer> kerning = Collections.singletonMap(TextAttribute.KERNING, TextAttribute.KERNING_ON);
   label.setFont(font.derive(kerning));
   ````

**Comment by weisJ** [comment]
After doing some tests I have decided to switch to `Helvetica Neue` for macOS Catalina. All other combinations of the system font produced bad kerning behavior.
