### ISSUE TITLE
Maximized window with decoration has gap 

### ISSUE THREAD

**Issue by steffen-wilke** [weisJ/darklaf#132]
Hi,

great project. This is the first (dark) LAF that I'm actually considering to use for the editor of our game engine ([LITIENGINE](https://github.com/gurkenlabs/litiengine)).

I've played around with it yesterday and I found the following issue with the LAF when `       LafManager.setDecorationsEnabled(true)` is set (which I believe is the default):

It seems like the window somehow produces a gap around the window when it is in maximized state:

**Maximized wid decoration disabled:**
![nodecoration](https://user-images.githubusercontent.com/7015370/78894556-8b945700-7a6d-11ea-91db-28a4cf3b004b.png)

**Maximized with decoration enabled:**
![decorationn](https://user-images.githubusercontent.com/7015370/78894606-a5359e80-7a6d-11ea-828e-bbddcae8dedf.png)

To reproduce this, I just used the basic example code from your `README` and applied the `DarculaTheme`. But even without the dark theme, the issue still occurs.
I really like the look with decorations and I wonder if there is anything I can do to prevent this issue or if it's actually a bug.

OS Information:
- Microsoft Windows 10 Pro
- 10.0.18362 Build 18362

Java Version: jdk1.8.0_201

**Comment by weisJ** [comment]
I’m glad you like the project :). 

The issue with the gap has already been resolved and will be available with the next version.

**Comment by steffen-wilke** [comment]
That's great :) Looking forward to the next release! Any ETA on the release?

**Comment by weisJ** [comment]
The last thing to do is #127.

**Comment by weisJ** [comment]
The new version is now out

**Comment by steffen-wilke** [comment]
Perfect! The issue is resolved.
