### ISSUE TITLE
macos, 2.0.2: titlebar is missing when native code is enabled

### ISSUE THREAD

**Issue by vlsi** [weisJ/darklaf#136]
d99f655ef82b421ddea515344ea44ca86aa75eb5:
<img width="472" alt="default" src="https://user-images.githubusercontent.com/213894/79687235-7d54f080-824e-11ea-92f3-78da2fcb1235.png">

`-Ddarklaf.decorations=false`:

<img width="538" alt="darklaf.decorations=false" src="https://user-images.githubusercontent.com/213894/79687258-b2614300-824e-11ea-980f-ec81325b4f0e.png">

**Comment by weisJ** [comment]
Should be fixed in 9482bc3dd8e020bb9c88227da2c22040d790352a

**Comment by weisJ** [comment]
ddd6af025fb58205cfeb1a1086bf18d1bfd70bf9 should fix the incorrect titlebar height.

**Comment by vlsi** [comment]
Thanks, it looks OK now.
