### ISSUE TITLE
macos, 2.0.2: selected text foreground should be aligned with selection foreground

### ISSUE THREAD

**Issue by vlsi** [weisJ/darklaf#137]
d99f655ef82b421ddea515344ea44ca86aa75eb5:

Here's selected text is hard to read since it is white on yellow:
<img width="426" alt="selection foreground" src="https://user-images.githubusercontent.com/213894/79687321-33b8d580-824f-11ea-9b0f-f9592b616216.png">

**Comment by weisJ** [comment]
This has been improved in 8371826ab5b4355fde48841aa93a0939f53cc88d. My current approach is to use the `[brightness of selection foreground]= 1 - [brightness of selection background]`. Of course this might still result in hard to read selections but this should only occur for colors that are gray and have `~0.5` brightness.

**Comment by vlsi** [comment]
It looks like the foreground is always black:
<img width="537" alt="yellow" src="https://user-images.githubusercontent.com/213894/79692917-8d7dc780-8270-11ea-882a-ef180c9c045d.png">

It is in line with what macOS does:
<img width="637" alt="Снимок экрана 2020-04-19 в 19 06 49" src="https://user-images.githubusercontent.com/213894/79693014-fcf3b700-8270-11ea-8d7d-f1bdf3b65112.png">

**Comment by weisJ** [comment]
> It looks like the foreground is always black:

That is because the selection color has brightness `1.0`
