### ISSUE TITLE
Title bar disappears

### ISSUE THREAD

**Issue by GraxCode** [weisJ/darklaf#138]
A `WindowListener` overriding `windowClosing` that displays a `JOptionPane` crash the look and feel, after confirmation the top bar disappears. (`mainFrame.addWindowListener(...)`)

**Comment by weisJ** [comment]
Please provide a minimal example and the stacktrace

**Comment by GraxCode** [comment]
https://streamable.com/0w05hr There is no stacktrace

**Comment by weisJ** [comment]
> https://streamable.com/0w05hr There is no stacktrace

Please avoid the terminology of "crashing" when there is no literal crash.

Also this should be fixed in 5fecc2cc563de287aaab8959a99481c0838ffc84
