### ISSUE TITLE
Release tag consistency

### ISSUE THREAD

**Issue by Bios-Marcel** [weisJ/darklaf#14]
I've seen the folder `bin/` and think that binaries shouldn't be part of the source repo. You've already released 1.3.1.2 on Maven Central, however, there's currently no tag for that version in the git repository. It'd be good to keep these two consistent, the maven versions and the git tags. This will avoid confusion to whether a version is really what it seems to be.

**Comment by weisJ** [comment]
I have created the corresponding release.
