### ISSUE TITLE
macos: tooltip is opaque

### ISSUE THREAD

**Issue by vlsi** [weisJ/darklaf#140]
ToolTipDemo:

<img width="269" alt="Снимок экрана 2020-04-20 в 11 05 09" src="https://user-images.githubusercontent.com/213894/79728894-4edf2000-82f7-11ea-94fd-a79ed467b420.png">

**Comment by weisJ** [comment]
Fixed in b7a0da34108e5d36b89af1ee0a44b5ab54db2eab

**Comment by weisJ** [comment]
Is this fixed? If yes I'd cut a release.

**Comment by vlsi** [comment]
Thanks. Looks good in 7fd865105af4fa6cd6d5bc3a016b909e9404dbff

However, I guess you might want to remove the following:

```
core/src/main/java/com/github/weisj/darklaf/settings/ThemeSettingsPanel.java:        System.out.println(theme);
core/src/main/java/com/github/weisj/darklaf/settings/ThemeSettingsPanel.java:        System.out.println(themeComboBox.getSelectedItem());
```
