### ISSUE TITLE
Dark mode detection on Catalina is unreliable.

### ISSUE THREAD

**Issue by weisJ** [weisJ/darklaf#141]
See [this issue](https://github.com/weisJ/auto-dark-mode/issues/3) for more infrmation.

The fix is (probably. not tested yet) to build the macos library against the `10.14 SDK`. Currently it is build against `10.10` for maximum compatibility. But upgrading would also remove the decorations feature for the  older versions.

My proposition would be to have a separate library build for dark mode detection with the `10.14 SDK` which then can be loaded if Mojave is available.

Any opinions on this?

**Comment by kirill-grouchnikov** [comment]
It's your project, and you're the decider. I'll just offer this.

Ignoring the situation where at the present moment you do not have direct access to macOS hardware for developing and testing, I think that over the long run you'll find that trying to incorporate native integration at this level to be painful and brittle.

It might be OS APIs that are still being developed and refined by the OS vendors. It might be that these APIs will evolve over time in ways that will make it very cumbersome to support anything but the latest version of the OS in question. It might be that there are no public APIs to access things you want to access (I think that's where you are right now with title text color) and you will be broken at any time.

It's not that it's impossible or infeasible - as your efforts are clearly showing that it can be done. It's just that it doesn't scale well over the horizon of 5+ years where every year you have major OS releases.

**Comment by weisJ** [comment]
I see your point. I'll definitely won't broaden the scope of the native support any further. I'll have to see what the next macOS version brings and depending on it I'll drop support for versions older than Mojave. The bright side here is that there are generally `~75%`  of users running one of the two newest versions.
