### ISSUE TITLE
Cannot build 2.0.2 with gradle

### ISSUE THREAD

**Issue by steffen-wilke** [weisJ/darklaf#144]
Currently testing the new release and I changed the `build.gradle` file 

```groovy
repositories {
   jcenter()
}

dependencies {
  implementation 'com.github.weisj:darklaf-core:[1.4.3.1,)'
}
``` 

to
```groovy
repositories {
  mavenCentral() // not available on jcenter  yet
}

dependencies {
  implementation 'com.github.weisj:darklaf-core:[2.0.2,)'
}
```

In my simple test project and also when attempting to integrate this into the LITIENGINE editor (see [this commit](https://github.com/gurkenlabs/litiengine/commit/9b586928a97143892550a50244a0443da12eb9f3)) I always get an error when building with gradle on the `:compileJava` stage 

```
> Task :compileJava FAILED
{SOME_PATH}\Darktest\src\main\java\Darktest\Test.java:13: error: package com.github.weisj.darklaf.theme does not exist
import com.github.weisj.darklaf.theme.DarculaTheme;
                                     ^
{SOME_PATH}\Darktest\src\main\java\Darktest\Test.java:24: error: cannot find symbol
       LafManager.install(new DarculaTheme());
                              ^
  symbol:   class DarculaTheme
  location: class Test
2 errors
```
(also see this [Travis CI build](https://travis-ci.com/github/gurkenlabs/litiengine/builds/161321156)). Oddly enough: Eclipse builds the project just fine. It doesn't show any errors and I can launch the application successfully.

**Comment by weisJ** [comment]
You'll have to also include `darklaf-theme` with
````
implementation("com.github.weisj:darklaf-theme:[2.0.2,)")
````
