### ISSUE TITLE
Switching themes: Is it possible to affect "orphan" controls

### ISSUE THREAD

**Issue by steffen-wilke** [weisJ/darklaf#146]
I've integrated theming support to the editor of our game engine (with [PR 340](https://github.com/gurkenlabs/litiengine/pull/340)). 

First, I'd like to say: Thank you! **Great work on the latest 2.0.x release.**

The editor should support switching themes at runtime and in general, this works great, except for some controls that are (what I think might be the reason) not a direct child of any component.

This is a problem, e.g. for a `JPopupMenu` or other components that might be displayed or even added dynamically at runtime. Our editor dynamically adds some panels when certain objects are selected.

**Example JPopupMenu after switching from `OneDark` to `IntelliJ`:**
![image](https://user-images.githubusercontent.com/7015370/80044770-d4d0b600-8505-11ea-871f-079c13ed350f.png)

Is there any callback or mechanism in place to ensure that these controls are also affected when switching a theme?

**Comment by weisJ** [comment]
You’ll have to call `JComponent#updateUI` on them every time the theme or laf is updated. If you have nested components the safer way is to call `SwingUtilities#updateComponentTreeUI` which recourses through all children of the components and updates the ui.

**Comment by weisJ** [comment]
One way to do this is to attach a `PropertyChangeListener` to the `UIManager` this way you don’t have to manage all components yourself. In the next release there will also be listeners for theme install events you can add to the `LafManager` which comes with a predefined listener that updates the UI for you.

**Comment by steffen-wilke** [comment]
This works perfectly. Thank you for your support!
