### ISSUE TITLE
Frame / dialog shadow not visible

### ISSUE THREAD

**Issue by GraxCode** [weisJ/darklaf#147]
I am unsure what causes this. Should the main frame have a shadow too? I know that dialogs are supposed to have a shadow around them, but it seems like they are not appearing for me.
![Screenshot_2](https://user-images.githubusercontent.com/24767548/80110133-a3e09780-857e-11ea-90c6-a77e52d002cc.png)
I'm initializing using 
`		LafManager.enableLogging(true);
		LafManager.install(new OneDarkTheme());`
did i forget something? I am on Windows 10, Java 8.

**Comment by weisJ** [comment]
All windows that have a title bar should have shadows.
- Are you able to use "aero-snap" with the frame?
- Which version of darklaf are you using?
- Which version of Windows10 are you using?

**Comment by weisJ** [comment]
Please try to run with a version newer than Java 8.  `threadtear-all-2.0.jar` works fine for me on Java 11

**Comment by GraxCode** [comment]
Also doesn't work with Java 10 for me. I have AeroGlass installed, could it be related with this issue?

**Comment by weisJ** [comment]
> I have AeroGlass installed

Most definitely yes. Try disabling it.

**Comment by GraxCode** [comment]
The dialog shadow worked with AeroGlass in version 1.3.3.4.

**Comment by weisJ** [comment]
You might wan't to try with the repository version.
````
./gradlew runDemo --class ui.button.ButtonDemo
````
but I won't officially support any third party program that modifies titlebars etc.

**Comment by GraxCode** [comment]
Can't get it to build, 'main' component in project ':darklaf-macos' does not target this operating system, whatever. Did you change something in terms of shadows?

**Comment by weisJ** [comment]
I changed one thing that could have an effect.

> 'main' component in project ':darklaf-macos' does not target this operating

This is only a warning. It should still build fine.

**Comment by weisJ** [comment]
I'm closing this off as it involves a third party program.
