### ISSUE TITLE
Custom UI properties not refreshing

### ISSUE THREAD

**Issue by GraxCode** [weisJ/darklaf#152]
I want to darken the default color of JTrees. This works fine, but when switching theme using `ThemeSettings.showSettingsDialog` the JTree background color is not updated on the main frame, however is updated in JDialogs (opened after changing theme).
```java
	public static void setLookAndFeel() {
		LafManager.enableLogging(true);
		LafManager.registerInitTask(LookAndFeel::applyCustomChanges);
		LafManager.install(new OneDarkTheme());
	}

	public static void applyCustomChanges(Theme t, UIDefaults d) {
		if (Theme.isDark(t)) {
			d.put("Tree.background", d.getColor("Tree.background").darker());
		}
	}
```
Am I doing something wrong?

**Comment by weisJ** [comment]
This works perfectly fine for me. Can you provide a runnable example where it doen't work for you?

Also you might want to consider doing something like this:
````java
LafManager.registerDefaultsAdjustmentTask((theme, props) -> {
    if (Theme.isDark(theme)) {
        Object p = props.get("backgroundContainer");
        if (p instanceof Color) {
            props.put("backgroundContainer",((Color) p).darker());
        }
    }
});
````
It will also have an effect on lists, tables, trees, etc. that use the same background.

**Comment by GraxCode** [comment]
```java
	public static void setLookAndFeel() {
		LafManager.enableLogging(true);
		LafManager.registerDefaultsAdjustmentTask((t, d) -> {
			if (Theme.isDark(t)) {
				Object p = d.get("backgroundContainer");
				if (p instanceof Color) {
					d.put("backgroundContainer", ((Color) p).darker());
				}
			}
		});
		LafManager.install(new OneDarkTheme());
	}

	public static class Test extends JFrame {
		public Test() {
			setBounds(100, 100, 400, 400);
			setLayout(new BorderLayout());
			JTree jt = new JTree();
			this.add(jt, BorderLayout.CENTER);
			ThemeSettings.showSettingsDialog(this);
		}
	}

	public static void main(String[] args) {
		LookAndFeel.setLookAndFeel();
		new Test().setVisible(true);
	}
```
Tree background not changing on Win 10 Build 16299, JDK8_91

**Comment by weisJ** [comment]
The issue is that even `ColorUIResource#darker` and `ColorUIResource#brighter` don't return a `ColorUIResource`. The Laf doesn't overwrite values that aren't marked with `UIResource`. I'll mitigate the problem with the next release by using a custom `ColorUIResource` class that indeed behaves as expected.

For now try to use
````
d.put("backgroundContainer", new ColorUIResource(((Color) p).darker()));
````
