### ISSUE TITLE
Rendering issues of long node label

### ISSUE THREAD

**Issue by pmouawad** [weisJ/darklaf#155]
**Describe the bug**
I have a JTree node with a long label.
As you can see in screenshot, there is a rendering issue where the text is displayed outside of rendering zone of JTree, see the red highlighted zone.

**To Reproduce**
Using JMeter last CI build 

**Screenshots**

<img width="727" alt="Screen Shot 2020-04-30 at 22 41 31" src="https://user-images.githubusercontent.com/3127467/80757176-06640580-8b34-11ea-9fb9-72a740b11051.png">

**Additional Information:**
 - OS: macOS
 - OS Version: 10.11.6
- Darklaf Version: 2.1.0

**Comment by pmouawad** [comment]
See also garbled text in the View Results Tree:

<img width="294" alt="Screen Shot 2020-04-30 at 22 46 44" src="https://user-images.githubusercontent.com/3127467/80757477-82f6e400-8b34-11ea-9072-65d80aa48366.png">

**Comment by weisJ** [comment]
Doesn't happen for me. Could you provide a minimal example to reproduce it?

**Comment by pmouawad** [comment]
Did you try this build:
https://builds.apache.org/job/JMeter-trunk/7733/

**Comment by weisJ** [comment]
I'm building from the current master branch.

**Comment by pmouawad** [comment]
I have just double checked and I reproduce again.
See attached screenshot and test plan.

Go To View Results Tree
Run Plan
Select last Debug Sampler....
Go back to View Results Tree => Get the bug
<img width="1142" alt="Screen Shot 2020-05-01 at 00 08 24" [](src="https://user-images.githubusercontent.com/3127467/80764010-0ec23d80-8b40-11ea-9b28-8278ced7a293.png">)


Test Plan, rename it to jmx only
[reproducer-darklaf-155.jmx.txt](https://github.com/weisJ/darklaf/files/4561648/reproducer-darklaf-155.jmx.txt)

**Comment by pmouawad** [comment]
Another way to reproduce:

Open test plan
Maximize JMeter and you'll also get this

**Comment by pmouawad** [comment]
I think bug is confirmed by another report, see #158

**Comment by pmouawad** [comment]
Thanks for fix, tried it in JMeter nightly, it works
