### ISSUE TITLE
Cursor in Text Field is in wrong position after deleting a char

### ISSUE THREAD

**Issue by pmouawad** [weisJ/darklaf#156]
**Describe the bug**
Using JMeter , add a Debug Sampler with some long text In name textfield.
Go to middle and delete a char, starting from there the cursor is incorrect (I guess by 1 char). So when you delete new character you delete the wrong ones.

**Screenshots**

**Additional Information:**
 - OS: macOS
 - OS Version: 10.11.6
- Darklaf Version: 2.1.0

**Comment by weisJ** [comment]
Doesn't happen for me. Could you provide a minimal example to reproduce it?

**Comment by pmouawad** [comment]
Did you try this build:
https://builds.apache.org/job/JMeter-trunk/7733/

**Comment by weisJ** [comment]
Same as with #155 I am building from the most recent source and can't reproduce it. Could you check if it is happening with other Lafs too?

**Comment by pmouawad** [comment]
Create a Debug Sampler with this text:

`WriteReleaseNotes-${__StringToFile(/data/jmeter/release-notes.md,* ${ticketNumber} ${ticketTitle}\n,true,UTF-8)}`


Go to middle of **ticketNumber** and start deleting characters and moving left / right and you should see the problem.

**Comment by weisJ** [comment]
![delete_text](https://user-images.githubusercontent.com/31143295/80820480-39aba080-8bd7-11ea-972d-ab19d97ddba5.gif)

No problem for me.

**Comment by pmouawad** [comment]
@weisJ , what utility do you use to show this ? I'll do the same

**Comment by weisJ** [comment]
I am using [screenToGif](https://www.screentogif.com/) but it's only for windows. Maybe [this](https://apps.apple.com/de/app/giphy-capture-the-gif-maker/id668208984?mt=12) works well for macOS.

**Comment by pmouawad** [comment]
See this screenshot, look at red rectangle at end, it seems there is a space, but there is none, the pipe is the cursor:

<img width="810" alt="Screen Shot 2020-05-01 at 18 21 42" src="https://user-images.githubusercontent.com/3127467/80821303-bab76780-8bd8-11ea-8268-6d795c30cbcc.png">

**Comment by pmouawad** [comment]
See this screenshot, the cursor is in the middle of the N

<img width="821" alt="Screen Shot 2020-05-01 at 18 24 08" src="https://user-images.githubusercontent.com/3127467/80821461-0d911f00-8bd9-11ea-85c9-54bca36ae60d.png">

**Comment by pmouawad** [comment]
@vlsi , do you also see this behaviour with your version of MacOSX ?

**Comment by weisJ** [comment]
It might be an kerning issue.
Could you try the following?
````java
Map<? extends Attribute, ?> disableKerning = Collections.singletonMap(TextAttribute.KERNING,null);
textField.setFont(textField.getFont().deriveFont(disableKerning));
````

**Comment by pmouawad** [comment]
Issue is related to Java version.
Using 8u161 no issue, using 8u201 issue appears whether I use Kerning or not.

**Comment by kirill-grouchnikov** [comment]
I had a similar report over at https://github.com/kirill-grouchnikov/radiance/issues/179 and ended up doing this - https://github.com/kirill-grouchnikov/radiance/blob/master/substance/src/main/java/org/pushingpixels/substance/api/SubstanceLookAndFeel.java#L190

**Comment by weisJ** [comment]
Thank you @kirill-grouchnikov .
@pmouawad Could you check if the following resolved the problem for you?
````java
LafManager.registerInitTask((theme, defaults) -> {
                Toolkit toolkit = Toolkit.getDefaultToolkit();
                Map<?, ?> desktopHints = (Map<?, ?>) toolkit.getDesktopProperty("awt.font.desktophints");

                Object aaHint = (desktopHints == null) ? null : desktopHints.get(RenderingHints.KEY_TEXT_ANTIALIASING);
                if (aaHint != null
                    && aaHint != RenderingHints.VALUE_TEXT_ANTIALIAS_OFF
                    && aaHint != RenderingHints.VALUE_TEXT_ANTIALIAS_DEFAULT) {
                    defaults.put(RenderingHints.KEY_TEXT_ANTIALIASING, aaHint);
                    defaults.put(RenderingHints.KEY_TEXT_LCD_CONTRAST,
                                 desktopHints.get(RenderingHints.KEY_TEXT_LCD_CONTRAST));
                }
            });
````

**Comment by pmouawad** [comment]
Hello,
No change.
See what I also get selecting all text , moving cursor to left then right, notice the rendering of last character is completely broken

<img width="827" alt="Screen Shot 2020-05-01 at 21 10 36" src="https://user-images.githubusercontent.com/3127467/80834099-5a342480-8bf0-11ea-807c-aa8f7a720ea9.png">

**Comment by weisJ** [comment]
Please try combining it with disabled kerning.

**Comment by pmouawad** [comment]
Thanks but problem persists.

**Comment by weisJ** [comment]
Is the issue still present when using the default caret? i.e.
````java
textField.setCaret(new DefaultCaret());
````

**Comment by pmouawad** [comment]
It works when using your advice

**Comment by weisJ** [comment]
> It works when using your advice.
> Will you be impacting Darklaf or must we handle it on our side ?
> Thanks

I'll have to see if there is something I can do about it. If not I'll handle chaning the caret if necessary.
Just to narrow down the cause could you check what happens with the following?
````java
setCaret(new DarkCaret(){
    @Override
    protected Highlighter.HighlightPainter getSelectionPainter() {
        return DefaultHighlighter.DefaultPainter;
    }
});
````

**Comment by pmouawad** [comment]
Hello @weisJ ,
Well, it's strange, after moving to 2.1.1 I don't reproduce the issue with cursor anymore without any change.
To double check, I reverted to 2.1.0 and issue reappeared.
Upgrading to 2.1.1 again, issue is fixed.

Do you know why ?
Thanks

**Comment by weisJ** [comment]
I guess it would be modifying [`GraphicsUtil#setupAntialiasing`](https://github.com/weisJ/darklaf/blob/d58f56e38af1c1408b012db3915ac48a47289bce/core/src/main/java/com/github/weisj/darklaf/graphics/GraphicsUtil.java#L46). Previously it used to overwrite some system settings.

**Comment by pmouawad** [comment]
Shouldn't you update release notes to mention this fixed issue ?
Thanks
