### ISSUE TITLE
Loading spinner feature request

### ISSUE THREAD

**Issue by GraxCode** [weisJ/darklaf#159]
Currently it is really hard to render animated gifs in swing with antialiasing. (Is it possible to use animated SVG images with `Iconloader.loadSVGIcon`?) Either way, would it be possible to implement something like smooth gif resizing? (as `getScaledInstance` with `Image.SCALE_SMOOTH` does not work on gifs) Or even implement something like a `JLoadingSpinner` component. I am looking for something like a android-like circular spinner.

**Comment by weisJ** [comment]
> Is it possible to use animated SVG images with `Iconloader.loadSVGIcon`?

No it’s currently not possible to do and not although svgSalamander does support animated svg images swing has some problems with it (i.e. icons have no state themselves that tells swing to repaint them when necessary).

 > Either way, would it be possible to implement something like smooth gif resizing? (as `getScaledInstance` with `Image.SCALE_SMOOTH` does not work on gifs) Or even implement something like a `JLoadingSpinner` component. 

Are those two separate request? You can already get a resized instance of an icon using `DarkSVGIcon#derive` but the proffered way to do is simply using `IconLoader#getIcon` anyway. It will pick up on the `svg` extension and will load it as such. You can then use `IconLoader#getIcon` with multiple size parameters (those icons are memory efficient, as they share the same underlying svg instance and only differ in the size they are painted in.)

> Or even implement something like a `JLoadingSpinner` component.

How do you image this component to work? Does it sit in a fixed position, is it a popup?
For me this sounds like a kind of JProgressBar. Maybe look into [ProgressMonitor](https://docs.oracle.com/javase/7/docs/api/javax/swing/ProgressMonitor.html) if the appearance of this component depends on the length of the action taking place.

I’ll need more information on how this component should behave and how it should look like.

**Comment by GraxCode** [comment]
`JLoadingSpinner` should be like a `JLabel` with an `ImageIcon`. The loading animation should look like this: 
![spin](https://user-images.githubusercontent.com/24767548/80819133-b1c49700-8bd4-11ea-8b4c-acc8f736cb34.gif)
Before loading something, I add the component to my panel and repaint, and remove it after that. Why don't I just use a `JLabel` then? The problem is that gif animations are rendered pixelated (as gifs only support 1-bit transparency) and without antialiasing. Loading a high quality gif and scaling it down does also not work in swing. I think this component can easily be made using standard swing methods like `Graphics2D.drawOval` and an internal repainting thread or something similar. This way there won't be problems with downscaling or pixelation.

**Comment by weisJ** [comment]
![load_indicator](https://user-images.githubusercontent.com/31143295/80830093-a8452a00-8be8-11ea-8419-a9a81a16a856.gif)

Darklaf already has a mechanism that allows icons to be painted rotated. (See `RotatableIcon`) so it's quite straight forward to implement something like this. It's a static icon and a swing `Timer` that changes the rotation and repaints the parent of the icon.

**Comment by GraxCode** [comment]
Are you saying this feature is already implemented? Can't seem to find it, if so. If not, I can't override `getAngle` or set it.

**Comment by weisJ** [comment]
> Are you saying this feature is already implemented? Can't seem to find it, if so. If not, I can't override `getAngle` or set it. 

`RotatableIcon#getAngle` already exists in the current version. But the component in the gif will be available out of the box with the next version.

>(Unrelated: Also, when is 2.1.1 released? Need a working `JFileChooser` but do not want to revert changed i already made)
Probably tomorrow.

**Comment by GraxCode** [comment]
Okay, cool!
