### ISSUE TITLE
Feature request: Color chooser field

### ISSUE THREAD

**Issue by GraxCode** [weisJ/darklaf#165]
I am missing something like a color chooser field like in weblaf. Looks like this: 
![Screenshot_22](https://user-images.githubusercontent.com/24767548/81497343-1c08c600-92be-11ea-81a3-637ed5e44d11.png) 
It behaves like a (non-editable) text field.
The color chooser pops up if you click the button on the right side, left side button is for on-screen color selection.

**Comment by weisJ** [comment]
You are looking for [`QuickColorChooser`](https://github.com/weisJ/darklaf/blob/389312a94a06d44506b1f9e6a91bd32d62ead9cd/core/src/main/java/com/github/weisj/darklaf/components/color/QuickColorChooser.java#L39)

**Comment by GraxCode** [comment]
Very cool, but it seems like its position is not updated in a grid layout.
```java
    JPanel left = new JPanel();
    left.setLayout(new GridLayout(4, 1, 16, 16));
    JPanel right = new JPanel();
    right.setLayout(new GridLayout(4, 1, 16, 16));

    left.add(new JLabel("Color: "));
    right.add(new QuickColorChooser("line color", color, c -> color = c));
```
![Screenshot_23](https://user-images.githubusercontent.com/24767548/81498390-fa5f0d00-92c4-11ea-8352-be527987e328.png)
![Screenshot_24](https://user-images.githubusercontent.com/24767548/81498391-faf7a380-92c4-11ea-97c1-8f625c797a7e.png)

**Comment by weisJ** [comment]
Will be fixed in the next release. Until then you could wrap it in a `JPanel` with a `BoxLayout` for example. Or make your own component by looking at the implementation of `QuickColorChooser` all the popup logic is contained in the `QuickColorChooser#attachToComponent` method.
