### ISSUE TITLE
<hr> is white in tooltip texts on dark theme

### ISSUE THREAD

**Issue by GraxCode** [weisJ/darklaf#166]
` setToolTipText("<font color=\"#ff6b6b\">text<br><hr>text");`
![Screenshot_28](https://user-images.githubusercontent.com/24767548/81507014-850e2f00-92fa-11ea-92b4-101c1c46fcae.png)

**Comment by weisJ** [comment]
I couldn't quite get `<hr>` styling to work using the style sheet. Will have to look into it further. I'll probably convert the current approach over to generating the style sheet from the theme defaults instead of having the theme provide it.

**Comment by weisJ** [comment]
Swing only  supports HTML 2.1 and attributes for hr in html 2.1 are `noshade` and `size` (so no `style` tag).
You can do something like this:
````java
"<div style=\"height: 0px; border-top-style: solid; border-width: 1px\"></div>"
````
For now it will be using the text foreground but with the next version it will use a proper border color of the theme.
