### ISSUE TITLE
Better way to combine SVG icons

### ISSUE THREAD

**Issue by GraxCode** [weisJ/darklaf#167]
Is there a better way to combine SVG icons other than using `new ImageIcon(((DarkSVGIcon) this.icon).getSVGIcon().getImage())`? I want to get something like this: ![Screenshot_29](https://user-images.githubusercontent.com/24767548/81507681-49c22f00-92ff-11ea-8e5e-d1ed21f34b3a.png)

**Comment by weisJ** [comment]
You can create a custom icon implementation.

````java
public class OverlayIcon implements Icon {

    private final Icon icon;
    private final Icon overlay;

    public OverlayIcon(final Icon icon, final Icon overlay) {
        this.icon = icon;
        this.overlay = overlay;
    }

    @Override
    public void paintIcon(final Component c, final Graphics g, final int x, final int y) {
        icon.paintIcon(c, g, x, y);
        overlay.paintIcon(c, g, x, y);
    }

    @Override
    public int getIconWidth() {
        return icon.getIconWidth();
    }

    @Override
    public int getIconHeight() {
        return icon.getIconHeight();
    }
}
````

Just make sure that the dimension of the icons fit together. Otherwise adjust the position the overlay is painted at.

**Comment by GraxCode** [comment]
Thanks!
