### ISSUE TITLE
Performance issues with bidirectional text.

### ISSUE THREAD

**Issue by slimzghal** [weisJ/darklaf#169]
**Describe the bug**
Using JMeter 5.3 with Darklaf 2.1.1 on MacOS Catalina 10.15.4 and Oracle JDK 9 (or higher), writing mixed text (LTR and RTL-Scripts, i.e. english in combination with arabic/hebrew) in a component using MigLayout 5.2, the GUI becomes unresponsive. Couldn't reproduce the behaviour on Windows 7, though. Using System-LAF is less sluggish, so I think it's a MigLayout issue which get worse using JDK>8 and Darklaf.

**To Reproduce**
Open JMeter 5.3 with Darklaf on MacOS Catalina, Oracle JDK 9 and type some mixed text (english + a RTL-Script i.e. hebrew/arabic) in the Comment field as in Screenshot. JMeter freezes.

**Screenshots**
<img width="1341" alt="jmeter" src="https://user-images.githubusercontent.com/13177667/82349605-9f32c600-99fa-11ea-90c2-0119211230f2.png">
<img width="1405" alt="profiling" src="https://user-images.githubusercontent.com/13177667/82349622-a35ee380-99fa-11ea-9565-5de10523feab.png">
<img width="1277" alt="profiling2" src="https://user-images.githubusercontent.com/13177667/82349637-a78b0100-99fa-11ea-8bd4-949d758b7dcd.png">

**Additional Information:**
 - OS: MacOS
 - OS Version: MacOS Catalina 10.15.4
- Darklaf Version: 2.1.1
- JDK: Oracle JDK 9 (or higher)
-Miglayout (https://github.com/mikaelgrev/miglayout) 5.2

**Additional context**

**Comment by weisJ** [comment]
Does this occur while typing or when resizing the component. Could you please provide a minimal reproducible example? If its related to mixed LTR and RTL text this should be quite straight forward. Its very difficult for me to extract the cause of the issue this way. Ideally this example also contains text that will cause performance hits.

**Comment by slimzghal** [comment]
Writing an RTL-text is already very slow and sluggish. Combining RTL and LTR makes the GUI pause for a long time (no need to resize the window). Interacting with the GUI is then almost impossible from that point on. Also, there is an issue with marking selected text correctly (but that's a different issue).

**Comment by weisJ** [comment]
Minimal example.

````java
JTextComponent text = ...
text.setText(bidirectionalText); // bidirectionalText is any bidirectional text.
text.setMargin(new Insets(5,5,5,5)); // Any no-zero margins.
````
