### ISSUE TITLE
Add a horizontal scroll bar to JComboBox popup.

### ISSUE THREAD

**Issue by GraxCode** [weisJ/darklaf#175]
**Describe the bug**
Horizontal scroll is not possible in JComboBox with preferred size lower than size it would normally have. The user cannot view all items fully.

**To Reproduce**
```java
JComboBox<Object> selection = new JComboBox<>(new String[] { "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. " });
selection.setPreferredSize(new Dimension(200,  methodSelection.getPreferredSize().height));
```
add it to a GridBagLayout
**Screenshots**
![Screenshot_12](https://user-images.githubusercontent.com/24767548/83548609-4f78f200-a504-11ea-9689-571c48c0ddf1.png)

If you have any suggestions what would be better than using JComboBox let me know.

**Comment by weisJ** [comment]
I can add a horizontal scrollbar to the popup. However if the space is available a combobox should calculate its size based on the largest entry as the scrollbar solves the issue in the popup but not the combobox itself (the entry will still be clipped):

````java
String[] entries = new String[] {...};
String longestEntry = Arrays.stream(entries).max(Comparator.comparingInt(String::length)).get();
JComboBox<Object> combo= new JComboBox<>(entries);
combo.setPrototypeDisplayValue(longestEntry);
````

Nonetheless it's probably useful to have the option the read the entire entry in the popup.
