### ISSUE TITLE
[JTable] setHorizontalAlignement on label not honoured in TableCellRenderer

### ISSUE THREAD

**Issue by tychobrailleur** [weisJ/darklaf#176]
**Describe the bug**

`setHorizontalAlignment` is ignored on a label when set in a `TableCellRenderer`:

![Screenshot 2020-06-02 at 20 00 26](https://user-images.githubusercontent.com/114285/83559254-2f4d3100-a50c-11ea-814b-311e13522d82.png)

The behaviour is different to vanilla Swing where alignment is honoured:

![Screenshot 2020-06-02 at 20 00 06](https://user-images.githubusercontent.com/114285/83559295-44c25b00-a50c-11ea-9f1b-d1581da9ee20.png)

**To Reproduce**
Repro can be found there:
https://gist.github.com/tychobrailleur/73b79037f06885e210ea160cdd71ab81

Commenting out [this line](https://gist.github.com/tychobrailleur/73b79037f06885e210ea160cdd71ab81#file-centeredlabelframe-java-L89) shows normal behaviour.

**Screenshots**
See above.

**Additional Information:**
 - OS: macos
 - OS Version: 10.14.6
- Darklaf Version: 2.2.1

**Additional context**
Problem seems to occur on other platforms too.

**Comment by weisJ** [comment]
This bug has been introduced with my efforts to provide consistent background/foreground visuals for cell renderers that don't extend the Darklaf by wrapping the renderer on my end.
