### ISSUE TITLE
Cannot click on the lower half of a tall button

### ISSUE THREAD

**Issue by stanio** [weisJ/darklaf#177]
**Describe the bug**

Cannot activate a tall button clicking near the middle or the bottom half of it.

**To Reproduce**

```java
import java.awt.FlowLayout;
import javax.swing.*;

import com.github.weisj.darklaf.LafManager;

public class ButtonTest extends JFrame {

    ButtonTest() {
        super("Button Test");
        super.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        super.setLayout(new FlowLayout());

        super.add(new JButton(new ImageIcon("tall-20x100.png")));
    }

    public static void main(String[] args) {
        SwingUtilities.invokeLater(() -> {
            LafManager.setTheme(LafManager.getPreferredThemeStyle());
            LafManager.install();

            JFrame frame = new ButtonTest();
            frame.pack();
            frame.setVisible(true);
        });
    }

}
```

**Screenshots**

![button-test](https://user-images.githubusercontent.com/1247730/83656682-7ef13280-a5c8-11ea-8e87-70eaefa94709.png)

**Additional Information:**
 - OS: Windows
 - OS Version: 10
- Darklaf Version: 2.2.1

**Additional context**

Java 8 and Java 11, Screen scaling 1.25 (125%) and 1.5 (150%)

**Comment by weisJ** [comment]
> Java 8 and Java 11, Screen scaling 1.25 (125%) and 1.5 (150%)

Does this mean the issue doesn't happen when scaling is set to 100% ?

**Comment by weisJ** [comment]
I see. I didn't think of this use case as I have created [JTabFrame](https://github.com/weisJ/darklaf/wiki/Components#jtabframe) for this exact purpose.
