### ISSUE TITLE
Don't use maven version ranges

### ISSUE THREAD

**Issue by hupfdule** [weisJ/darklaf#18]
I just saw that you changed the maven coordinates in the README in commit  95b1f93e5014819c394a93856cde6096b4f44c54 to include version ranges. This is bad practice as the build isn't reproducible anymore. I therefore advise to revert this change and specify an explicit version.

**Comment by weisJ** [comment]
Reverted in e8a3a77d26d1cf4e6476b1a7cc8313a4765f357c
