### ISSUE TITLE
Can you please clarify how darklaf relates to the current Darcula?

### ISSUE THREAD

**Issue by vlsi** [weisJ/darklaf#19]
Thanks for the LaF.

AFAIK, the up to date Darcula is located in IDEA's repository: https://github.com/JetBrains/intellij-community/tree/1bc324ce785de1917f3ad0e0f99ceb4bf895105a/platform/platform-impl/src/com/intellij/ide/ui/laf/darcula

Can you please clarify if `darklaf` builds upon that version or not?

**Comment by weisJ** [comment]
Darklaf originally started as an extension of [Darcula](https://github.com/bulenkov/Darcula) implementing the newer design language of the Jetbrains products. Some things are taken from the [IntelliJ](https://github.com/JetBrains/intellij-community/tree/1bc324ce785de1917f3ad0e0f99ceb4bf895105a/platform/platform-impl/src/com/intellij/ide/ui/laf/darcula) repository and rewritten to not rely on IntelliJ specific APIs. In a way this project is part an extension of the old Darcula project part port/decoupling of the Darcula LaF as it sits in the IntelliJ repository and part custom written extension of the aforementioned (with the latter being the bulk portion).

**Comment by vlsi** [comment]
Oh, I see.
Konstantin said that their vision on Darcula is [it might make sense to decouple](https://github.com/bulenkov/Darcula/issues/56#issuecomment-526942616) `darcula-inside-intellij` from intellij platform, then it could be reused for other places.

I just thought you made that happen.

Now I see you are doing a mix :)
