### ISSUE TITLE
Darklaf 2.4.0 not in Maven repository

### ISSUE THREAD

**Issue by pmouawad** [weisJ/darklaf#192]
Hello,
Thanks for last release.

I don't see artifact of version in Maven repo:
https://repo.maven.apache.org/maven2/com/github/weisj/darklaf-core/

Is this expected ?
Thanks

**Comment by weisJ** [comment]
That’s not expected, should be up now. Thank you for reporting it.

**Comment by pmouawad** [comment]
Thanks !
