### ISSUE TITLE
When Darklaf is enable, it is not possible to input text in a numeric column DefaultTableModel

### ISSUE THREAD

**Issue by pmouawad** [weisJ/darklaf#193]
**Describe the bug**
In JMeter when using 3rd party plugin ThroughputShapingTimer , it is not more possible to input ${varName} instead of number.
Values it erased by previous number.
Switching to System LAF removes the issue

**To Reproduce**

Download JMeter , install jmeter-plugins, start, click on JMeterPLugin icon, select second tab and install plugin Throughput Shaping TImer

Create test plan as screenshot:

<img width="1438" alt="Screen Shot 2020-07-09 at 13 24 30" src="https://user-images.githubusercontent.com/3127467/87034083-946d0400-c1e7-11ea-8d6c-5cd996f1f9fd.png">

**Screenshots**

Notice the Arrow on right of ${throughput}, and once I quit field, value is replaced by old numeric one 60.

<img width="1064" alt="Screen Shot 2020-07-09 at 13 14 37" src="https://user-images.githubusercontent.com/3127467/87033903-52dc5900-c1e7-11ea-96e9-81b12c51e875.png">

**Additional Information:**

Happens on Windows 10 and Mac OSX

**Additional context**

Below information on concerned code:

https://github.com/undera/jmeter-plugins/blob/master/plugins/tst/src/main/java/kg/apc/jmeter/timers/VariableThroughputTimerGui.java#L224
https://github.com/apache/jmeter/blob/master/src/core/src/main/java/org/apache/jmeter/gui/util/PowerTableModel.java

**Comment by pmouawad** [comment]
Hello,
First thanks for your reactivity in fixing the bug I reported.

I tried last integration and issue is still there.

Try entering ${varName} in duration field, it is not possible.

Regards

**Comment by weisJ** [comment]
Integration versions are only published at midnight. I haven't gotten around to manually publish one with the fixes.
