### ISSUE TITLE
Unable to rename new folder after creating it in FileBrowser

### ISSUE THREAD

**Issue by pmouawad** [weisJ/darklaf#199]
**Describe the bug**

See https://bz.apache.org/bugzilla/show_bug.cgi?id=64453

**To Reproduce**

Using latest build of JMeter + latest integration build of Darklaf including the fix for 196.
Scenario:
- Open JMeter
- Templates
- Select any
- File > Save As
- Go to a folder where you can write
- Click on Create New Folder button
- You can't rename it

**Screenshots**

<img width="521" alt="Screen Shot 2020-07-29 at 12 28 15" src="https://user-images.githubusercontent.com/3127467/88789389-ff7e7a80-d196-11ea-9ddf-d99a0c05b865.png">

**Additional Information:**
 - OS: macOS
 - OS Version: 10.11.6
- Darklaf Version: latest integration of today

**Comment by weisJ** [comment]
> You can't rename it

What do you exactly mean by this?
- It doesn't enter rename mode after pressing new folder
or
- It isn't possible to manually enter rename mode

Also, did is the second row not displaying the item? What is the content of "NewFolder.6"?

**Comment by weisJ** [comment]
Reproduction requires to selected. List instead of grid view.

**Comment by pmouawad** [comment]
> > You can't rename it
> 
> What do you exactly mean by this?
> 
>     * It doesn't enter rename mode after pressing new folder
>       or

It passes in rename mode, but you can't enter anything
> 
>     * It isn't possible to manually enter rename mode
> 
> 
> Also, did is the second row not displaying the item? What is the content of "NewFolder.6"?

It is empty, it's a folder which names was automatically created when clicking on create folder

**Comment by pmouawad** [comment]
> Reproduction requires to selected. List instead of grid view.

Can you clarify ? 
Thanks

**Comment by weisJ** [comment]
At the top right of the file chooser you can switch between "List" (the icon with the grid) and "Details" (the list icon). The issue happens only when "Details" is selected and affects every rename operation.

I know the names for the individual modes is a bit unfortunate but those are the default value of swing.

**Comment by pmouawad** [comment]
Hello @weisJ ,
Thanks for fix, it works, tested on latest.integration.

Regards

**Comment by pmouawad** [comment]
Hello @weisJ ,
When do you plan a release of 2.4.2 ?

Thanks

**Comment by weisJ** [comment]
`2.4.2` is now available.
