### ISSUE TITLE
Support for platforms different than windows.

### ISSUE THREAD

**Issue by weisJ** [weisJ/darklaf#2]
Currently only windows is fully supported. Without having access specifically to a macOS machine the finer details need to be adjusted for each platform.
Specifically custom window decorations currently are only tailored to suit the windows platform.
The plan is to provide custom decorations for most of the major platforms.

<sub>Sent from <a href="https://itunes.apple.com/cn/app/id1314212521">PPHub</a></sub>

**Comment by Bios-Marcel** [comment]
What's the state of Linux support? Do you need somebody looking into that as well?

**Comment by weisJ** [comment]
Yes I still need someone to look over the Linux related bits and pieces. (Note that in the current version under certain screen scaling factors some elements may appear too big. That should be fixed in an upcoming version)

**Comment by Bios-Marcel** [comment]
it would be great to have an overall overview of which features are broken on which platforms

**Comment by weisJ** [comment]
Most features if broken will be broken on all platforms. Though Linux and macOS might have some scaling issues as I’m not using those too often. Most adjustments fall under the category of conforming to the platform standard for certain visual elements and behaviors. I will try to create a list of current things that are unfinished or don’t work at the moment during the week and create some issues for those.

**Comment by Bios-Marcel** [comment]
Cool, thanks.

**Comment by weisJ** [comment]
I have put up a list with things that I'm currently aware of [here](https://github.com/weisJ/darklaf/blob/master/README.md). I'll add more things if they come up.

**Comment by Bios-Marcel** [comment]
Cool, I'll see whether I'll be able to contribute to this project at work. Since we are currently looking to add a dark-mode to our software. Gotta see which priority this gets assigned :D

**Comment by vlsi** [comment]
macOS build fails as follows :(

```
> Configure project :
Building on OS: Mac OS X
Using JDK: /Library/Java/JavaVirtualMachines/adoptopenjdk-8-222.jdk/Contents/Home/jre

> Task :compileJniplatformX64SharedLibraryJniplatformCpp FAILED
/Users/vladimirsitnikov/Documents/work/darklaf/src/jniplatform/cpp/JNIDecorations.h:25:10: fatal error: 'windows.h' file not found
#include <windows.h>
         ^~~~~~~~~~~
1 error generated.

In file included from /Users/vladimirsitnikov/Documents/work/darklaf/src/jniplatform/cpp/com_github_weisj_darklaf_platform_windows_JNIDecorations.h:2:
/Library/Java/JavaVirtualMachines/adoptopenjdk-8-222.jdk/Contents/Home/include/jni.h:45:10: fatal error: 'jni_md.h' file not found
#include "jni_md.h"
         ^~~~~~~~~~
1 error generated.

In file included from /Users/vladimirsitnikov/Documents/work/darklaf/src/jniplatform/cpp/JNIDecorations.cpp:24:
/Users/vladimirsitnikov/Documents/work/darklaf/src/jniplatform/cpp/JNIDecorations.h:25:10: fatal error: 'windows.h' file not found
#include <windows.h>
         ^~~~~~~~~~~
1 error generated.


> Task :compileJniplatformX86SharedLibraryJniplatformCpp FAILED
/Users/vladimirsitnikov/Documents/work/darklaf/src/jniplatform/cpp/JNIDecorations.h:25:10: fatal error: 'windows.h' file not found
#include <windows.h>
         ^~~~~~~~~~~
1 error generated.

In file included from /Users/vladimirsitnikov/Documents/work/darklaf/src/jniplatform/cpp/com_github_weisj_darklaf_platform_windows_JNIDecorations.h:2:
/Library/Java/JavaVirtualMachines/adoptopenjdk-8-222.jdk/Contents/Home/include/jni.h:45:10: fatal error: 'jni_md.h' file not found
#include "jni_md.h"
         ^~~~~~~~~~
1 error generated.

In file included from /Users/vladimirsitnikov/Documents/work/darklaf/src/jniplatform/cpp/JNIDecorations.cpp:24:
/Users/vladimirsitnikov/Documents/work/darklaf/src/jniplatform/cpp/JNIDecorations.h:25:10: fatal error: 'windows.h' file not found
#include <windows.h>
         ^~~~~~~~~~~
1 error generated.
```

**Comment by weisJ** [comment]
As for now I have simply disabled the compilation of the native libraries as they are - at this point - only intended for windows anyway. (c8a8168772ef6f51c677bb226293019709802c86)

**Comment by weisJ** [comment]
If #32 has been implemented compilation of native binaries needs to be made more flexible.

**Comment by vlsi** [comment]
I suggest that platform-tailored native binaries should come to their own projects.
WDYT?

**Comment by weisJ** [comment]
This seems like a good idea, especially because implementations very between each platform.

**Comment by vlsi** [comment]
Well, the next question is "how should it be released".
For instance, I doubt one can compile macOS-specific code using Windows, and one can't compile Windows-specific code in macOS.

That means platform-specific modules have to be built on different machines.

**Comment by weisJ** [comment]
I was thinking about the very same thing and apparently one can share resources between tasks on different machines with github actions. So one could only compile the platform specific code on the relative platform which then gets bundled when building the binaries.

**Comment by vlsi** [comment]
That is true. However, GitHub Actions does not support FreeBSD yet.

**Comment by weisJ** [comment]
If this is an real issue really depends on how likely someone contributes platform specific code for FreeBSD. If necessary one could include these libraries manually to the resulting jar (or hope that FreeBSD gets added to actions in the future).

**Comment by weisJ** [comment]
I guess this issue isn't quite up to date anymore. Any further enhancements should have their own issue, so I'm closing this.
