### ISSUE TITLE
Hide Title Bar in Full Screen

### ISSUE THREAD

**Issue by mEncinoso** [weisJ/darklaf#200]
**Describe the bug**
When toggle the app to full screen mode, title bar doesn't dissapear as it does by default without setting any theme.

**To Reproduce**
I am using VLCJ lib to make a video player. It has a method called mediaPlayer.toggleFullScreen(); which I use to toggle full screen mode by double clicking it.

**Screenshots**

No theme:
![imagen](https://user-images.githubusercontent.com/35850578/88795999-e080e800-d198-11ea-97e7-19e8866bdd5b.png)
Full Screen:
![imagen](https://user-images.githubusercontent.com/35850578/88796030-ee366d80-d198-11ea-8822-afea8a886387.png)

Theme applied:
![imagen](https://user-images.githubusercontent.com/35850578/88796131-132ae080-d199-11ea-9476-c6d87b1d61e4.png)
Full Screen:
![imagen](https://user-images.githubusercontent.com/35850578/88796150-1aea8500-d199-11ea-8c95-b8f012f5c1fb.png)

**Additional Information:**
 - OS: Windows 10
 - Darklaf Version: 2.4.0

**Comment by weisJ** [comment]
VLCJ does some hacky stuff to achieve their fullscreen mode. I had to make some adjustments to adhere to the behaviour the library is expecting. You can already try out, whether it works with the latest integration version.
