### ISSUE TITLE
Opening GUI shows a horizontal scrollbar that keeps sliding to the right

### ISSUE THREAD

**Issue by pmouawad** [weisJ/darklaf#201]
**Describe the bug**
See this:
https://bz.apache.org/bugzilla/show_bug.cgi?id=64638

**To Reproduce**
As issue is now fixed in JMeter but through a change of UI, use a JMeter 5.3 with latest version of Darklaf.

**Additional Information:**
 - OS: MacOS , Windows 10
 - OS Version: MAC OS 10.11.6 , Windows 10
- Darklaf Version: Latest integration and 2.2.1

**Comment by weisJ** [comment]
Would you mind posting the source for the gui that produces the issue as a reference?

**Comment by pmouawad** [comment]
Hello @weisJ ,
See:
https://github.com/apache/jmeter/commit/c037ee577a03a895de1b5e0163b34db01e6eb4ac

The old code had the issue, but since I reworked the UI , we don't face it anymore, but issue is in Darklaf as it only happens with Darklaf.

Regards

**Comment by weisJ** [comment]
Yes I am aware of the old code. It's just a huge amount of dependencies to try to reproduce the issue. Where exactly comes the `JScrollPane` into play? That's not clear from the diff.

**Comment by pmouawad** [comment]
It was jsonValue = new JLabeledTextArea(JMeterUtils.getResString(JSON_ASSERTION_EXPECTED_VALUE)); 
in JSONPathAssertionGui

**Comment by pmouawad** [comment]
Thanks @weisJ , test on latest.integration , and confirmed fix.
