### ISSUE TITLE
[Feature Request] Change display name of Theme

### ISSUE THREAD

**Issue by jbax** [weisJ/darklaf#205]
**General description**
Right now all themes come with default names in English. I'm looking for some mechanism to easily let me change the theme name that is displayed to the end user. For example, them "High Contrast Light" could be translated to Portuguese as "Claro, em Alto Contraste". Also "IntelliJ" name makes zero sense to most people who are not developers. I'd like to display that as just "Default light" or something.

This suggestion is:
- [X] Visual

All I'm looking for is an extra method in class `Theme` that allows me to invoke `setName(String newThemeName)`, then have this change propagated. Or if it's simpler something like `LafManager.renameTheme(originalName, newName)` would do the job even faster.

**Comment by weisJ** [comment]
Thank you for the suggestion.

I don't think that allowing the name of a them to be mutated is the way to go though. The `Theme` class is intentionally designed to be immutable. Instead I am was thinking of utilizing the already existing `ThemeDelegate` class to wrap the theme with an overwritten `#getDisplayName` method.

Changing the name of an existing theme then could look like this:
````java
ResourceBundle bundle = ...
Theme[] themes = LafManager.getRegisteredThemes();
for (Theme theme : themes) {
    LafManager.replaceTheme(theme, theme.withDisplayName(bundle.getString(theme.getPrefix())));
}
````
with the corresponding resource bundle
````properties
intellij = Light
solarized_light = Solarized Light
darcula = Darcula 
one_dark = Dark
solarized_dark = Solarized Dark
high_contrast_light = High Contrast Light
high_contrast_dark = High Contrast Dark
````

You can try out the changes using the latest snashot.
````kotlin
repositories {
    maven {
        url = uri("https://oss.sonatype.org/content/repositories/snapshots/")
    }
}

configurations.all {
    resolutionStrategy.cacheChangingModulesFor(0, "seconds")
}

dependencies {
    implementation("com.github.weisj:darklaf-core:latest.integration")
}
````

**Comment by jbax** [comment]
This worked perfectly well, thank you!
