### ISSUE TITLE
Table cell editing can't be started through mouse click.

### ISSUE THREAD

**Issue by pmouawad** [weisJ/darklaf#206]
**Describe the bug**

When using a table and trying to edit a cell in a row, if you select the row, the cursor does not appear.
This is the component concerned:

https://github.com/apache/jmeter/blob/master/src/core/src/main/java/org/apache/jmeter/config/gui/ArgumentsPanel.java

**To Reproduce**

Use latest jmeter nightly build.
Select Test Plan , in User Defined Variables , click add, try to edit name, notice cursor does not appear
set a value in cell
try to edit it, you don't see the cursor neither

**Additional Information:**
 - OS: macOS, Windows 10
 - OS Version: MacOSX 10.11.6, Windows 10

- Darklaf Version: latest release 2.4.7

**Comment by weisJ** [comment]
Thank you for reporting. After examining the issue I discovered that this isn't a rendering issue but rather the fact that there is a bug where table cells are unable to be edited through mouse invocation.

**Comment by pmouawad** [comment]
Hello @weisJ ,
I tested latest integration, issue is fixed but there seems to be a display regression.

See screenshot:

<img width="187" alt="Screen Shot 2020-09-13 at 11 30 02" src="https://user-images.githubusercontent.com/3127467/93014817-a175ed00-f5b4-11ea-955a-f72d39e6158d.png">

Regards

**Comment by weisJ** [comment]
I did notice this too and fixed it in bba681969e6ea5fd9798a6b977e3dd324a4a88d3

**Comment by pmouawad** [comment]
But I tested latest integration, so it would include this no ?

**Comment by weisJ** [comment]
Have you tried building using the `--refresh-dependencies` option?

**Comment by pmouawad** [comment]
Hello,
yes I tried and it works indeed.
But I don't understand as bug was fixed, is it a later build ? 
Thanks

**Comment by weisJ** [comment]
Hi,
snapshots are only created at midnight (UTC) unless I manually publish the changes. You probably testes while the changes haven’t been published yet.

**Comment by pmouawad** [comment]
Hello @weisJ ,
When do you plan a release containing this fix ? 

Thanks
Regards

**Comment by weisJ** [comment]
Hello @pmouawad 

I'm currently doing some last cleanup tasks I have on my backlog and will probably release the next version tomorrow evening.

**Comment by weisJ** [comment]
@pmouawad Version `2.4.8` has been released.

**Comment by weisJ** [comment]
Hi @pmouawad 
Just a heads-up that there has been an issue where a NPE is thrown if no desktop properties are defined (this most likely affects Linux on Java 8). I have released a hotfix with version `2.4.9`.
