### ISSUE TITLE
ThreadTear Problem

### ISSUE THREAD

**Issue by Cryfix** [weisJ/darklaf#208]
Thread tear doesn't work because of the last update. Please help.
This is a Thread tear problem but help me.

Can we contact in private?
Discord: Cryfix#1818

Screenshoot: https://cdn.discordapp.com/attachments/755699147381800991/755757888751927306/unknown.png

**Comment by weisJ** [comment]
Could you please include the stacktrace as text instead of the image?
Also what do you mean by 
> the last update

do you know which version specifically causes the issue (the last version that made any changes to icon loading/rendering was `2.4.0`)

**Comment by weisJ** [comment]
Does this mean the issue doesn't happen anymore? Why did you close the issue?

**Comment by Cryfix** [comment]
> Does this mean the issue doesn't happen anymore? Why did you close the issue?

The problem is with me. I changed the folder. And now it works.

**Comment by weisJ** [comment]
Good to hear. Thank you for the clarification.

**Comment by Cryfix** [comment]
> Good to hear. Thank you for the clarification.

Can you write to me on Discord? 
Discord: Cryfix#1818
