### ISSUE TITLE
Text drawing on Java 8

### ISSUE THREAD

**Issue by cookiedragon234** [weisJ/darklaf#209]
Text rendering on Java 8 has very bad anti aliasing. It works completely fine on 14, but 8 does not.

Java 8:
```
java version "1.8.0_261"
Java(TM) SE Runtime Environment (build 1.8.0_261-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.261-b12, mixed mode)
```
![](https://i.binclub.dev/kf9g42g4.png)

Java 14:
```
openjdk version "14.0.2" 2020-07-14
OpenJDK Runtime Environment (build 14.0.2+12)
OpenJDK 64-Bit Server VM (build 14.0.2+12, mixed mode)
```
![](https://i.binclub.dev/kf9g2ddx.png)

**Additional Information:**
 - OS: Arch Linux x86_64
 - OS Version: 5.8.8-arch1-1
- Darklaf Version: 2.4.7

**Additional context**
Usage:
```Kotlin
LafManager.setTheme(DarculaTheme())
LafManager.install()
```
(Same on every other theme as well)

**Comment by cookiedragon234** [comment]
Also works fine on OpenJ9:
```
openjdk version "1.8.0_265"
OpenJDK Runtime Environment (build 1.8.0_265-b01)
Eclipse OpenJ9 VM (build openj9-0.21.0, JRE 1.8.0 Linux amd64-64-Bit Compressed References 20200728_727 (JIT enabled, AOT enabled)
OpenJ9   - 34cf4c075
OMR      - 113e54219
JCL      - c82ff0c20f based on jdk8u265-b01)
```

**Comment by weisJ** [comment]
Thank you for reporting!

Font antialiasing is a known issue with Java 8 on Linux. Could you please run with logging enabled
````java
LafManager.setLogLevel(Level.FINE);
````
Also what values do the system properties `"awt.useSystemAAFontSettings"`, `"swing.aatext"` have for you (Java 8 as well as Java 9)? The properties can be obtained using `System#getProperty`.

**Comment by cookiedragon234** [comment]
@weisJ 
```Java
awt.useSystemAAFontSettings: null
swing.aatext: null
[2020-09-19 15:56:11] [FINE] Setting log level to FINE [at com.github.weisj.darklaf.LafManager]
[2020-09-19 15:56:11] [FINE] Setting theme to Darcula [at com.github.weisj.darklaf.LafManager]
[2020-09-19 15:56:11] [FINE] Installing theme Darcula [at com.github.weisj.darklaf.LafManager]
[2020-09-19 15:56:11] [FINE] Setting 'Text-specific antialiasing enable key' = 'LCD HRGB antialiasing text mode' [at com.github.weisj.darklaf.task.FontDefaultsInitTask]
[2020-09-19 15:56:11] [FINE] Setting 'Text-specific LCD contrast key' = 'Text-specific LCD contrast key' [at com.github.weisj.darklaf.task.FontDefaultsInitTask]
```

**Comment by weisJ** [comment]
Please try the following
````java
System.setProerty("awt.useSystemAAFontSettings", "gasp"); //alternatively if this doesn’t work use "on"
System.setProerty("swing.aatext", "true");
````

**Comment by cookiedragon234** [comment]
@weisJ 

Gasp doesn't work, however on does. I found `lcd_hrgb` provided the best result (more documentation here: https://docs.oracle.com/javase/6/docs/technotes/guides/2d/flags.html#aaFonts).

Perhaps it would be useful if darklaf set this automatically on Java 8 and under?

**Comment by weisJ** [comment]
I have added 

> @weisJ
> 
> Gasp doesn't work, however on does. I found `lcd_hrgb` provided the best result (more documentation here: https://docs.oracle.com/javase/6/docs/technotes/guides/2d/flags.html#aaFonts).
> 
> Perhaps it would be useful if darklaf set this automatically on Java 8 and under?

Darklaf now uses a fallback value of `VALUE_TEXT_ANTIALIAS_LCD_HRGB` if the screen device support the appropriate bit depth of at least 15. Otherwise it will use `VALUE_TEXT_ANTIALIAS_ON`. Although I will log a warning that one should specify the value themselves in the JVM startup parameters or switch to Java 9 (or later).
