### ISSUE TITLE
Custom tree cell renderer with setIcon doesn't work anymore.

### ISSUE THREAD

**Issue by GraxCode** [weisJ/darklaf#217]
**Describe the bug**
Tree cell renderer with setIcon doesn't have any effect anymore.
![Screenshot_24](https://user-images.githubusercontent.com/24767548/98437609-d188ca80-20e3-11eb-8e57-962d2c0d05dd.png)
Cause is unknown. No stacktrace.

**Additional Information:**
 - OS: Win 10
- Darklaf Version: a9e0ce3

**Additional context**
My tree renderer: https://github.com/GraxCode/threadtear/blob/f5a55fe923819e6bb09f56a7579c4695f5ca40ae/gui/src/main/java/me/nov/threadtear/swing/tree/renderer/ClassTreeCellRenderer.java

**Comment by weisJ** [comment]
This should be fixed by 82331b08d1793b4e06cb129d07c779845cb2c83d. Could you please check whether this is the case for you?

**Comment by GraxCode** [comment]
Works like a charm.
