### ISSUE TITLE
[Feature Request] Persisting user preferences

### ISSUE THREAD

**Issue by ischumacher** [weisJ/darklaf#219]
**General description**
What is the motivation for this suggestion.
- Enable persisting of user preferences

This suggestion is:
- [ ] Visual
- [x] Behavioral

First, thank you for such a wonderful project. Second, I apologize if these feature exists somewhere and I lacked the skill/persistence to see it. 

To customize theme settings (such as increasing font size for a particular user's needs) there is the excellent and straightforward ThemeSettings dialog. However, there doesn't seem to be a way to serialize and persist these settings to disk so they may be reloaded the next time an application is started. If that feature does exist and I simply failed to see it, could you please point to the methods/procedure to do this? If this feature does not exist then this is my request to add it one day.

**Comment by weisJ** [comment]
> [...] However, there doesn't seem to be a way to serialize and persist these settings to disk so they may be reloaded the next time an application is started.

I did consider adding such a feature. However there isn't a good way to do this without forcing the usage of any particular mechanism. Most applications (if they have settings which need to be persisted across sessions) already have a mechanism to persist the necessary information.
My suggestion would be to to use the properties exposed through `ThemeSettings#getInstance` and save them using your technology of choice (e.g. the [Preferences API](https://docs.oracle.com/javase/7/docs/api/java/util/prefs/Preferences.html)).

What I could do to make this process easier is to expose the internal `SettingsConfiguration` through a `ThemeSettings#exportConfiguration` function and make `SettingsConfiguration` serializable.
It's already possible to import a `SettingsConfiguration` through `ThemeSettings#setConfiguration`.

**Comment by ischumacher** [comment]
Well I'm glad I didn't overlook something obvious then. I'll see if I can figure out how to do this myself in a local copy for now. Thanks.

**Comment by weisJ** [comment]
If you feel it would be beneficial I could add a sample implementation to the demo samples.

**Comment by ischumacher** [comment]
That would be great.

**Comment by weisJ** [comment]
A sample implementation can be found [here](https://github.com/weisJ/darklaf/blob/master/core/src/test/java/ui/PersistentThemeSettingsDemo.java). Note that you will have to use the snapshot version to get and serialize the `SettingsConfiguration`.

**Comment by ischumacher** [comment]
Thanks very much. That is probably enough to close this I think. Seems enough to me.
