### ISSUE TITLE
Please include LICENSE and NOTICE to the artifact jar

### ISSUE THREAD

**Issue by vlsi** [weisJ/darklaf#22]
Hi, darklaf looks nice, and MIT is a great license choice (well, Apache-2.0 might be slightly less better), however, would you please add the relevant license to the resulting jar file?

For instance, https://repo1.maven.org/maven2/com/github/weisj/darklaf/1.3.3.4/ does not have license, so it would be a bit complicated for third-parties to comply with darklaf license.

1) I suggest that darklaf.jar should include at least LICENSE for darklaf itself

2) It looks like you include bits from IntelliJ platform (judging by NOTICE.txt). I guess that NOTICE.txt must be re-distributed with binary artifacts as well.

The suggested location is `META-INF/LICENSE` and or `META-INF/NOTICE`.

PS. Having a license in `META-INF/LICENSE` would simplify license compliance for the projects that bundle `darklaf`.

**Comment by weisJ** [comment]
Licenses are now included in the jar (ac9de657243d882715c9e3fef8972973f7e243cb). Is this what you imagined?

**Comment by vlsi** [comment]
Unfortunately, I can't verify that as the build fails for me with https://github.com/weisJ/darklaf/issues/2#issuecomment-586466941

So I would probably wait for the new version.

**Comment by vlsi** [comment]
darklaf-1.3.3.4.jar bundles org/pbjar/jxlayer/, so please bundle its license to the jar as well.

**Comment by vlsi** [comment]
Fixed in https://github.com/weisJ/darklaf/pull/33
