### ISSUE TITLE
Opaque tooltip on Linux

### ISSUE THREAD

**Issue by weisJ** [weisJ/darklaf#220]
@weisJ This bug seems to still be appearing on Linux.
![image](https://user-images.githubusercontent.com/53862811/100724186-8304de00-33ba-11eb-83c8-705199ba6514.png)

I'm on Arch Linux x86_64 (5.9.8-arch1-1).

It also seems to be incredibly hard to activate tooltips. They don't appear after hovering, but can in some circumstances be triggered with control + f1, however this is very hard to trigger.

_Originally posted by @x4e in https://github.com/weisJ/darklaf/issues/180#issuecomment-736364221_

**Comment by weisJ** [comment]
> This bug seems to still be appearing on Linux.

The popup for the tooltip is configured here:

https://github.com/weisJ/darklaf/blob/d47b78e6bf0e8cbdf0df5e537b26ee83917f875f/core/src/main/java/com/github/weisj/darklaf/ui/DarkPopupFactory.java#L97

It would be very insightful what `PopupType` the popup has.
Are you comfortable with building the project locally? You can start the tooltip demo using
````
gradlew runDemo --class ui.toolTip.ToolTipDemo
````


> It also seems to be incredibly hard to activate tooltips. They don't appear after hovering, but can in some circumstances be triggered with control + f1, however this is very hard to trigger.

The laf shouldn't change how tooltips are activated. Do you experience the same issue when using the system look and feel?

**Comment by x4e** [comment]
>  Are you comfortable with building the project locally? You can start the tooltip demo using
![image](https://user-images.githubusercontent.com/53862811/100805365-7027f300-3426-11eb-8820-394959b5edca.png)
> It would be very insightful what PopupType the popup has.
type == HEAVY_WEIGHT

> The laf shouldn't change how tooltips are activated. Do you experience the same issue when using the system look and feel?
On the demo it seems to be working ok. Probably something I'm doing wrong so don't worry about this part.

**Comment by x4e** [comment]
Actually I take back that last part. It seems that sometimes the tooltip is triggered as my `System.out.println(type)` in `DarkPopupFactory.java` is being triggered, however often no tooltip shows up.
This is likely related to the opaque problem in some way.

**Comment by weisJ** [comment]
Could you print out the component hierarchy of the tooltip together with the corresponding background colours?

**Comment by x4e** [comment]
Which variables are those stored in?

**Comment by weisJ** [comment]
You have to loop over the parents of the tooltip i.e.
````java
Component p = content;
while(p != null) {
    System.out.println(p);
    System.out.println(p.getBackground());
    System.out.println(p.isOpaque());
    System.out.println("");
    p = p.getParent()
}
````

**Comment by x4e** [comment]
This part when I hover over the button (no tooltip is shown)
```Java
javax.swing.JFrame[frame0,601,1242,337x296,invalid,layout=java.awt.BorderLayout,title=ToolTip Demo,resizable,normal,defaultCloseOperation=EXIT_ON_CLOSE,rootPane=javax.swing.JRootPane[,6,43,325x247,layout=javax.swing.JRootPane$RootLayout,alignmentX=0.0,alignmentY=0.0,border=com.github.weisj.darklaf.ui.rootpane.DarkRootPaneBorder@1145ecf,flags=16777673,maximumSize=,minimumSize=,preferredSize=],rootPaneCheckingEnabled=true]
java.awt.SystemColor[i=7]
true
--
javax.swing.JToolTip[,0,0,1x1,invalid,alignmentX=0.0,alignmentY=0.0,border=com.github.weisj.darklaf.ui.tooltip.DarkTooltipBorder@54442b74,flags=16777224,maximumSize=,minimumSize=,preferredSize=,tipText=<html><p style="color:red;">This is the ToolTip demo text!<br><p style="color:blue;">This is the ToolTip demo text!<br><p style="color:green;">This is the ToolTip demo text!<br></html>]
UIColor[r=247, g=247,b=247]
true
--
javax.swing.JPanel[null.contentPane,0,0,0x0,invalid,layout=javax.swing.JRootPane$1,alignmentX=0.0,alignmentY=0.0,border=,flags=16777217,maximumSize=,minimumSize=,preferredSize=]
UIColor[r=242, g=242,b=242,a=000]
false
--
javax.swing.JLayeredPane[null.layeredPane,0,0,0x0,invalid,alignmentX=0.0,alignmentY=0.0,border=,flags=0,maximumSize=,minimumSize=,preferredSize=,optimizedDrawingPossible=true]
UIColor[r=242, g=242,b=242]
false
--
javax.swing.JRootPane[,0,0,0x0,invalid,layout=javax.swing.JRootPane$RootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=16777673,maximumSize=,minimumSize=,preferredSize=]
UIColor[r=242, g=242,b=242]
true
--
javax.swing.Popup$HeavyWeightWindow[win1,809,1358,1x1,invalid,hidden,layout=java.awt.BorderLayout,rootPaneCheckingEnabled=true]
java.awt.SystemColor[i=7]
true
--
javax.swing.JFrame[frame0,601,1242,337x296,invalid,layout=java.awt.BorderLayout,title=ToolTip Demo,resizable,normal,defaultCloseOperation=EXIT_ON_CLOSE,rootPane=javax.swing.JRootPane[,6,43,325x247,layout=javax.swing.JRootPane$RootLayout,alignmentX=0.0,alignmentY=0.0,border=com.github.weisj.darklaf.ui.rootpane.DarkRootPaneBorder@1145ecf,flags=16777673,maximumSize=,minimumSize=,preferredSize=],rootPaneCheckingEnabled=true]
java.awt.SystemColor[i=7]
true
```
This part when I press control+f1 (tooltip is shown)
```Java
--
javax.swing.JToolTip[,0,0,1x1,invalid,alignmentX=0.0,alignmentY=0.0,border=com.github.weisj.darklaf.ui.tooltip.DarkTooltipBorder@73db22ba,flags=16777224,maximumSize=,minimumSize=,preferredSize=,tipText=<html><p style="color:red;">This is the ToolTip demo text!<br><p style="color:blue;">This is the ToolTip demo text!<br><p style="color:green;">This is the ToolTip demo text!<br></html>]
UIColor[r=247, g=247,b=247]
true
--
javax.swing.JPanel[null.contentPane,0,0,0x0,invalid,layout=javax.swing.JRootPane$1,alignmentX=0.0,alignmentY=0.0,border=,flags=16777217,maximumSize=,minimumSize=,preferredSize=]
UIColor[r=242, g=242,b=242,a=000]
false
--
javax.swing.JLayeredPane[null.layeredPane,0,0,0x0,invalid,alignmentX=0.0,alignmentY=0.0,border=,flags=0,maximumSize=,minimumSize=,preferredSize=,optimizedDrawingPossible=true]
UIColor[r=242, g=242,b=242]
false
--
javax.swing.JRootPane[,0,0,0x0,invalid,layout=javax.swing.JRootPane$RootLayout,alignmentX=0.0,alignmentY=0.0,border=,flags=16777673,maximumSize=,minimumSize=,preferredSize=]
UIColor[r=242, g=242,b=242]
true
--
javax.swing.Popup$HeavyWeightWindow[win3,716,1356,1x1,invalid,hidden,layout=java.awt.BorderLayout,rootPaneCheckingEnabled=true]
java.awt.SystemColor[i=7]
true
--
javax.swing.JFrame[frame0,601,1242,337x296,invalid,layout=java.awt.BorderLayout,title=ToolTip Demo,resizable,normal,defaultCloseOperation=EXIT_ON_CLOSE,rootPane=javax.swing.JRootPane[,6,43,325x247,layout=javax.swing.JRootPane$RootLayout,alignmentX=0.0,alignmentY=0.0,border=com.github.weisj.darklaf.ui.rootpane.DarkRootPaneBorder@1145ecf,flags=16777673,maximumSize=,minimumSize=,preferredSize=],rootPaneCheckingEnabled=true]
java.awt.SystemColor[i=7]
true
```

**Comment by weisJ** [comment]
For the opacity issue please try to check out the [linux/tooltip](https://github.com/weisJ/darklaf/tree/linux/tooltip) branch.

As for the tooltip not being displayed sometimes you might want to try to set `System.setProperty("darklaf.animations", "false")`.

**Comment by weisJ** [comment]
@x4e I have published the linux/tooltip branch. It can be tested using `com.github.weisj:darklaf-core-linux-popup:latest.integration` as a dependency.

**Comment by x4e** [comment]
Thank You! That works a lot better. 
There are still some minor issues highlighted in this video (https://youtu.be/-quKrqTuL40), being white background, tooltip being slightly displaced sometimes, and previous tooltips being visible in the background).
This is great though thanks!

**Comment by weisJ** [comment]
I just released another snapshot version for the `linux/tooltip` branch. 
I had to deal with incorrect tooltip positioning multiple times already and it always was caused by system scaling factors. To make sure where to look for the problem could you log the following information for me:
````java
GraphicsConfiguration gc = GraphicsEnvironment.getLocalGraphicsEnvironment().getDefaultScreenDevice().getDefaultConfiguration();
AffineTransform  transform = gc.getDefaultTransform();

System.out.println(gc);
System.out.println(gc.getDefaultScreenDevice());
System.out.println(transform);
````

**Comment by x4e** [comment]
> Also which java version are you using?

OpenJDK 15.0.1

To make your code run I had to change it to the following (I believe it has the intended functionality):
```Java
var gs = GraphicsEnvironment.getLocalGraphicsEnvironment().getDefaultScreenDevice();
var gc = gs.getDefaultConfiguration();
System.out.println(gc);
System.out.println(gs);
System.out.println(gc.getDefaultTransform());
```
And the output is:
```
X11GraphicsConfig[dev=X11GraphicsDevice[screen=0],vis=0x21]
X11GraphicsDevice[screen=0]
AffineTransform[[1.0, 0.0, 0.0], [0.0, 1.0, 0.0]]
```
Video of tooltips in latest update: https://youtu.be/qcaXepwhWRY

**Comment by weisJ** [comment]
Does [TooltipTest](https://github.com/weisJ/darklaf/blob/f099bfe72aed0e151c566be52b295f60aefa4bff/core/src/test/java/test/TooltipTest.java) fail for you with the `linux/tooltip` branch?

**Comment by x4e** [comment]
Sorry for the late response.

![tooltip_linux](https://user-images.githubusercontent.com/53862811/103484999-fdc27e00-4dea-11eb-9525-a8679357bbf7.png)
`gradlew test` succeeds with this tooltip screenshot so I'm guessing that means that the test is suceeding.

Tooltips in my actual project do not work at all now, and just briefly blink a black square before going away.

**Comment by weisJ** [comment]
@x4e the new snapshot version `com.github.weisj:darklaf-core-linux-popup:latest.integration` should fix the transparency issue. Could you verify that this is the case for you?

**Comment by weisJ** [comment]
Positioning also shouldn't be an issue anymore.

**Comment by x4e** [comment]
Thank you so much! It works perfectly now. It's great to be able to maintain a project like this on so many different operating systems.
