### ISSUE TITLE
NPE in BasicEditorPaneUI.cleanDisplayProperties with Darklaf Intellij 

### ISSUE THREAD

**Issue by pmouawad** [weisJ/darklaf#221]
**Describe the bug**

With latest jmeter version 5.4 and  darklaf release darklaf 2.4.10 we get an exception report:

`o.a.j.g.a.ActionRouter: Error processing
org.apache.jmeter.gui.action.LookAndFeelCommand@11015ca0
java.lang.NullPointerException: null
at
javax.swing.plaf.basic.BasicEditorPaneUI.cleanDisplayProperties(BasicEditorPaneUI.java:275)
~[?:?]
at
javax.swing.plaf.basic.BasicEditorPaneUI.uninstallUI(BasicEditorPaneUI.java:101)
~[?:?]
at
com.github.weisj.darklaf.ui.text.dummy.DummyTextPaneUI.uninstallUI(DummyTextPaneUI.java:60)
~[darklaf-core-2.4.10.jar:2.4.10]
at
com.github.weisj.darklaf.ui.text.bridge.DarkEditorPaneUIBridge.cleanDisplayProperties(DarkEditorPaneUIBridge.java:91)
~[darklaf-core-2.4.10.jar:2.4.10]
at
com.github.weisj.darklaf.ui.text.bridge.DarkEditorPaneUIBridge.uninstallUI(DarkEditorPaneUIBridge.java:73)
~[darklaf-core-2.4.10.jar:2.4.10]
at javax.swing.JComponent.uninstallUIAndProperties(JComponent.java:700)
~[?:?]
at javax.swing.JComponent.setUI(JComponent.java:675) ~[?:?]
at javax.swing.text.JTextComponent.setUI(JTextComponent.java:342) ~[?:?]
at javax.swing.text.JTextComponent.updateUI(JTextComponent.java:352) ~[?:?]
at
org.apache.jorphan.gui.DynamicStyle.collectComponents(DynamicStyle.java:197)
~[jorphan.jar:5.4]
at
org.apache.jorphan.gui.DynamicStyle.collectComponents(DynamicStyle.java:217)
~[jorphan.jar:5.4]
at
org.apache.jorphan.gui.DynamicStyle.collectComponents(DynamicStyle.java:217)
~[jorphan.jar:5.4]
at
org.apache.jorphan.gui.DynamicStyle.collectComponents(DynamicStyle.java:217)
~[jorphan.jar:5.4]
at
org.apache.jorphan.gui.DynamicStyle.collectComponents(DynamicStyle.java:217)
~[jorphan.jar:5.4]
at
org.apache.jorphan.gui.DynamicStyle.collectComponents(DynamicStyle.java:217)
~[jorphan.jar:5.4]
at
org.apache.jorphan.gui.DynamicStyle.collectComponents(DynamicStyle.java:217)
~[jorphan.jar:5.4]
at
org.apache.jorphan.gui.DynamicStyle.updateComponentTreeUI(DynamicStyle.java:159)
~[jorphan.jar:5.4]
at org.apache.jorphan.gui.DynamicStyle.updateLaf(DynamicStyle.java:144)
~[jorphan.jar:5.4]
at org.apache.jorphan.gui.JFactory.refreshUI(JFactory.java:68)
~[jorphan.jar:5.4]
`

**To Reproduce**

Load a sample scenario with 1 HTTP Request, run it

**Screenshots**

 NA

**Additional Information:**
 - OS: Windows 7
 - OS Version: 7
- Darklaf Version: 2.4.10
- Java: Java 8

**Comment by weisJ** [comment]
This was fixed in version [2.5.3](https://github.com/weisJ/darklaf/releases/tag/v2.5.3-rc2) ([related commit](https://github.com/weisJ/darklaf/commit/f0bcd89a67b3efc048f64d394ad55e459021a204))
