### ISSUE TITLE
[Feature Request] different rendering of combobox whether or not they are active

### ISSUE THREAD

**Issue by akasolace** [weisJ/darklaf#223]
**General description**
I noticed a difference between darklaf and Nimbus regarding rendering of combobox and I think that darklf could mimick other laf default which are clearer

This suggestion is:
- [x] Visual
- [ ] Behavioral

**For visual suggestions**
Other LAF renders differently active and non-active combox wheras they are similar in darklaf. I believe the former approach is clearer.

**Nimbus**

![image](https://user-images.githubusercontent.com/1136496/101819480-9e43bc00-3b25-11eb-918b-b45d0f2cdca1.png)

**Darklaf**

![image](https://user-images.githubusercontent.com/1136496/101819530-aef43200-3b25-11eb-9900-905cdf5260bf.png)

**Comment by weisJ** [comment]
Darklaf does render disabled comboboxes in a different way. However it will always prioritise the colour of the current renderer if the colour isn't `null` or of type `UIResource`.

**Comment by akasolace** [comment]
Yes I realized my mistake afterward.

**Comment by weisJ** [comment]
That is what I figured. I just wanted to write an answer for anyone who might have the same problem and stumbles upon this issue :D.
