### ISSUE TITLE
Navigating menu with keyboard is broken

### ISSUE THREAD

**Issue by pmouawad** [weisJ/darklaf#227]
**Describe the bug**

On Windows 10
Download latest nightly build of JMeter
Open JMeter 
Use ALT + F to select File
Try navigating with Arrows (left, right, up, down) nothing happens.

Use another LAF, no problem.

**To Reproduce**
 
See above 
**Screenshots**

NA

**Additional Information:**
 - OS: Windows
 - OS Version: 10
 - Darklaf Version: 2.5.3

**Additional context**

I confirmed the bug myself.

See initial report:
https://bz.apache.org/bugzilla/show_bug.cgi?id=64993

**Comment by weisJ** [comment]
This was caused by me moving away from extending `BasicLookAndFeel`. It looks like some of the plaf code whecks whether the current laf is of type `BasicLookAndFeel`. This resulted in the manager responsible for keyboard navigation to be uninstalled.

**Comment by pmouawad** [comment]
Thanks for quick fix.
Could you release a new version of Darklaf so that we can release a JMeter 5.4.1 ?
Thanks

**Comment by weisJ** [comment]
Version `2.5.4` has been released.
