### ISSUE TITLE
It looks like click on a label for a checkbox is not dispatched in darklaf

### ISSUE THREAD

**Issue by vlsi** [weisJ/darklaf#24]
I have tried to apply darklaf to Apache JMeter, and below are some samples.
The issue I have is checkboxes and radioboxes can not be flipped by clicking on the relevant labels.

For instance, here's the code that creates radio buttons:
https://github.com/apache/jmeter/blob/b6d11d79d905d0c099732bb928d2372fd1388981/src/components/src/main/java/org/apache/jmeter/sampler/gui/TestActionGui.java#L210

With other LaFs (e.g. Darcula) I can click on labels like `Infinite`, `Continue`, `Stop Test`, and they alter the checkboxes.

PS. I can't build darklaf as it fails with `windows.h` not found (I use macOS)

Apache JMeter with bulenkov/darcula:
<img width="1264" alt="jmeter_darcula" src="https://user-images.githubusercontent.com/213894/74556774-d31bcc80-4f6f-11ea-8d03-448bdb4947c8.png">

Apache JMeter with weisJ/darflaf/darcula (it is strange the menu is not moved to Apple's menu):
<img width="1264" alt="darklaf_darcula" src="https://user-images.githubusercontent.com/213894/74556783-d911ad80-4f6f-11ea-85e1-a8ae43718411.png">

Apache JMeter with weisJ/darflaf/IntelliJ (just in case):
<img width="1264" alt="darklaf_intellij" src="https://user-images.githubusercontent.com/213894/74556966-2beb6500-4f70-11ea-9f48-9d79097954be.png">

**Comment by weisJ** [comment]
This should be fixed in ffc248f781184f19fb1e7c56e9cfa08037644192. I will upload a new version later this day or tomorrow.

**Comment by weisJ** [comment]
The menu bar not being in the OsX menu bar is indeed odd. Could you tell me the value of ````System.getProperty("apple.laf.useScreenMenuBar","false")```` on your machine?

**Comment by vlsi** [comment]
>Could you tell me the value of System.getProperty("apple.laf.useScreenMenuBar","false") on your machine?

It is set. As you see on the screenshots above it does work (see bulenkov/darcula where the menu is not present). I launch JMeter with exactly the same command, and the only difference is different themes.

Note: the application itself does not modify useScreenMenuBar property, and the property is passed during the startup: https://github.com/apache/jmeter/blob/cfb2bd92acf19123ae8a0de32ca60a46f5a85043/src/dist/build.gradle.kts#L520

**Comment by vlsi** [comment]
Ok. I was able to execute `./gradlew jar`, and I confirm checkboxes and radios work as expected now.

Thanks for the quick fix.

**Comment by weisJ** [comment]
I think I have solved what caused the menu to be misplaced. Could you try it out to confirm this? (ac9de657243d882715c9e3fef8972973f7e243cb)

Also labels should now have the correct disabled text colour applied to them (c23556c13fcc82bc3e36f58cf6b8d96e37e9cca4).

**Comment by weisJ** [comment]
In the screenshot the comment text area has the wrong background outside the border.
This is fixed with af25c7dd9466629820e33a86986fee51ada39dc6.

**Comment by vlsi** [comment]
@weisJ , that is interesting.
Frankly speaking, the border around textarea has workaround in JMeter.

By default Swing does not put the border around textarea, so JMeter adds its own border.

Will check shortly.
