### ISSUE TITLE
Darklaf JFileChooser List Mode glitches after first column

### ISSUE THREAD

**Issue by mengland80** [weisJ/darklaf#244]
**Describe the bug**
Opening a JFileChooser after LafManager.install() by default opens in list (as opposed to detail) mode. In this mode, on my Windows 10 machine, the first column of a directory listing displays normally (e.g., with folder icons for directories, etc.), but all the subsequent columns show the full absolute path of the file/directory with no icon, and the behavior is odd too (e.g., double clicking edits the name rather than navigating into a directory).

**To Reproduce**
```
public class MinimalDarklafTest {

  public static void main(String[] args) {
    LafManager.install(); //comment this statement out and the resulting file chooser works fine
    JFrame frame = new JFrame("JFileChooser Test");
    frame.setSize(400,400);
    JMenuBar menubar = new JMenuBar();
    JMenu file = new JMenu("File");
    Action open = new AbstractAction() {
      @Override
      public void actionPerformed(ActionEvent e) {
        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(frame);
      }
    };
    open.putValue(Action.NAME,"Open");
    file.add(open);
    menubar.add(file);
    frame.setJMenuBar(menubar);
    frame.setVisible(true);
    frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
  }
}
```

**Screenshots**
![image](https://user-images.githubusercontent.com/20937156/124823522-5233eb00-df3f-11eb-86ee-d29387a24db5.png)

**Additional Information:**
 - OS: Windows 10 Home
 - OS Version: 19041.1052
- Darklaf Version: 2.6.1

**Comment by weisJ** [comment]
Thank you for reporting. I have already noticed this and it was fixed in 40f6bac711aa6e05f67cdfee51ffaffaf0633032. The fix will be available with the next version.
