### ISSUE TITLE
Java 8 regression: Blocky application

### ISSUE THREAD

**Issue by ThexXTURBOXx** [weisJ/darklaf#256]
**Describe the bug**
Since DarkLaf 2.7.0, Java 16 works fine, but with Java 8 the application looks "blocky".

**To Reproduce**
Use DarkLaf 2.7.0 with Java 8. I am also using a 4K Monitor. I don't know if that could also cause issues.

**Screenshots**
![grafik](https://user-images.githubusercontent.com/12763829/127752195-1ed8cc5d-0a60-4642-a671-8a527b820d24.png)

**Additional Information:**
 - OS: Windows 10
 - OS Version: 21H1 19043.1151
- Darklaf Version: 2.7.0

**Comment by ThexXTURBOXx** [comment]
A comparison between Java 8 and Java 16. No code changes between the two pictures:
![grafik](https://user-images.githubusercontent.com/12763829/127752224-209a2e1d-f64e-4957-a326-e4ec7c394699.png)

**Comment by weisJ** [comment]
Can you confirm that this doesn't happen with darklaf `2.6.1`? Java 8 doesn't have any HiDpi support so issues with 4k screens are to be expected

**Comment by ThexXTURBOXx** [comment]
On `2.6.1`, there are also some issues, but they are much less appearent:
![grafik](https://user-images.githubusercontent.com/12763829/127752489-ddaac7b5-4d2f-47d7-8f2a-5c1c6ddb7a09.png)

**Comment by weisJ** [comment]
Please try the latest snasphot

**Comment by ThexXTURBOXx** [comment]
Thank you very much! The issue is much less appearent now. The only difference to `2.6.1` I can see now, is the `class/jar/...` text still being a little bit blocky. But tbh, that is just for convenience sake :)

![grafik](https://user-images.githubusercontent.com/12763829/127753407-9545c5ef-b505-46cb-ad75-665b26c3f775.png)

**Comment by weisJ** [comment]
How is the `class/jar/...` part painted. If manually I'd reckon it relied on antialiasing being set up somewhere, which doesn't happen now.

**Comment by ThexXTURBOXx** [comment]
Yes, it was drawn manually and I just needed to turn on antialiasing. Sorry for that!

In that case, the newest snapshot fixes this issue entirely and, thus, I will close it now. Thanks for the help and I am looking forward to the new release! :)
