### ISSUE TITLE
2.7.0/1 dependent on SNAPSHOT version

### ISSUE THREAD

**Issue by ThexXTURBOXx** [weisJ/darklaf#257]
**Describe the bug**

The new 2.7.0 and 2.7.1 releases are dependent on `swing-extensions-laf-support:0.1.3-SNAPSHOT` and `swing-extensions-visual-padding:0.1.3-SNAPSHOT` and I am unsure if this is correct.
I just noticed this because our CI/CD service reported that it can't find this dependency as it is not present in Maven Central, but only in the OSS Snapshot repository.
I am sorry to not have noticed that before

**Comment by weisJ** [comment]
Thank you for noticing! I have now put in a safe-guard such that this can't happen in the future. Version `2.7.2` now uses a stable version of the dependecies.
