### ISSUE TITLE
Add GitHub Actions CI (it supports Linux, Windows, and macOS)

### ISSUE THREAD

**Issue by vlsi** [weisJ/darklaf#26]

**Comment by weisJ** [comment]
I don't have that much experience when it comes to GitHub Actions as I was glad the current workflow works at all. Is the goal to also publish the artefacts using the actions?

**Comment by vlsi** [comment]
> Is the goal to also publish the artefacts using the actions?

The typical use case is to ensure code quality standards are met:
* code style matches expectations
* code compiles
* tests pass

It is especially useful for testing pull requests.

Actions can push SNAPSHOT versions as well, so everybody else can test how a new version of `darklaf` would look and feel.


Of course, Actions can be used to publish the artifacts, however, that is optional.
Pushing releases to Nexus (~Central) requires to sign artifacts, and it works best when the signing key never leaves the hardware you own and physically control. It basically means you should refrain from pushing the signing key to cloud servers.


Frankly speaking, I use https://github.com/vlsi/vlsi-release-plugins/blob/master/plugins/stage-vote-release-plugin/README.md for publishing my Gradle projects to Nexus (~Central).
It is a couple of commands (`prepare staging repository`, and `release it`), and it does not require git commits in between.

**Comment by vlsi** [comment]
Fixed in https://github.com/weisJ/darklaf/pull/27
