### ISSUE TITLE
How can I set systemProperty java.library.path in gradle.build file ?

### ISSUE THREAD

**Issue by poorvajappja** [weisJ/darklaf#263]
I am using groovy in build.gradle file.

I didn't know about setting systemProperty   `java.library.path`.

How can I set systemProperty java.library.path in gradle.build file ?

**Comment by weisJ** [comment]
Could you please clarify your question? Generally you can set system properties using `System.setProperty(String, String)` at runtime. Is there any specific error you are encountering with the `java.library.path` property while using darklaf?

**Comment by harideva16** [comment]
I have this error `java.lang.UnsatisfiedLinkError: no hello in java.library.path`.

I want to set system Property in build.gradle file. But , I didn't know about how to set system property in build.gradle file.

So , help me to set system properties in build.gradle file.

Can I set `java.library.path` like this ?

     runtime {
      //other configurations
      systemProperty "java.library.path", "path"

       }

**Comment by weisJ** [comment]
Are you trying to load a custom native library? For me this doesn’t look like an issue with darklaf itself. Why did you open this issue?

**Comment by poorvajappja** [comment]
@harideva16 this question was not asked by me.
