### ISSUE TITLE
native library didn't work after creating JPACKAGE. 

### ISSUE THREAD

**Issue by poorvajappja** [weisJ/darklaf#267]

**Comment by weisJ** [comment]
Please provide some further details. What exactly doesn’t work? If available provide a backtrack of occurring exceptions. What operating system are you using? What darklaf version are you using?
Please don’t ignore the issue templates. They are there for a reason, so I don’t have to ask all this questions.

**Comment by weisJ** [comment]
Closing because of lack of information. If you add the necessary information feel free to open the issue again and I'll have a look at it.
