### ISSUE TITLE
Translation error on the close button tooltip in spanish

### ISSUE THREAD

**Issue by Z3R0x24** [weisJ/darklaf#269]
The close button says "Cerca" instead of "Cerrar" in spanish, possibly because both words can be translated as "Close". 
![image](https://user-images.githubusercontent.com/86972958/131774665-8a3d1cb0-c1a8-47ea-89db-145387e1957a.png)

**Comment by weisJ** [comment]
Thank you for reporting this! I would appreciate if you could also look over the other spanish  translations (they are located [here](https://github.com/weisJ/darklaf/tree/master/core/src/main/resources/com/github/weisj/darklaf/task) in the files ending with `_es`) and create a PR (or report it here instead if you don’t want to create a PR)

**Comment by Z3R0x24** [comment]
I'll look into it. Also, I've noticed that the font size translation on the ThemeSettings panel overlaps.
![image](https://user-images.githubusercontent.com/86972958/131911933-eedd1f2c-c9de-45e4-8a26-869596b6ca4c.png)

**Comment by weisJ** [comment]
How it looks now:
![font_size](https://user-images.githubusercontent.com/31143295/132552441-024c6d40-6e98-415f-ac03-aa52b59a277a.png)

**Comment by Z3R0x24** [comment]
That looks nice! Thank you.
