### ISSUE TITLE
java.lang.IllegalAccessError JavaSE16

### ISSUE THREAD

**Issue by quantumcore** [weisJ/darklaf#271]
``Exception in thread "AWT-EventQueue-0" java.lang.IllegalAccessError: class com.github.weisj.darklaf.ui.label.DarkLabelUI`` on JavaSe16 but works fine on JavaSE15.

**Comment by weisJ** [comment]
Please use version `2.7.2` of the library.

**Comment by quantumcore** [comment]
Is it on Maven? Let me try.

**Comment by quantumcore** [comment]
Works. Thanks for quick response.
![cat](https://i.giphy.com/media/tBxyh2hbwMiqc/giphy.webp)

**Comment by quantumcore** [comment]
How do I contact you?
https://github.com/weisJ/darklaf#projects-using-darklaf
"Please send me your project, and I'll add it here."

**Comment by weisJ** [comment]
You can simply write it here :) I haven't gotten around to setup a contact email address 😅

**Comment by quantumcore** [comment]
Alright, I have an ambitious project. Would appreciate if you add it.
https://github.com/quantumcore/remote_hacker_probe

Thanks alot! Great work on this. :sweat_smile:

**Comment by weisJ** [comment]
Done
