### ISSUE TITLE
native library naming

### ISSUE THREAD

**Issue by harideva16** [weisJ/darklaf#273]
I have one doubt.

Java native interface (jni) allows calling native libraries

 1. Windows --> .dll,
 2. Linux --> .so and
 3. Mac -->.dylib.

I use the following code to load native library.

      static {
        System.loadLibrary("mypl");
        }

If I generate native library in windows os the native library's name comes `mypl.dll`

But , in Linux os the native library's name comes `libmypl.so` and in mac it comes `libmypl.dylib` 

Will this code ` System.loadLibrary("mypl");` load native library correcty after creating JPackage  in linux and mac ?

Help!!!

**Comment by weisJ** [comment]
What does this have to do with this project? Have you read the documentation of `System#loadLibrary`?

**Comment by harideva16** [comment]
But , there is information about it.

Link
 https://docs.oracle.com/javase/7/docs/api/java/lang/System.html#loadLibrary(java.lang.String)

**Comment by weisJ** [comment]
> What does this have to do with this project? Have you read the documentation of `System#loadLibrary`?

First question still stands.
