### ISSUE TITLE
What do you think of kotlin DSL for Gradle scripts?

### ISSUE THREAD

**Issue by vlsi** [weisJ/darklaf#28]

**Comment by weisJ** [comment]
I'm not against it. Is there an easy way to convert the current script to the kotlin version?

**Comment by vlsi** [comment]
Well. That is manual. I think I can help with that.

**Comment by vlsi** [comment]
I see you have `deployRepoUrl`. Do you really deploy to different repositories or do you deploy to Central only?

**Comment by weisJ** [comment]
I am only deploying to central.

**Comment by vlsi** [comment]
Fixed in https://github.com/weisJ/darklaf/pull/33
