### ISSUE TITLE
v3.0.0 - Missing words

### ISSUE THREAD

**Issue by Richard-Tang** [weisJ/darklaf#289]
**Describe the bug**
2.7.3 ---> normal
3.0.0 ---> missing words

**To Reproduce**
```java
import com.github.weisj.darklaf.LafManager;

import javax.swing.*;

public class Main {

    public static void main(String[] args) {
        LafManager.install();
        
        JFrame jFrame = new JFrame();
        jFrame.setSize(600, 600);
        jFrame.setVisible(true);

        JButton jButton = new JButton("123");
        JPanel  jPanel  = new JPanel();
        jFrame.add(jPanel);
        jPanel.add(jButton);

        jButton.addActionListener(e -> {
            JFileChooser jFileChooser = new JFileChooser();
            jFileChooser.showOpenDialog(null);
        });
    }
}
```

**Screenshots**
![image](https://user-images.githubusercontent.com/30547741/139269906-36a594ba-0da9-46c6-8dd5-41fb07947d6c.png)

![image](https://user-images.githubusercontent.com/30547741/139269530-250f1811-fa95-47c3-bb91-8112a28ece3b.png)

**Additional Information:**
 - OS: MacOS Big Sur
 - OS Version: 11.6
- Darklaf Version: 2.7.3 And 3.0.0
- JDK Version
```text
openjdk version "11.0.12" 2021-07-20
OpenJDK Runtime Environment JBR-11.0.12.7-1729.1-jcef (build 11.0.12+7-b1729.1)
OpenJDK 64-Bit Server VM JBR-11.0.12.7-1729.1-jcef (build 11.0.12+7-b1729.1, mixed mode)
```

**Additional context**
```xml
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>org.example</groupId>
    <artifactId>untitled</artifactId>
    <version>1.0-SNAPSHOT</version>

    <properties>
        <maven.compiler.source>11</maven.compiler.source>
        <maven.compiler.target>11</maven.compiler.target>
    </properties>

    <dependencies>
        <dependency>
            <groupId>com.github.weisj</groupId>
            <artifactId>darklaf-core</artifactId>
            <version>2.7.3</version>
        </dependency>
    </dependencies>

</project>
```

In addition, I would like to add another question, can the English letters "Open" "Cancel"  here be changed into other languages?

**Comment by weisJ** [comment]
Reopened because of https://github.com/weisJ/darklaf/issues/298#issuecomment-1007156412

**Comment by weisJ** [comment]
@Xujiayao I'm not quite able to reproduce the missing resources. Could you check for me using a debugger what values are contained in the `private Vector<String> resourceBundles` field of `UIManager.getLookAndFeelDefaults()` after installing the laf?

**Comment by Xujiayao** [comment]
> Could you check for me using a debugger what values are contained in the `private Vector<String> resourceBundles` field of `UIManager.getLookAndFeelDefaults()` after installing the laf?

Can you give a sample code and where should breakpoints be set for that? I tried but `resourceBundles` is always `null`. 🤔

**Comment by weisJ** [comment]
````java
SwingUtilities.invokeLater(() -> {
    LafManager.install(new IntelliJTheme());
    UIDefaults defaults = UIManager.getLookAndFeelDefaults();
});
````
Should do the trick. Then inspect `defaults.resourceBundles`.

**Comment by Xujiayao** [comment]
Like this?

![image](https://user-images.githubusercontent.com/58985541/148691529-55eefe39-3e0e-49a2-ac03-3da73a0d590e.png)

**Comment by weisJ** [comment]
Yes exactly thank you :)

**Comment by Xujiayao** [comment]
Ok. Thank you for your hard work! 👍

**Comment by weisJ** [comment]
Sorry I didn't get back to you sooner. This seems very wird to me. All necessey resource bundles are loaded and they do contain the missing strings. I'll have to do some more investigation to find out why this is happening. What jdk version/dsitribution do you use?

**Comment by Xujiayao** [comment]
JDK Version: (Oracle)
```
java version "17.0.1" 2021-10-19 LTS
Java(TM) SE Runtime Environment (build 17.0.1+12-LTS-39)
Java HotSpot(TM) 64-Bit Server VM (build 17.0.1+12-LTS-39, mixed mode, sharing)
```

I just re-tried inspect `defaults.resourceBundles`:

![image](https://user-images.githubusercontent.com/58985541/152337107-0b40186d-5a00-486c-bb31-22be27a4466b.png)

**Comment by weisJ** [comment]
I was able to reproduce the issue and fixed it with the latest snapshot.

**Comment by Xujiayao** [comment]
Just tested and it's fixed. This has helped me a lot in my modular project. Thank you so much!
