### ISSUE TITLE
Do you need pom.xml in the repository?

### ISSUE THREAD

**Issue by vlsi** [weisJ/darklaf#29]
Gradle can generate the full pom, so there's probably not much help from the file stored in the repository.

The current `pom.xml` duplicates the list of dependencies, so it might go off rails :-/

**Comment by weisJ** [comment]
I am copying the pom that is generated for the publishing process to make use of the github dependency analysis. If you have strong opinions against this the file can be removed.

**Comment by vlsi** [comment]
> to make use of the github dependency analysis

Oh, I did not think of such a use case.

The file is OK, and my main concern was if the file was used by the build itself it might produce unexpected results.
