### ISSUE TITLE
Wrong window height on macOS

### ISSUE THREAD

**Issue by hannesbraun** [weisJ/darklaf#292]
**Describe the bug**
When setting a window size, the height is not correct after calling `setVisible(true)`.

**To Reproduce**
Sadly, I'm not able to reproduce this issue with a small demo project. I've seen it occurring only with [our project](https://github.com/magmaOffenburg/RoboViz/tree/roboviz_kotlin). However, I found out the following:
- The issue does not occur when selecting `NimbusLookAndFeel`, so I assume it's related to this library. Correct me, if I'm wrong.
- The window height (measured including the title bar) is always reduced by 28 compared to the given size. This is the value returned by `JNIDecorationsMacOS.getTitleBarHeight` and also matches the height of the title bar on macOS. This means the actual window height is 372, when setting the size to 400.
- The size is changed during the call to `setVisible(true)` on the Frame.
- The y position of the window has the same offset as the window height. So the top of the window starts 28 pixels further down than expected for me.

**Additional Information:**
- OS: macOS
- OS Version: 12.1
- Darklaf Version: 2.7.3

**Additional context**
I think the issue originates somewhere in the release of version 2.0.3. The title bar was missing before that release as stated in the release notes. With version 2.0.3, the title bar appears together with the problem of the incorrect window height and position.

I hope my description helps at least to some extent. If you need more information, let me know.

Thanks in advance.

**Comment by weisJ** [comment]
If I understand your problem correctly you are experiencing the following:
````java
JFrame frame = ...
frame.setSize(new Dimension(400, 400));
frame.setVisible(true);
// Now frame.getSize().height < 400
````
If yes this sounds like the problem described in #230, when passing `null` as the parent of the dialog.
I managed to fix that particular issue, but it didn't yet make it into a release. Could you please try whether using the `3.0.0-SNAPSHOT` version fixes the problem:
````kotlin
repositories {
    maven {
        url = uri("https://oss.sonatype.org/content/repositories/snapshots/")
    }
}
dependencies {
    implementation("com.github.weisj:darklaf-core:3.0.0-SNAPSHOT")
}
````
Note that depending on what features you are using some code changes may be necessary.
See https://github.com/weisJ/darklaf/releases/tag/v3.0.0-SNAPSHOT for more information (if necessary).

**Comment by hannesbraun** [comment]
Hmm, I overlooked that issue completely. Sorry. However, this does not seem to fix the problem.

Luckily, I have now been able to reproduce the issue with a simple example:

```
import com.github.weisj.darklaf.LafManager;
import javax.swing.*;

public class App {

    public static void main(final String[] args) {
         SwingUtilities.invokeLater(() -> {
            LafManager.install();

            JFrame frame = new JFrame();
            frame.setSize(600, 400);

            frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
            frame.setVisible(true);
        });
    }
}
```

It seems like it's depending on the version of the JDK I'm using. At first, I tested this example with Adoptium `jdk-17+35` and the issue was not present. Then, I set the JAVA_HOME variable to the AdoptOpenJDK version `jdk8u232-b09` which I was using for my project and the issue appeared: the window height was wrong. After I switched back to `jdk-17+35`, the issue was gone.

Next, I wanted to try various other versions. The issue appeared with every other version too, that I've tested (current version of Adoption JDK 11, 16 and 17 as well as version 11 of the Zulu JDK). When I was switching back to `jdk-17+35`, the issue is still present. At this point, I'm not sure if this is something related to darflaf or the JDK. Or if I'm making just a very stupid mistake...

**Comment by weisJ** [comment]
Thank you for the clarification and the example. I guess there is some weird interplay between the JDK and darklaf, which I'll have to dig into.

On another note I would advise against specifically setting the size of a `JFrame` (or any other swing window). It really isn't a platform independent way to achieve correct sizes. If you need the content of the window to be of a specific size use
````java
JComponent content = ...
frame.setContentPane(content);
content.setPreferredSize(new DImension(600, 400));
frame.pack();
````
Of course I'm still going to try to fix this issue ;)

**Comment by weisJ** [comment]
I have published a snapshot version containing the latest changes. Please try whether they fix the problem.

**Comment by hannesbraun** [comment]
Thanks for the hint regarding `setPreferredSize`. Works like a charm.

I also tested both the project I saw the bug initially and the demo app with different versions of the JDK and it looks like the issue is gone with the latest snapshot version. Thank you very much :)
