### ISSUE TITLE
[Help] How to enable automatic switch to light/dark theme according to the OS

### ISSUE THREAD

**Issue by bric3** [weisJ/darklaf#310]
**General description**
So by playing with he API a bit I can toggle the themes programmatically.

        LafManager.setThemeProvider(new DefaultThemeProvider(new IntelliJTheme(), new DarculaTheme()));
        LafManager.enabledPreferenceChangeReporting(true);
        LafManager.installTheme(LafManager.getPreferredThemeStyle());

However I don't quite get how to make the LaF sync with the OS, either on startup or during runtime. I don't think I have missed something in the wiki, but surely I did.

Thanks in advance.

This suggestion is:
- [ ] Visual
- [ ] Behavioral
- [x] Documentation

**Comment by weisJ** [comment]
There is some delicacy involved when detecting the system them on macOS. The app bundle for the current program has to specify `NSRequiresAquaSystemAppearance=False` because otherwise macOS will always report the system to be running in light mode. Because all java programms running on the same JVM this isn't a value that can be reliably set by darklaf (though it is trying its best to do so). For this to work `LafManager.enabledPreferenceChangeReporting(true);` has to be the first call in the main method (one can also pass `false`, the call itself is relevant).

**Comment by bric3** [comment]
> The app bundle for the current program has to specify `NSRequiresAquaSystemAppearance=False`

Ha does that means this won't work if the app is started as a jar file ?

Do I need the _native_ dependencies, currently I am only declaring the `darklaf-core` that is advertised in the `README.md`.

**Comment by weisJ** [comment]
> > The app bundle for the current program has to specify `NSRequiresAquaSystemAppearance=False`
> 
> Ha does that means this won't work if the app is started as a jar file ?
> 

Not really. In this case the bundle of the jvm is used. If you call `LafManager.enabledPreferenceChangeReporting(true)` it should work as well (this may not work with some jvm versions. Though I don’t know why and what specific versions are affected.)

> Do I need the _native_ dependencies, currently I am only declaring the `darklaf-core` that is advertised in the `README.md`.

No extra dependencies are needed. `darklaf-core` already pulls in everything it needs.

**Comment by bric3** [comment]
Ah ok, I get why it didn't work. I was launching from gradle. Running from a regular `java -jar` command works.

> For this to work `LafManager.enabledPreferenceChangeReporting(true);` has to be the first call in the main method

I still needed this piece though for the program to pick up the them upon start-up.

However the UI don't update when the system theme changes.

Also I noticed this error (this machine runs Monterey 12.2), it happens on various occasions, like selecting text in a `JTextArea`.

<details><summary>Exception in thread "AppKit Thread" java.lang.NoSuchMethodError: accessibilityHitTest</summary>

```
2022-01-30 08:12:22.282 java[5053:1005898] Bad JNI lookup accessibilityHitTest
2022-01-30 08:12:22.286 java[5053:1005898] (
        0   libawt_lwawt.dylib                  0x0000000102d7b20d -[CommonComponentAccessibility accessibilityHitTest:] + 173
        1   libawt_lwawt.dylib                  0x0000000102d360a0 -[AWTView accessibilityHitTest:] + 176
        2   AppKit                              0x00007ff80efbc845 -[NSWindow(NSWindowAccessibility) accessibilityHitTest:] + 302
        3   AppKit                              0x00007ff80eb4fc4a -[NSApplication(NSApplicationAccessibility) accessibilityHitTest:] + 333
        4   AppKit                              0x00007ff80eb1f688 CopyElementAtPosition + 136
        5   HIServices                          0x00007ff81174f7f5 _AXXMIGCopyElementAtPosition + 388
        6   HIServices                          0x00007ff81177108c _XCopyElementAtPosition + 351
        7   HIServices                          0x00007ff81172ea69 mshMIGPerform + 182
        8   CoreFoundation                      0x00007ff80bcf10aa __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE1_PERFORM_FUNCTION__ + 41
        9   CoreFoundation                      0x00007ff80bcf0f86 __CFRunLoopDoSource1 + 619
        10  CoreFoundation                      0x00007ff80bcef5fb __CFRunLoopRun + 2397
        11  CoreFoundation                      0x00007ff80bcee5dd CFRunLoopRunSpecific + 563
        12  HIToolbox                           0x00007ff81492b4f1 RunCurrentEventLoopInMode + 292
        13  HIToolbox                           0x00007ff81492b118 ReceiveNextEventCommon + 284
        14  HIToolbox                           0x00007ff81492afe5 _BlockUntilNextEventMatchingListInModeWithFilter + 70
        15  AppKit                              0x00007ff80e71dd88 _DPSNextEvent + 886
        16  AppKit                              0x00007ff80e71c3f4 -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 1411
        17  libosxapp.dylib                     0x00000001021274aa -[NSApplicationAWT nextEventMatchingMask:untilDate:inMode:dequeue:] + 122
        18  AppKit                              0x00007ff80e70e919 -[NSApplication run] + 586
        19  libosxapp.dylib                     0x0000000102127275 +[NSApplicationAWT runAWTLoopWithApp:] + 165
        20  libawt_lwawt.dylib                  0x0000000102d9b140 +[AWTStarter starter:headless:] + 496
        21  libosxapp.dylib                     0x0000000102128f5f +[ThreadUtilities invokeBlockCopy:] + 15
        22  Foundation                          0x00007ff80cb76b03 __NSThreadPerformPerform + 179
        23  CoreFoundation                      0x00007ff80bcf08fd __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
        24  CoreFoundation                      0x00007ff80bcf0865 __CFRunLoopDoSource0 + 180
        25  CoreFoundation                      0x00007ff80bcf05e4 __CFRunLoopDoSources0 + 242
        26  CoreFoundation                      0x00007ff80bcef01b __CFRunLoopRun + 893
        27  CoreFoundation                      0x00007ff80bcee5dd CFRunLoopRunSpecific + 563
        28  libjli.dylib                        0x0000000101d17132 CreateExecutionEnvironment + 386
        29  libjli.dylib                        0x0000000101d12c96 JLI_Launch + 1366
        30  java                                0x0000000101beac0a main + 394
        31  dyld                                0x0000000107e264fe start + 462
)
Exception in thread "AppKit Thread" java.lang.NoSuchMethodError: accessibilityHitTest
```

</details>

**Comment by bric3** [comment]
So I tried this, but the synchronization doesn't happen

```java
LafManager.enabledPreferenceChangeReporting(true);
LafManager.setThemeProvider(new DefaultThemeProvider(new IntelliJTheme(), new DarculaTheme()));
LafManager.installTheme(LafManager.getPreferredThemeStyle());
LafManager.addThemePreferenceChangeListener(new ThemePreferenceListener() {
    @Override
    public void themePreferenceChanged(ThemePreferenceChangeEvent e) {
        System.out.println(">>>> theme preference changed = " + e.getPreferredThemeStyle());
        LafManager.setTheme(e.getPreferredThemeStyle());
        LafManager.updateLaf();
    }
});
```

When switching the OS from Light to Dark :

```
>>>> theme preference changed = PreferredThemeStyle{contrastRule=STANDARD, colorToneRule=LIGHT, accentColorRule=AccentColorRule{accentColor=java.awt.Color[r=0,g=122,b=255], selectionColor=java.awt.Color[r=179,g=215,b=255]}, fontSizeRule=FontSizeRule{type=NO_ADJUSTMENT}}
```

The right theme is picked upon startup though.

**Comment by weisJ** [comment]
Please try the following;

````java
LafManager.enabledPreferenceChangeReporting(true);
LafManager.setThemeProvider(new DefaultThemeProvider(new IntelliJTheme(), new DarculaTheme()));
LafManager.installTheme(LafManager.getPreferredThemeStyle());
LafManager.addThemePreferenceChangeListener(new ThemePreferenceListener() {
    @Override
    public void themePreferenceChanged(ThemePreferenceChangeEvent e) {
        SwingUtilities.invokeLater(() -> {
            System.out.println(">>>> theme preference changed = " + LafManager.getPreferredThemeStyle());
            LafManager.installTheme(LafManager.getPreferredThemeStyle());
        });
    }
});
````

**Comment by bric3** [comment]
It worked, just wrapping the code in `invokeLater` fixed the thing, I didn't have to pass the custom argument.

> _For others the argument parsing should be modified to ignore `-NSRequiresAquaSystemAppearance` and it's immediate value `False` (or `No`, or `0`) as it's in the program arguments now._

I was using `System.setProperty("apple.awt.application.appearance", "system");` which seems to work on Corretto 11.0.14.9.1. 

<details><summary>Corretto Java build</summary>

From what I've seen elsewhere it may depends against which os / sdk version the binary has been built.

```
$ otool -l ~/.asdf/installs/java/corretto-11.0.14.9.1/bin/java
...
Load command 9
      cmd LC_VERSION_MIN_MACOSX
  cmdsize 16
  version 10.9
      sdk 12.1
...
```

</details>

I think this should be added in the wiki or in the readme.


By the way, is it possible to use this system theme preference detection with other LaF out there ? Like `com.formdev:flatlaf`.

Thank you!

**Comment by bric3** [comment]
I noticed in the Javadoc that preference reporting has to be disabled.

> ```
>  * <p>
> * Warning: If preference reporting is enabled it <b>needs</b> to be disabled before closing the
> * program. Not doing so can result in memory leaks and prevent the classloader from being garbage
> * collected.
> ```

So to complete the code shouldn't I add :

```java
Runtime.getRuntime().addShutdownHook(new Thread(() -> 
    LafManager.enabledPreferenceChangeReporting(false)
));
```


> By the way, is it possible to use this system theme preference detection with other LaF out there ? Like `com.formdev:flatlaf`.

It turns out it's possible !

```java
LafManager.enabledPreferenceChangeReporting(true);
switch (LafManager.getPreferredThemeStyle().getColorToneRule()) {
    case DARK:
        FlatDarculaLaf.setup();
        break;
    case LIGHT:
        FlatIntelliJLaf.setup();
        break;
}
LafManager.addThemePreferenceChangeListener(new ThemePreferenceListener() {
    @Override
    public void themePreferenceChanged(ThemePreferenceChangeEvent e) {
        SwingUtilities.invokeLater(() -> {
            System.out.println(">>>> theme preference changed = " + LafManager.getPreferredThemeStyle());
            switch (LafManager.getPreferredThemeStyle().getColorToneRule()) {
                case DARK:
                    FlatDarculaLaf.setup();
                    break;
                case LIGHT:
                    FlatIntelliJLaf.setup();
                    break;
            }
            FlatLaf.updateUI();
        });
    }
});
```

Eventually I thought about using `ThemePreferencesHandler.getSharedInstance()` directly.

**Comment by weisJ** [comment]
> I noticed in the Javadoc that preference reporting has to be disabled.
> 
> > ...
> 
> So to complete the code shouldn't I add :
> 
> ```java
> Runtime.getRuntime().addShutdownHook(new Thread(() -> 
>     LafManager.enabledPreferenceChangeReporting(false)
> ));
> ```
>

Well this depends on whether you care about "memory leaks" happening during shutdown. This remark is meant for scenarios where you care about the classloader being able to be garbage collected e.g. in a plugin scenario. I should probably edit the comment to elaborate on this.

> > By the way, is it possible to use this system theme preference detection with other LaF out there ? Like `com.formdev:flatlaf`.
> ...
> Eventually I thought about using `ThemePreferencesHandler.getSharedInstance()` directly to avoid the cost of initializing `LafManager` class.

The `LafManager` class is rather light weight, so this really shouldn't be an issue. However you probably care about all the baggage the rest of the laf brings when you only want to make use of the system preference reporting. I have resturctured the project and published `com.github.weisj:darklaf-platform-preferences:3.0.0-SNAPSHOT` to the maven snapshot reporitory, which offers the preference reporting in a stripped down fashion (i.e. it only pulls in what is needed for the reporting to work and provides a minimal interface for it):

````kotlin
repositories {
    maven {
        url = uri("https://oss.sonatype.org/content/repositories/snapshots/")
    }
}

dependencies {
    implementation("com.github.weisj:darklaf-platform-preferences:latest.integration")
}
````
````java
SystemPreferencesManager manager = new SystemPreferencesManager();
manager.addListener(style -> System.out.println("Theme preference is now " + style));
manager.enableReporting(true);
````

**Comment by bric3** [comment]
Nice, I'll take a look!

**Comment by bric3** [comment]
Some heads up, it works just as well. Thank you !

**Comment by bric3** [comment]
I noticed this error which seems to come from this line : 

```
Runtime.getRuntime().addShutdownHook(new Thread(() -> manager.enableReporting(false)));
```

```
[04/02/2022, 12:00] [INFO] Stopped preference monitoring. [at com.github.weisj.darklaf.platform.macos.MacOSPreferenceMonitor]
Exception in thread "Thread-0" java.lang.RuntimeException: Non-Java exception raised, not handled! (Original problem: Cannot remove an observer <PreferenceChangeListener 0x600002d979a0> for the key path "effectiveAppearance" from <NSApplicationAWT 0x7fa7db90a020> because it is not registered as an observer.)
	at com.github.weisj.darklaf.platform.macos.JNIThemeInfoMacOS.deletePreferenceChangeListener(Native Method)
	at com.github.weisj.darklaf.platform.macos.MacOSPreferenceMonitor.stop(MacOSPreferenceMonitor.java:83)
	at com.github.weisj.darklaf.platform.macos.MacOSPreferenceMonitor.setRunning(MacOSPreferenceMonitor.java:91)
	at com.github.weisj.darklaf.platform.macos.MacOSThemePreferenceProvider.setReporting(MacOSThemePreferenceProvider.java:68)
	at com.github.weisj.darklaf.platform.preferences.SystemPreferencesManager.enableReporting(SystemPreferencesManager.java:87)
```

**Comment by weisJ** [comment]
Please run with `com.github.weisj.darklaf.util.LogUtil.setLevel(Level.INFO)` (You may need to depend on `com.github.weisj:darklaf-utils` to see the class). Is the reporting perhaps being already disabled beforehand? Another cause may be that at the point of shutdown hooks being executed the `NSApplicationAWT` has already removed all it's listeners.
Anyhow I don't actually think anymore that the shutdown hook is necessary anymore with the way it's currently implemented.

**Comment by weisJ** [comment]
> Some heads up, it works just as well. Thank you ! However the code needs to ask eagerly the actual _theme_, as the listener isn't invoked on startup.

I have published a new snapshot which initially calls all listeners when enabling reporting.

**Comment by weisJ** [comment]
Could you please also try version `com.github.weisj:darklaf-platform-preferences-jnf:latest.integration`. As it touches the native code I'd like to get confirmation that it doesn't break preference monitoring.

**Comment by bric3** [comment]
So about the latest snapshot  `com.github.weisj:darklaf-platform-preferences:latest.integration`

<table>
<thead>
  <tr>
    <th></th>
    <th><strong>corretto-17.0.2.8.1</strong></th>
    <th><strong>corretto-11.0.14.9.1</strong></th>
  </tr>
</thead>
<tbody>
  <tr>
    <td><strong>immediate explicit LaF init</strong></td>
    <td>

`accessibilityHitTest` stack trace when interacting with the UI.
    </td>
    <td>

no errors
    </td>
  </tr>
  <tr>
    <td><strong>listener only</strong></td>
    <td>

Mane, many more _no ComponentUI errors_, then crash on `JComboBox.setItem`
    </td>
    <td>

Few _no ComponentUI errors_, no `accessibility` stacktrace
    </td>
  </tr>
</tbody>
</table>

* **`accessibilityHitTest` stack trace**

```
2022-02-07 11:02:21.363 java[85156:3804876] Bad JNI lookup accessibilityHitTest
2022-02-07 11:02:21.369 java[85156:3804876] (
	0   libawt_lwawt.dylib                  0x000000010757b20d -[CommonComponentAccessibility accessibilityHitTest:] + 173
	1   libawt_lwawt.dylib                  0x00000001075360a0 -[AWTView accessibilityHitTest:] + 176
	2   AppKit                              0x00007ff804e12845 -[NSWindow(NSWindowAccessibility) accessibilityHitTest:] + 302
	3   AppKit                              0x00007ff8049a5c4a -[NSApplication(NSApplicationAccessibility) accessibilityHitTest:] + 333
	4   AppKit                              0x00007ff804975688 CopyElementAtPosition + 136
	5   HIServices                          0x00007ff8075a57f5 _AXXMIGCopyElementAtPosition + 388
	6   HIServices                          0x00007ff8075c708c _XCopyElementAtPosition + 351
	7   HIServices                          0x00007ff807584a69 mshMIGPerform + 182
	8   CoreFoundation                      0x00007ff801b470aa __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE1_PERFORM_FUNCTION__ + 41
	9   CoreFoundation                      0x00007ff801b46f86 __CFRunLoopDoSource1 + 619
	10  CoreFoundation                      0x00007ff801b455fb __CFRunLoopRun + 2397
	11  CoreFoundation                      0x00007ff801b445dd CFRunLoopRunSpecific + 563
	12  HIToolbox                           0x00007ff80a7814f1 RunCurrentEventLoopInMode + 292
	13  HIToolbox                           0x00007ff80a781118 ReceiveNextEventCommon + 284
	14  HIToolbox                           0x00007ff80a780fe5 _BlockUntilNextEventMatchingListInModeWithFilter + 70
	15  AppKit                              0x00007ff804573d88 _DPSNextEvent + 886
	16  AppKit                              0x00007ff8045723f4 -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 1411
	17  libosxapp.dylib                     0x00000001069314aa -[NSApplicationAWT nextEventMatchingMask:untilDate:inMode:dequeue:] + 122
	18  AppKit                              0x00007ff804564919 -[NSApplication run] + 586
	19  libosxapp.dylib                     0x0000000106931275 +[NSApplicationAWT runAWTLoopWithApp:] + 165
	20  libawt_lwawt.dylib                  0x000000010759b140 +[AWTStarter starter:headless:] + 496
	21  libosxapp.dylib                     0x0000000106932f5f +[ThreadUtilities invokeBlockCopy:] + 15
	22  Foundation                          0x00007ff8029ccb03 __NSThreadPerformPerform + 179
	23  CoreFoundation                      0x00007ff801b468fd __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
	24  CoreFoundation                      0x00007ff801b46865 __CFRunLoopDoSource0 + 180
	25  CoreFoundation                      0x00007ff801b465e4 __CFRunLoopDoSources0 + 242
	26  CoreFoundation                      0x00007ff801b4501b __CFRunLoopRun + 893
	27  CoreFoundation                      0x00007ff801b445dd CFRunLoopRunSpecific + 563
	28  libjli.dylib                        0x0000000106554132 CreateExecutionEnvironment + 386
	29  libjli.dylib                        0x000000010654fc96 JLI_Launch + 1366
	30  java                                0x0000000106427c0a main + 394
	31  dyld                                0x000000010bcb44fe start + 462
)
Exception in thread "AppKit Thread" java.lang.NoSuchMethodError: accessibilityHitTest
```

* **no ComponentUI errors for `JTextField`, `JPanel`, etc.**
```
java.lang.Error: no ComponentUI class for: javax.swing.JTextField[,0,0,0x0,invalid,alignmentX=0.0,alignmentY=0.0,border=,flags=0,maximumSize=,minimumSize=,preferredSize=,caretColor=,disabledTextColor=,editable=true,margin=,selectedTextColor=,selectionColor=,columns=0,columnWidth=0,command=,horizontalAlignment=CENTER]
	at java.desktop/javax.swing.UIDefaults.getUIError(UIDefaults.java:760)
	at java.desktop/javax.swing.MultiUIDefaults.getUIError(MultiUIDefaults.java:133)
	at java.desktop/javax.swing.UIDefaults.getUI(UIDefaults.java:790)
	at java.desktop/javax.swing.UIManager.getUI(UIManager.java:1066)
	at java.desktop/javax.swing.text.JTextComponent.updateUI(JTextComponent.java:352)
	at java.desktop/javax.swing.text.JTextComponent.<init>(JTextComponent.java:326)
	at java.desktop/javax.swing.JTextField.<init>(JTextField.java:230)
	at java.desktop/javax.swing.JTextField.<init>(JTextField.java:182)
```

* **Crash on `JComboBox.setItem` because `JComboBox.getEditor()` is null**
```
Exception in thread "main" java.lang.NullPointerException: Cannot invoke "javax.swing.ComboBoxEditor.setItem(Object)" because the return value of "javax.swing.JComboBox.getEditor()" is null
	at java.desktop/javax.swing.JComboBox.setSelectedItem(JComboBox.java:603)
	at com.github.bric3.fireplace.FlameGraphTab.<init>(FlameGraphTab.java:62)
	at com.github.bric3.fireplace.FirePlaceMain.main(FirePlaceMain.java:124)
```

**Comment by bric3** [comment]
So about the latest snapshot  `com.github.weisj:darklaf-platform-preferences-jnf:latest.integration` (the timestamp is `20220206170328`)

I don't know yet the differences between the JNF variant, the OS them detection worked well.
There's a slight improvement highlighted in bold on JDK 17, when the code has explicit LaF initialization after setting up the listeners : in short the `accessibilityHitTest` stacktrace is gone.

----


In the following table I identified a few issues when adding the explicit theme configuration (as I wrote in this https://github.com/weisJ/darklaf/issues/310#issuecomment-1029852060) or just setting up the listeners (ie without the switch block)

<table>
<thead>
  <tr>
    <th></th>
    <th><strong>corretto-17.0.2.8.1</strong></th>
    <th><strong>corretto-11.0.14.9.1</strong></th>
  </tr>
</thead>
<tbody>
  <tr>
    <td><strong>immediate explicit LaF init</strong></td>
    <td>

<strong>no errors</strong>
    </td>
    <td>

no errors
    </td>
  </tr>
  <tr>
    <td><strong>listener only</strong></td>
    <td>

Mane, many more _no ComponentUI errors_, then crash on `JComboBox.setItem`
    </td>
    <td>

Few _no ComponentUI errors_, no `accessibility` stacktrace
    </td>
  </tr>
</tbody>
</table>


* **no ComponentUI errors for `JTextField`, `JPanel`, etc.**
```
java.lang.Error: no ComponentUI class for: javax.swing.JTextField[,0,0,0x0,invalid,alignmentX=0.0,alignmentY=0.0,border=,flags=0,maximumSize=,minimumSize=,preferredSize=,caretColor=,disabledTextColor=,editable=true,margin=,selectedTextColor=,selectionColor=,columns=0,columnWidth=0,command=,horizontalAlignment=CENTER]
	at java.desktop/javax.swing.UIDefaults.getUIError(UIDefaults.java:760)
	at java.desktop/javax.swing.MultiUIDefaults.getUIError(MultiUIDefaults.java:133)
	at java.desktop/javax.swing.UIDefaults.getUI(UIDefaults.java:790)
	at java.desktop/javax.swing.UIManager.getUI(UIManager.java:1066)
	at java.desktop/javax.swing.text.JTextComponent.updateUI(JTextComponent.java:352)
	at java.desktop/javax.swing.text.JTextComponent.<init>(JTextComponent.java:326)
	at java.desktop/javax.swing.JTextField.<init>(JTextField.java:230)
	at java.desktop/javax.swing.JTextField.<init>(JTextField.java:182)
```

* **Crash on `JComboBox.setItem` because `JComboBox.getEditor()` is null**
```
Exception in thread "main" java.lang.NullPointerException: Cannot invoke "javax.swing.ComboBoxEditor.setItem(Object)" because the return value of "javax.swing.JComboBox.getEditor()" is null
	at java.desktop/javax.swing.JComboBox.setSelectedItem(JComboBox.java:603)
	at com.github.bric3.fireplace.FlameGraphTab.<init>(FlameGraphTab.java:62)
	at com.github.bric3.fireplace.FirePlaceMain.main(FirePlaceMain.java:124)
```

**Comment by weisJ** [comment]
I’m a bit confused do you mean that the following produces the error?
````java
SystemPreferencesManager manager = new SystemPreferencesManager();
manager.addListener(style ->{});
manager.enableReporting(true);
````

**Comment by bric3** [comment]
Yes, on my application code base this code snippet produces `java.lang.Error: no ComponentUI class for...`

**Comment by weisJ** [comment]
So to recapitulate:

This doesn't throw:
````java
SystemPreferencesManager manager = new SystemPreferencesManager();
manager.addListener(style ->System.out.println("Hello"));
manager.enableReporting(true);
````

But this does?
````java
SystemPreferencesManager manager = new SystemPreferencesManager();
manager.addListener(style -> SwingUtilities.invokeLater(() -> System.out.println("Hello 2"));
manager.enableReporting(true);
````

**Comment by bric3** [comment]
Yes! 
But the action in the is not a simple `println`, the action sets up / install the LaF, so there must be a concurrency error.

**Comment by weisJ** [comment]
Can you post an example (including the code for the UI itself)? Also please try to install the system look and feel instead of any third party LaF to ensure it isn’t caused by that.

**Comment by bric3** [comment]
Hello, yes, here's a very simple Gradle project that reproduce the issue.

Just run `./gradlew run`

[dpr.zip](https://github.com/weisJ/darklaf/files/8053863/dpr.zip)

In `darklaf.pref.reproducer.App` there is some commented code, when this code is commented the `no ComponentUI` error happens. When the code is uncommented, the UI works fine.

**Comment by bric3** [comment]
I made the following replacement, but this had the same issue. 

```diff
                    case LIGHT:
-                       FlatIntelliJLaf.setup();
+                       try {
+                           UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
+                       } catch (Exception e) { }
                        break;
```

**Comment by weisJ** [comment]
You are running into the following problem:
````java
ystemPreferencesManager manager = new SystemPreferencesManager();
manager.addListener(style -> {
    SwingUtilities.invokeLater(() -> {
        //Laf is installed here
        ...
    });
});
manager.enableReporting(true); // This invokes the listener once.

// (*)

// At this point on the swing ui thread (which is different from the main thread
// the laf installation code runs. While it is being installed calls tu UIManager.getUI(...) will fail, as
// the Laf defaults providing the appropriate values don't exist yet.
var label = new JLabel(); // Exception is thrown
````
Installing the laf at `(*)` only makes it more difficult for the error to appear, but not impossible.


I would recommend the following: 
- Don't wrap the laf installation code in the listener with `SwingUtilities#invokeLater`. This won't be necessary as I have updated the reporting to ensure the correct value gets passed. As long as you follow the next item you can leave it in until the new version is published.
- Always initialize/modify ui on the swing thread i.e. using `SwingUtilities#invokeLater`.

**Comment by bric3** [comment]
Thank you! Indeed I started to craft some hooks in the `RepaintManager` that told me similar things, ie don't initialize components outside the main awt thread, even if they are not _realized_ yet.

And yes about the unwrapping of `invokeLater`.

Thank you very, very much for three help!
