### ISSUE TITLE
JScrollBar / JScrollPane search highlighting

### ISSUE THREAD

**Issue by GraxCode** [weisJ/darklaf#315]
A neat feature would be to have highlighting of rows with a specifiable color in scroll bars on JTextAreas (especially with RSyntaxTextArea would be very interesting!)

![image](https://user-images.githubusercontent.com/24767548/159311260-f14bd090-bbdb-4d5d-894c-382ea3ab88ad.png)

**Comment by weisJ** [comment]
This shouldn't be too difficult to get working :). I'll give it a shot

**Comment by weisJ** [comment]
With the latest snapshot you should be able to provide a custom "background painter" for scrollbars to paint behind the track and thumb. See https://github.com/weisJ/darklaf/blob/d7d08139ab6d56a11d0c9a3c61ed73e0d1564510/core/src/test/java/com/github/weisj/darklaf/ui/scrollPane/OverlayRSyntaxScrollPane.java
for a possible way to implement markers this way.

**Comment by GraxCode** [comment]
Thank you.
