### ISSUE TITLE
Custom title bar on macOS

### ISSUE THREAD

**Issue by weisJ** [weisJ/darklaf#32]
This relates to #2 .

Provide a custom title bar on macOS. After doing some research, this could be done by setting
the properties 
[````fullsizecontentview````](https://developer.apple.com/documentation/appkit/nswindow/stylemask/1644646-fullsizecontentview) and [````]titlebarappearstransparent````](https://developer.apple.com/documentation/appkit/nswindow/1419167-titlebarappearstransparent) of the underlying NSWindow. (see [https://stackoverflow.com/questions/54353576/colorizing-the-titlebar-in-macos-with-multiple-colors](https://stackoverflow.com/questions/54353576/colorizing-the-titlebar-in-macos-with-multiple-colors)).

Communication with java would happen as in the windows version through JNI passing the request to a C++ function which in turn calls the objective-c code, that is able to set those properties.

If working the LaF should add a custom title bar (without window buttons, as those should still be present).

As I don't have access to macOS platform I can't do this myself, so help would be highly appreciated.

**Comment by vlsi** [comment]
Is it different from `Frame#setUndecorated(true)` ?

<img width="803" alt="Снимок экрана 2020-02-20 в 1 00 30" src="https://user-images.githubusercontent.com/213894/74880540-7c9dfc00-537c-11ea-99bc-36f317dd78df.png">

**Comment by weisJ** [comment]
Yes this keeps the window buttons and title text.

**Comment by vlsi** [comment]
https://bugs.openjdk.java.net/browse/JDK-8212549  which indeed works in Java 13.

```java
JFrame frame = new JFrame();
final JRootPane rootPane = frame.getRootPane();
rootPane.putClientProperty("apple.awt.fullWindowContent", true);
rootPane.putClientProperty("apple.awt.transparentTitleBar", true);
```

<img width="619" alt="Снимок экрана 2020-02-20 в 2 00 59" src="https://user-images.githubusercontent.com/213894/74884720-e1f5eb00-5384-11ea-8b8b-427bdc2d90bf.png">

**Comment by weisJ** [comment]
Great. At least for java version >= 12 this is a solution. Does moving the window work?

**Comment by vlsi** [comment]
What do you think of `setAccessible(true)`-driven `sun.lwawt.macosx.CPlatformWindow#setStyleBits(int mask, boolean value)` for pre Java 12?

**Comment by weisJ** [comment]
Theoretically a good approach. The instance of the underlying `CPlatformWindow` can be optained as follows:
````java
WindowPeer peer = (WindowPeer)window.getPeer();
CPlatformWindow platformWindow = (CPlatformWindow)((LWWindowPeer)peer).getPlatformWindow();
````
Neither `CPlatformWindw` nor `LWWindowPeer` are visible (or included) in non macOS jdk version.
All of this would need to happen through reflection.

**Comment by weisJ** [comment]
@vlsi could you tell me if #54 works for your? At least for the part of actually calling `setStyleBits` on `CPlatformWindow`.
