### ISSUE TITLE
Maximize and Restore not working in 3.0.0

### ISSUE THREAD

**Issue by josh-r-dick** [weisJ/darklaf#322]
When you click on the Maximize and Restore buttons some other version of the button appears to the right instead of performing the maximize or restore actions. 

Maximize and Restore work if you double click the title bar, however restoring always restores to the top left corner of the screen, not the last location.

![image](https://user-images.githubusercontent.com/4989713/170740391-59618deb-5ae8-4bb5-b605-07f9cd1196c3.png)

![image](https://user-images.githubusercontent.com/4989713/170740459-c084e993-c930-4109-9cf9-f54da27e60bd.png)

This issue did not exist in 2.7.3.

This was found on Windows 10 version 1809 build 17763.652

**Comment by weisJ** [comment]
Please try whether the latest snapshot fixes the issue for you :)

**Comment by josh-r-dick** [comment]
Works on 3.0.1-SNAPSHOT. Thanks!

**Comment by MarceloLaser** [comment]
Any news on when this will be available through maven? I'd prefer not to add a local dependency if it can be avoided. :)

**Comment by weisJ** [comment]
Sorry for the delay. I currently don’t find as much time as I’d like for my projects. I’ll try to release the next version this weekend. Thank you for your patience.

**Comment by weisJ** [comment]
Version 3.0.1 has been released.
