### ISSUE TITLE
Wiki Demo links not working.

### ISSUE THREAD

**Issue by nightm4re94** [weisJ/darklaf#324]
**Describe the bug**
In the Wiki, whenever a Demo snippet is linked, the link points to a non-existing location.
For example:
> Demo: [TriCheckBoxDemo](https://github.com/weisJ/darklaf/blob/master/core/src/test/java/ui/checkBox/TriCheckBoxDemo.java) 
(`https://github.com/weisJ/darklaf/blob/master/core/src/test/java/ui/checkBox/TriCheckBoxDemo.java`)

should be 
> Demo: [TriCheckBoxDemo](https://github.com/weisJ/darklaf/blob/master/core/src/test/java/com/github/weisj/darklaf/ui/checkBox/TriCheckBoxDemo.java)
(`https://github.com/weisJ/darklaf/blob/master/core/src/test/java/com/github/weisj/darklaf/ui/checkBox/TriCheckBoxDemo.java`)

**Comment by weisJ** [comment]
Should be fixed now. If you find another links thats broken let me know :)
