### ISSUE TITLE
JTree has some renderer bug

### ISSUE THREAD

**Issue by tyro668** [weisJ/darklaf#333]
**Describe the bug**
When used jtree component and set root invisible:
```
jtree.setRootVisibile(false)
```
add at last eight node， the first node and last node has child node，then toggle the last node，we can see some renderer not complete

**Additional Information:**
 - OS: [e.g. macOS]
 - OS Version: [e.g. 11.14]
   - For issues with frame decorations on Windows please provide the explicit [Windows build number](https://docs.microsoft.com/en-gb/windows/release-information/).
- Darklaf Version: [e.g. 3.0.2]
  - **Note**: If you are using the `latest.integration` version please try to replicate the issue with the latest stable release.

**Comment by weisJ** [comment]
Please provide a simple standalone example which demonstrates the issue you are describing.

**Comment by tyro668** [comment]
> Please provide a simple standalone example which demonstrates the issue you are describing.
hello @weisJ ,this is a simple demo code, when open the window and trigger node8,the bug will become!
`
import com.github.weisj.darklaf.LafManager;
import com.github.weisj.darklaf.theme.IntelliJTheme;

import javax.swing.*;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeCellRenderer;
import javax.swing.tree.DefaultTreeModel;
import java.awt.*;

/**
 * @author richie
 * Created by richie on 2023/5/17
 */
public class JTreeDemo {

    public static void main(String... args) {
        LafManager.installTheme(new IntelliJTheme());
        JFrame frame = new JFrame();
        JPanel contentPane = (JPanel) frame.getContentPane();
        contentPane.setLayout(new BorderLayout());

        JTreePane treePane = new JTreePane();
        contentPane.add(treePane, BorderLayout.CENTER);

        frame.setSize(800, 600);
        frame.setVisible(true);
    }

    /**
     * @author richie
     * Created by richie on 2023/5/17
     */
    public static class JTreePane extends JPanel {

        private final DefaultMutableTreeNode root = new DefaultMutableTreeNode();
        private final DefaultTreeModel model = new DefaultTreeModel(root);
        private final JTree jTree = new JTree(model);

        public JTreePane() {
            setLayout(new BorderLayout());
            jTree.setCellRenderer(new DatasourceTreeCellRenderer());
            jTree.setRootVisible(false);

            JScrollPane leftScrollPane = new JScrollPane(jTree);

            add(leftScrollPane, BorderLayout.CENTER);

            DefaultMutableTreeNode node1 = new DefaultMutableTreeNode(new NodeObject("node1"));
            node1.add(new DefaultMutableTreeNode( new NodeObject("node1-1")));
            root.add(node1);
            DefaultMutableTreeNode node2 = new DefaultMutableTreeNode(new NodeObject("node2"));
            root.add(node2);
            DefaultMutableTreeNode node3 = new DefaultMutableTreeNode(new NodeObject("node3"));
            root.add(node3);
            DefaultMutableTreeNode node4 = new DefaultMutableTreeNode(new NodeObject("node4"));
            root.add(node4);
            DefaultMutableTreeNode node5 = new DefaultMutableTreeNode(new NodeObject("node5"));
            root.add(node5);
            DefaultMutableTreeNode node6 = new DefaultMutableTreeNode(new NodeObject("node6"));
            root.add(node6);
            DefaultMutableTreeNode node7 = new DefaultMutableTreeNode(new NodeObject("node7"));
            root.add(node7);
            DefaultMutableTreeNode node8 = new DefaultMutableTreeNode(new NodeObject("node8"));
            node8.add(new DefaultMutableTreeNode( new NodeObject("node8-1")));
            root.add(node8);

            model.reload(root);
        }
    }

    /**
     * @author richie
     * Created by richie on 2023/5/17
     */
    public interface Nameable extends Cloneable {

        String getName();

        void setName(String name);
    }

    /**
     * @author richie
     * Created by richie on 2023/5/17
     */
    public static class NodeObject implements Nameable {

        private String name;

        public NodeObject(String name) {
            this.name = name;
        }

        @Override
        public String getName() {
            return name;
        }

        @Override
        public void setName(String name) {
            this.name = name;
        }
    }

    /**
     * @author richie
     * Created by richie on 2023/5/17
     */
    public static class DatasourceTreeCellRenderer extends DefaultTreeCellRenderer {

        public DatasourceTreeCellRenderer() {

        }

        @Override
        public Component getTreeCellRendererComponent(JTree tree, Object value, boolean sel, boolean expanded, boolean leaf, int row, boolean hasFocus) {
            super.getTreeCellRendererComponent(tree, value, sel, expanded, leaf, row, hasFocus);
            DefaultMutableTreeNode node = (DefaultMutableTreeNode) value;
            Object userObject = node.getUserObject();
            if (userObject instanceof Nameable) {
                this.setText(((Nameable) userObject).getName());
            }
            return this;
        }
    }
}
`

**Comment by weisJ** [comment]
I can't reproduce this with the latest snapshot hence will assume it is fixed. I'll release the new version in the next few days. If the issue still happens for you feel free to reopen the issue.
