### ISSUE TITLE
Event registered on EditorComponent for JComboBox will be cleared when new theme applied.

### ISSUE THREAD

**Issue by Gegenbauer** [weisJ/darklaf#334]
With a new theme applied, the DarkComboBoxUI will create an new editor accomponied with new editorComponent, so event listeners on previous editorComponent will not work. Is there any recommanded practice to solve this problem? Or will it be fixed as an bug?

**Comment by weisJ** [comment]
What listeners exactly are you installing?

**Comment by Gegenbauer** [comment]
All listeners will not work after ui changed, because the editorComponent you interact with was a new instance.

For example, add focus listener on it

JComboBox<String> combo = new JComboBox<>();

FocusListener listener = new FocusAdapter() {
    //override to do something
};
combo.getEditor().getEditorComponent().addFocusListener(listener)

And after new theme applied, the focusListener will not work. I added new listener after theme changed as a work around, but it's not elegant.

**Comment by weisJ** [comment]
Applying existing listeners to the new component cannot be done easily as there are also several other listeners installed by swing itself, which cannot be discerned from user provided listeners. I see two possible options here:
- If you don't want the component to change provide your own `ComboBoxEditor`, which doesn't implement `UIResource`, which results in it being reinstalled after the laf changes. Any objects which are `UIResource`s are allowed to be pulled away from you by the LaF at any point. Don't depend on them to preserve any state between LaF changes.
Though I recommend the following:
- Any visual related listeners should be installed in `JComponent#updateUI` and be contained in a custom class. This ensures that they are installed after the LaF changes.
