### ISSUE TITLE
[Help]JButton Background

### ISSUE THREAD

**Issue by pizzadox9999** [weisJ/darklaf#356]
Hi, i am sorry that is not really a bug. But I am not able to set the background color of a JButton with the client property: KEY_VARIANT VARIANT_BORDERLESS. I Tried setbackground Methode and the ui manager but both Seen unable to make said change. I would appreacite a way to change the background of a button. I have to admit I have changed the arc of the button to 25 in an initTask. Despite this I can still change the foreground. 

Best regards
pizzadox9999

**Comment by weisJ** [comment]
Try the `KEY_CLICK_COLOR` and `KEY_HOVER_COLOR` client properties.

**Comment by pizzadox9999** [comment]
Hi, thank you very much. It helped alot. pizzadox9999
