### ISSUE TITLE
[Help/Question]

### ISSUE THREAD

**Issue by pizzadox9999** [weisJ/darklaf#357]
Hi, is there an easy way for me to create proper styling for swingx JXTextField? I looked a bit into it and it seems, that the internally used PromptSupport messes around with darklaf quiet a bit, so that a proper display isn't possible. Does somebody know a solution for this?
Best regards pizzadox9999

example of it top is the JXTextField with a prompt underneath you can see a JPasswordField with icon enabled
![image](https://github.com/user-attachments/assets/d6ad448e-bd99-4482-b0de-55db8fc8fb87)

**Comment by weisJ** [comment]
I don’t know whether there is an easy way to fix this. As I also don’t have a lot of time on my hand to work on this project at the moment, so this won’t be fixed in the foreseeable future.

**Comment by pizzadox9999** [comment]
Hi, thank you for the response. Maybe there will be a solution in the future. When I figure something out I will let you know it.
So long pizzadox9999
