### ISSUE TITLE
Combobox seems to occupy too much space compared to other controls

### ISSUE THREAD

**Issue by vlsi** [weisJ/darklaf#38]
The button is large :(
It looks like it is worth reducing insets in `com.github.weisj.darklaf.ui.combobox.DarkComboBoxUI#getInsets`

<img width="532" alt="combobox" src="https://user-images.githubusercontent.com/213894/74614608-45d0a780-512a-11ea-8529-874bb517f926.png">

It looks like the drop-down icon has the same color as the background, so the control is hard to distinguish from an edit field.

<img width="532" alt="combobox_noneditable" src="https://user-images.githubusercontent.com/213894/74614611-4a955b80-512a-11ea-9aea-6d38e4a0cf3c.png">

When combo is open, the rows are much thinner than the combo itself.

<img width="121" alt="combobox_open" src="https://user-images.githubusercontent.com/213894/74614612-4d904c00-512a-11ea-9e75-5d1e0776e84a.png">

**Comment by weisJ** [comment]
Absolutely. I have made the insets smaller (4a3041ace8cd938c27470d53cc7151aa5534d078). Also the button area isn't that big anymore and it should use the correct icon.

**Comment by vlsi** [comment]
Oh, that is way better now

<img width="543" alt="jmeter_combo" src="https://user-images.githubusercontent.com/213894/74629011-3cfec680-5168-11ea-982e-c875463ff239.png">

Just one more thing: the border for combo looks rounded while other fields look rectangular.

WDYT?

**Comment by weisJ** [comment]
TextFields have a rectangular border to fall more in place with other text components. But I do understand, that they probably should look more in line with combo box and spinner. Will change to use the same arc length.

**Comment by weisJ** [comment]
@vlsi Which border is used for the title border in your example? The colours and thickness looks a bit off and it would be nice to know if I can do something about that.
