### ISSUE TITLE
Button text gets truncated in focused mode because of bold font

### ISSUE THREAD

**Issue by vlsi** [weisJ/darklaf#41]
Sample: https://recordit.co/2JXoSkG7zg

<img src="http://g.recordit.co/2JXoSkG7zg.gif">

**Comment by weisJ** [comment]
Could you check if the latest commit fixed this?

Though I am not sure about the use of making the button a default button for the means of focus painting.

**Comment by vlsi** [comment]
The current master does not seem to fix this.

<img width="719" alt="jmeter_save" src="https://user-images.githubusercontent.com/213894/74641994-45b0c600-5183-11ea-8be3-784763e85b69.png">

The code is as follows:

```
JOptionPane.showConfirmDialog(guiPackage.getMainFrame(), JMeterUtils
        .getResString("cancel_exit_to_save"), // $NON-NLS-1$
        JMeterUtils.getResString("save?"), // $NON-NLS-1$
        JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE);
``

**Comment by vlsi** [comment]
> I am not sure about the use of making the button a default button for the means of focus painting.

I guess I do not follow this :-/

**Comment by weisJ** [comment]
Strange. I'm not able to reproduce this. But I think I know what caused this. Could you please try again? 

>I guess I do not follow this :-/

I just think it is a bit strange to turn a button into a default button to use it for focus highlighting.

**Comment by vlsi** [comment]
>I just think it is a bit strange to turn a button into a default button to use it for focus highlighting.

I do not think JMeter turns buttons into default buttons :-/

**Comment by weisJ** [comment]
> I do not think JMeter turns buttons into default buttons :-/

Could you run the button demo and tell me if the focused button appears blue with bold font?

**Comment by vlsi** [comment]
Non-default button indeed appears in blue when focused:

focus_non_default
<img width="554" alt="focus_non_default" src="https://user-images.githubusercontent.com/213894/74653336-01c8bb80-5199-11ea-831a-eccd6ce3a7b8.png">

nofocus_non_default
<img width="554" alt="nofocus_non_default" src="https://user-images.githubusercontent.com/213894/74653344-08efc980-5199-11ea-8ca8-9f86d735a717.png">

nofocus_default
<img width="554" alt="nofocus_default" src="https://user-images.githubusercontent.com/213894/74653350-0db47d80-5199-11ea-8b9c-9b483c55c0b2.png">

focus_default
<img width="554" alt="focus_default" src="https://user-images.githubusercontent.com/213894/74653361-1016d780-5199-11ea-94a4-6f3310896e16.png">

**Comment by weisJ** [comment]
Super weird. Can you tell me what ````button.isDefaultButton()```` returns in each of these cases?

**Comment by vlsi** [comment]
```java
        JButton button = new JButton("Test Button", icon);
        System.out.println("button.isDefaultButton() = " + button.isDefaultButton());
```

prints

```
button.isDefaultButton() = false
```

**Comment by vlsi** [comment]
Ok, I identified the place where the button is upgraded to a default one.

It checks `Button.defaultButtonFollowsFocus`, and assumes `true` by default, so it upgrades the button to default on focus.

<img width="1552" alt="setdefault" src="https://user-images.githubusercontent.com/213894/74654909-689ba400-519c-11ea-954a-e5d4c3f7e52d.png">

**Comment by weisJ** [comment]
Could you try to set ````UIManager.put("defaultButtonFollowFocus", false)````?

**Comment by vlsi** [comment]
> UIManager.put("defaultButtonFollowFocus", false)

Well, it stops setting the button as default.

It looks like the default value for the property is wrong :-/

Frankly speaking, I'm inclined to always add `UIManager.put("defaultButtonFollowFocus", false)`
For instance, that keeps `yes` a default button no matter if one changes focus or not. That is "enter" defaults to "yes, save" action rather than the buton under focus.

**Comment by vlsi** [comment]
Note more thing: it looks like `pressed` state is not really reflected for regular and default buttons.

In other words, for `rollover` buttons I can distinguish between "mouse pressed" and "mouse released", however, regular (and default ones) do not provide feedback if they were pressed at all or not.

**Comment by weisJ** [comment]
>Frankly speaking, I'm inclined to always add UIManager.put("defaultButtonFollowFocus", false)

That is what I wanted to do. Just needed confirmation that it works.

> One more thing: it looks like pressed state is not really reflected for regular and default buttons.

So you suggest that the pressed state should be applied regardless of ````isRolloverEnabled()````?

**Comment by vlsi** [comment]
>So you suggest that the pressed state should be applied regardless of isRolloverEnabled()?

That is true. I find it better with the following patch to `getBackgroundColor`:

```
-        boolean clicked = rollOver && ((JButton) c).getModel().isArmed();
+        boolean clicked = c instanceof JButton && ((JButton) c).getModel().isArmed();
```

**Comment by weisJ** [comment]
I have added ````defaultButtonFollowFocus = true```` in ````button.properties````.

**Comment by weisJ** [comment]
Btw. is the text still truncated?

**Comment by vlsi** [comment]
No, the truncation is fixed (with both defaultButtonFollowFocus=true/false), thanks. It looks like size estimations with bold font helped.
