### ISSUE TITLE
Darklaf doesn't get published

### ISSUE THREAD

**Issue by weisJ** [weisJ/darklaf#43]
Now that core is in it's own module no darklaf jar gets published anymore. I renamed the artefact reference in the readme to darklaf-core.  Preferably there should probably be a darklaf artefact available to avoid confusion. Any opinions?

**Comment by Gama11** [comment]
I'm assuming these changes are the reason why this link from the readme is broken? https://github.com/weisJ/darklaf/tree/master/bin

**Comment by weisJ** [comment]
The binaries are no longer included in the repository. I have removed the broken link from the readme. Thank you for pointing it out :)

**Comment by Gama11** [comment]
I'm still a bit confused about this sentence:

>You can get the current build from [releases](https://github.com/weisJ/darklaf/releases).

That just seems to have the sources, not really a "build"? (build implies .jar file to me)

**Comment by weisJ** [comment]
Yes indeed. I have removed the sentence altogether. The intended way is to use maven.

**Comment by vlsi** [comment]
>Preferably there should probably be a darklaf artefact available to avoid confusion. Any opinions?

I don't know.
As for me, it probably makes sense to add a small note on the artifacts to clarify which one serves which purpose, so people can select which of them they need.

If both `darklaf` and `darklaf-core` are published, then it might cause similar confusion like `which one is better?`

**Comment by weisJ** [comment]
So change the description of each artefact?

**Comment by vlsi** [comment]
Well. Description indeed can be updated (e.g. as `description=...` to `gradle.properties` for each project).

However, I guess it is more important to put the description to the readme.
For instance: https://junit.org/junit5/docs/current/user-guide/#dependency-metadata-junit-platform

On top of that, Gradle enables to declare `features`: https://blog.gradle.org/optional-dependencies
I have not explored that yet, however, it looks
