### ISSUE TITLE
DLL size: 500KiB?

### ISSUE THREAD

**Issue by vlsi** [weisJ/darklaf#45]
I just noticed darklaf-windows from a RC-2 is 350KiB, and each DLL takes 500KiB.
It does not hurt much, however, it is a bit strange considering that `JNIDecorations.cpp` is just 8KiB.

Does that mean debugging information costs that much?
Would the binary be smaller if `optimized` one is shipped instead?

```
        0  02-01-1980 00:00   com/github/weisj/darklaf/platform/darklaf-windows/
        0  02-01-1980 00:00   com/github/weisj/darklaf/platform/darklaf-windows/windows-x86/
   456704  02-01-1980 00:00   com/github/weisj/darklaf/platform/darklaf-windows/windows-x86/darklaf-windows.dll
        0  02-01-1980 00:00   com/github/weisj/darklaf/platform/darklaf-windows/windows-x86-64/
   571392  02-01-1980 00:00   com/github/weisj/darklaf/platform/darklaf-windows/windows-x86-64/darklaf-windows.dll
```

**Comment by weisJ** [comment]
Well the release and debug versions actually have the same size. But both contain debug information nonetheless. The compiler uses the following arguments:
````/TP /nologo /c /Zi /O2````. Note that ````/Zi```` is included which produces the debug information. Is there a way to remove it?

**Comment by vlsi** [comment]
Just wondering: do you have a stipped version of the library co-located somewhere?

I just tried replacing all the cpp functions with empty ones, and it builds the following for me:

```
$ du -k -a .
8	./release/macos/x86-64/libdarklaf-windows.dylib
8	./release/macos/x86-64/stripped/libdarklaf-windows.dylib
8	./release/macos/x86-64/stripped
16	./release/macos/x86-64
16	./release/macos
16	./release
8	./debug/macos/x86-64/libdarklaf-windows.dylib
8	./debug/macos/x86-64
8	./debug/macos
8	./debug
24	.
```

So I have `stripped` folder. Do you have one?

**Comment by weisJ** [comment]
I don't get a stripped folder.

**Comment by weisJ** [comment]
Using [upx](https://github.com/upx/upx/tree/v3.96) (and the --brute option) I got the dll down to 119kb. Is it possible to execute it after the dll has been build?

**Comment by vlsi** [comment]
Well. Jar is already an archive, so upx is not that required here.

@lacasseio says "building debuggable" binaries is the current  Gradle implementation that might improve in future.

I guess we can strip debugging information if we add

```kotlin
        if (this is CppSharedLibrary) {
            linkTask.get().debuggable.set(false)
        }
```

into `binaries.configureEach` or into `afterEvaluate { ... forEach { binary ->`

Can you please try that?

**Comment by weisJ** [comment]
This works! Resulting dll is now 108kb.
