### ISSUE TITLE
ProgressBar strings hardly readable in Darcula theme

### ISSUE THREAD

**Issue by AlexFalappa** [weisJ/darklaf#47]
Progress bars with a painted string (`setStringPainted(true)`) are not so readable when not on the value part as their foreground color is a dark blue:
![image](https://user-images.githubusercontent.com/1875690/74746708-20e14f00-5266-11ea-95f0-084d158d0788.png)

**Comment by AlexFalappa** [comment]
Actually the string are even worse when on the value part:
![image](https://user-images.githubusercontent.com/1875690/74746992-89303080-5266-11ea-913a-2ae0387d3ca2.png)

**Comment by weisJ** [comment]
Thank you for the feedback. I have adjusted the colours. Available with the next release.
![ProgressBar](https://user-images.githubusercontent.com/31143295/74755520-9a336e80-5273-11ea-8fff-99b25ff92e67.png)
