### ISSUE TITLE
Lack of Java 8 support

### ISSUE THREAD

**Issue by Bios-Marcel** [weisJ/darklaf#5]
The pre-built (maven) binaries seem to be built with a newer version of Java. Therefore this L&F can't be used in applications that are still running Java 8. I've seen that you've set `sourceCompatibility` to `11`, but is this actually necessary? If not, i think it'd be cool to allow usage of older Java versions as well.

**Comment by weisJ** [comment]
I‘m currently reworking the codebase to be able to be compiled with Java 8. If I’m done with this I’ll upload a version that’s compatible with java 8.

**Comment by Bios-Marcel** [comment]
Cool, that's nice to hear. I am looking forward to it. If there's anything I can help you with, hmu.

**Comment by weisJ** [comment]
With the newest version Java8 should be compatible.

**Comment by Bios-Marcel** [comment]
That's great. Thanks :D I'll test it the next days
