### ISSUE TITLE
Button.defaultButtonFollowFocus -> defaultButtonFollowsFocus

### ISSUE THREAD

**Issue by vlsi** [weisJ/darklaf#50]
```
Button.defaultButtonFollowFocus = false
```

should be replaced with

```
Button.defaultButtonFollowsFocus = false
```

**Comment by weisJ** [comment]
The properties are processed before they are loaded sucht that ````false```` and ````true```` are parsed to the corresponding boolean value. See [````PropertyLoader````](https://github.com/weisJ/darklaf/blob/master/property-loader/src/main/java/com/github/weisj/darklaf/PropertyLoader.java). Is this still causing an issue i.e. do you observe ````DefaultLookup.getBoolean(... defaultButtonFollowFocus...)```` returning a string?

**Comment by vlsi** [comment]
Ok. I see. That is a typo.

```
Button.defaultButtonFollowsFocus <-- checked by Swing
Button.defaultButtonFollowFocus <-- configured in Darklaf
```

**Comment by weisJ** [comment]
Done 1c675764494b936514d0b170bed3987a109da583
