### ISSUE TITLE
Combobox: improper height estimation when item is empty

### ISSUE THREAD

**Issue by vlsi** [weisJ/darklaf#55]
Here's I add an extra empty item. It can be selected, however, its height is very small.

<img width="548" alt="empty_item" src="https://user-images.githubusercontent.com/213894/75022890-eff05c80-54a7-11ea-9d53-b15c11792ed8.png">

Using a space like `comboBox.addItem(" ");` solves the isuse:
<img width="189" alt="single_space" src="https://user-images.githubusercontent.com/213894/75023129-583f3e00-54a8-11ea-8158-e9da1534b93f.png">

**Comment by weisJ** [comment]
Fixed.
