### ISSUE TITLE
OSX incorrect dialog windows size with decoration enabled

### ISSUE THREAD

**Issue by FoxyBOA** [weisJ/darklaf#64]
The following code leads to incorrect Jdialog initial size (and position). Actually it's on decoration under OSX and shows JDialog.
```
import java.awt.FlowLayout;

import javax.swing.JButton;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;

import com.github.weisj.darklaf.LafManager;

public class Foo2 {

    private void initGUI() {
        JFrame frame = new JFrame("XXX");

        JButton button = new JButton("XXX");
        button.addActionListener(x -> {
            // create a dialog Box 
            JDialog d = new JDialog(frame); 

            // create a label 
            JLabel l = new JLabel("this is a dialog box"); 

            d.add(l); 

            // setsize of dialog 
            d.setSize(300, 300); 

            d.setLocationRelativeTo(null);

            // set visibility of dialog 
            d.setVisible(true); 
        });

        JPanel content = new JPanel(new FlowLayout());
        content.add(button);

        frame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        frame.setContentPane(content);
        frame.pack();
        frame.setLocationRelativeTo(null);
        frame.setVisible(true);
    }
    public static void main(String[] args) {
//        LafManager.setDecorationsEnabled(false);
        LafManager.install();
        SwingUtilities.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Foo2().initGUI();
            }
        });
    }
}
```

**Comment by weisJ** [comment]
Could you please provide a screenshot?

**Comment by FoxyBOA** [comment]
<img width="217" alt="Screen Shot 2020-03-06 at 10 00 03" src="https://user-images.githubusercontent.com/3250787/76064012-8127fe80-5f91-11ea-9ae2-5937dd0fb54c.png">

Expected behavior
<img width="302" alt="Screen Shot 2020-03-06 at 10 00 56" src="https://user-images.githubusercontent.com/3250787/76064047-9309a180-5f91-11ea-9227-1579f1401ae9.png">

**Comment by weisJ** [comment]
Does this happen reliably every time the dialog is openend?

**Comment by FoxyBOA** [comment]
Yes. 100%

macOS Mojave 10.14.6 if it's matter

**Comment by weisJ** [comment]
Could you provide pictures for the same case just with the dark theme?

**Comment by FoxyBOA** [comment]
Sure
<img width="197" alt="Screen Shot 2020-03-06 at 10 12 20" src="https://user-images.githubusercontent.com/3250787/76064847-255e7500-5f93-11ea-9830-a15edf88fe2d.png">
<img width="298" alt="Screen Shot 2020-03-06 at 10 12 46" src="https://user-images.githubusercontent.com/3250787/76064896-360eeb00-5f93-11ea-8092-29ea12c007a4.png">

**Comment by weisJ** [comment]
Thank you! Looks like the decorations are applied even if though the should not be. What version of Java are you using?

**Comment by FoxyBOA** [comment]
> java -version
```
java version "1.8.0_231"
Java(TM) SE Runtime Environment (build 1.8.0_231-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.231-b11, mixed mode)
```

>Edit: Does the same issue persist when setting System.setProperty(“darklaf.decorations“, “false“)?

Yes

**Comment by weisJ** [comment]
If you disable the decorations through `LafManager` are the decorations still applied. Do you have a Java 9 install or newer installed, to check if it still happens there?

**Comment by FoxyBOA** [comment]
Tested under 
> java -version
```
openjdk version "11.0.6" 2020-01-14
OpenJDK Runtime Environment (build 11.0.6+10)
OpenJDK 64-Bit Server VM (build 11.0.6+10, mixed mode)
```

The issue presents (for both light and dark themes).

And I was wrong. The code
`System.setProperty("darklaf.decorations", "false");`

fix the issue (works in the same way as` LafManager.setDecorationsEnabled(false);`) for Java8 and Java11

**Comment by FoxyBOA** [comment]
P.S. I noticed that initially, the dialog window has a size (possibly correct one, not sure), but after that, it changes it height to zero(?)

**Comment by weisJ** [comment]
Could you try to instead of setting the size of the dialog set its preferred size (if this doesn’t work try overwriting the preferredSize method).

**Comment by FoxyBOA** [comment]
If I change the code to `setPreferredSize()` than the situation is changing to reverse

1. `setPreferredSize()` && `setDecorationsEnabled(true)` -> correct windows size
2. `setPreferredSize()` && `setDecorationsEnabled(false)` -> zero height

For both Java 8 && 11.

1.
<img width="337" alt="Screen Shot 2020-03-06 at 11 59 23" src="https://user-images.githubusercontent.com/3250787/76073283-0adfc800-5fa2-11ea-834b-0d57a86497da.png">

2. 
<img width="123" alt="Screen Shot 2020-03-06 at 11 59 48" src="https://user-images.githubusercontent.com/3250787/76073362-2a76f080-5fa2-11ea-92ec-297665565c0f.png">

**Comment by weisJ** [comment]
Could you try and build the latest repository version and check if it behaves correctly now?

**Comment by FoxyBOA** [comment]
Tested. Works like a charm 😄
