### ISSUE TITLE
Is it possible to change globally default value (e.g. %borderThickness) for all themes?

### ISSUE THREAD

**Issue by FoxyBOA** [weisJ/darklaf#65]
You have a few themes (dark, light etc.) They are almost OK for me, except for one tiny thing - default border thickness. I would like to change it globally (for all controls and for all themes) from 3 to 1.

Is it possible without creating own themes etc.?

My workaround is to redefine it for each control before calling LafManager. But I've to determine and list all controls here. Possible you already have a solution for my and similar cases?
```
UIManager.put("TextField.borderThickness", 1);
...
LafManager.install();
```

**Comment by weisJ** [comment]
At the moment the easiest option is to overwrite the value in `Theme#loadGlobals`. I‘ll think about how to go about setting the values without a custom theme.

**Comment by FoxyBOA** [comment]
> At the moment the easiest option is to overwrite the value in Theme#loadDefaults

Not sure that I've got your idea. You propose to subclass a theme, but that code doesn't call `Theme#loadDefaults`. What I'm missing?

```
        LafManager.install();
        LafManager.setTheme(new MyTheme());
...
public class MyTheme extends IntelliJTheme{

    @Override
    public void loadDefaults(Properties pProperties, UIDefaults pCurrentDefaults) {
        super.loadDefaults(pProperties, pCurrentDefaults);
        
        System.out.println("%borderThickness="+pProperties.get("%borderThickness"));
    }

}

```

> The name %borderThickness may also be a bit misleading as borders in fact are always painted with a line width of 1 and this value actually controls the thickness of the focus border.

I would like to adjust insets around controls (e.g. I've +2px from each size around JTextField and that leads to additional scrolls etc.).

**Comment by weisJ** [comment]
Setting the theme just changes it for all subsequent installs. You need to pass the theme directly to `LafManager#install` or set it before.

The `%` is only present in the `.properties` files to indicate that this value can be referenced in other files. The actual key is just named `borderThickness`

**Comment by FoxyBOA** [comment]
The code
```
 LafManager.install(new MyTheme());
...
public class GBTheme extends IntelliJTheme{}
```

Leads to the following exception


```
[34m[2020-03-06 10:33:18][33m [SEVERE][31m Could not load intellij/intellij_defaults.properties.properties. null[37m[01m [at com.github.weisj.darklaf.theme.Theme][2m
                     [33m[Details] [31mjava.util.Properties$LineReader.readLine(Properties.java:434),
                               java.util.Properties.load0(Properties.java:353),
                               java.util.Properties.load(Properties.java:341),
                               com.github.weisj.darklaf.theme.Theme.load(Theme.java:189),
                               com.github.weisj.darklaf.theme.Theme.loadDefaults(Theme.java:80),
                               com.package.MyTheme.loadDefaults(MyTheme.java:13),
                               com.github.weisj.darklaf.DarkLaf.loadThemeDefaults(DarkLaf.java:208),
                               com.github.weisj.darklaf.DarkLaf.getDefaults(DarkLaf.java:112),
                               javax.swing.UIManager.setLookAndFeel(UIManager.java:539),
                               javax.swing.UIManager.setLookAndFeel(UIManager.java:583),
                               com.github.weisj.darklaf.LafManager.install(LafManager.java:169),
                               com.github.weisj.darklaf.LafManager.installTheme(LafManager.java:138),
                               com.github.weisj.darklaf.LafManager.install(LafManager.java:159),
                               com.package.Foo.main(Foo.java:268)[0m


```

**Comment by weisJ** [comment]
please overwrite `Theme#getLoaderClass` to return `IntelliJTheme.class`, this should fix it for now.

**Comment by FoxyBOA** [comment]
Works. Thank you

**Comment by weisJ** [comment]
With the next version you'll be able so set the properties through `LafManager.setProperty("borderThickness", "1")` and it will be applied to all themes (you have to set it before `LafManager.install()`). Properties can be also be cleared and removed.
