### ISSUE TITLE
Change default split pane divider style to `line`

### ISSUE THREAD

**Issue by weisJ** [weisJ/darklaf#70]
Currently the default style for the split pane divider is `grip` (through the `SplitPane.defaultDividerStyle` property). Personally I would almost always prefer the look of the `Line` style.
I'd like to change the default value of `SplitPane.defaultDividerStyle` to be `line`.
This comes with a few drawbacks though as this style by design doesn't honour `JSplitPane#isOneTouchExpandable`.

I'd like to get feedback on whether the change should happen.

`grip`
![grip](https://user-images.githubusercontent.com/31143295/76170876-75e9f400-6186-11ea-8b91-37c621597248.png)

`line`
![line](https://user-images.githubusercontent.com/31143295/76170881-839f7980-6186-11ea-929c-8a94903715c9.png)

**Comment by vlsi** [comment]
pictures, pictures

**Comment by weisJ** [comment]
Added pictures.

**Comment by weisJ** [comment]
It may be noted that for the `line` Style the area one is able to drag is actually larger than just the one pixel line.

**Comment by vlsi** [comment]
I wonder if there's a way to flip the styles of all dividers between `line` and `grip`.
E.g. to launch JMeter with both settings.

PS. The lack of lines for dividers was among the feedback on darklaf from JMeter team.

**Comment by weisJ** [comment]
I could add some overwrites using system properties (there are a few more that would benefit from this)

**Comment by weisJ** [comment]
The divider style can now be changed using `-DspdividerStyle=grip` or `-DspdividerStyle=line`.

**Comment by vlsi** [comment]
Does it make sense to group darklaf-related properties under `darklaf.*`namespace?

**Comment by vlsi** [comment]
I've tried JMeter with both styles and the output is mixed.

It looks like `line` is better provided the design was planned for `line` dividers.
In practice, we have ad-hoc divider usage, so if we flip everything to `line` it might be confusing (certain dividers would be hard to spot, and sometimes it would be hard to tell if the line is a divider or if it is a border).

However, IDEA never uses `grip` style, and it would be extremely surprising if they used `grip` :)

So using `line` by default would probably make sense.

**Comment by weisJ** [comment]
> Does it make sense to group darklaf-related properties under `darklaf.*`namespace?

Yes. Good idea!
