### ISSUE TITLE
Revert + release request

### ISSUE THREAD

**Issue by vlsi** [weisJ/darklaf#71]
https://github.com/weisJ/darklaf/commit/e5e7c02d2d9d7ea4f0a854d37995473c7b3af6cc causes "too wide" buttons (especially in the toolbar).

Before:
<img width="1264" alt="Снимок экрана 2020-03-10 в 1 03 20" src="https://user-images.githubusercontent.com/213894/76261494-334e1780-626b-11ea-829c-9edb64692bd1.png">

After:
<img width="1264" alt="Снимок экрана 2020-03-10 в 1 03 52" src="https://user-images.githubusercontent.com/213894/76261503-38ab6200-626b-11ea-8885-e0ae459e9a14.png">

Can you please revert the change and/or make it configurable?

It would be nice if you could release a version then (== with NPEs fixed), so we can actually start using it in Apache JMeter.

I guess we would start with `-Ddarklaf.decorations=false` due to outstanding native issues, however, moving to darklaf would improve the UX even with decorations disabled.

**Comment by weisJ** [comment]
I initlially made the fix due to the `no` button in the Laf restart message in JMeter was displayed as `...`. I have reverted it and appareantly it isn't an issue anymore so it should be good.

**Comment by vlsi** [comment]
> I have reverted it and appareantly it isn't an issue anymore so it should be good.

Yeah, thanks. Now it looks good modulo JMeter issues.

So it would be great if you could cut darklaf version so we can proceed with its integration in JMeter.

**Comment by weisJ** [comment]
> So it would be great if you could cut darklaf version so we can proceed with its integration in JMeter.

Do you mean release? Otherwise please clarify :).

**Comment by vlsi** [comment]
> Do you mean release?

I mean release.
The current version in Central (1.4.0.3) suffers from NPEs when LaF is updated.
