### ISSUE TITLE
Use of sun.* api

### ISSUE THREAD

**Issue by pmouawad** [weisJ/darklaf#76]
Hello,
First thanks for your work on this library which is really nice.

My question is maybe stupid, but do you plan to remove dependencies on Java internal API like:

- sun.awt.shell.ShellFolder
- sun.swing.SwingUtilities2

Thanks

**Comment by weisJ** [comment]
The possibility of this is explored in #62. Sadly some parts of swing aren't very accessible to custom look and feel implementations. `sun.swing.SwingUtilities2` isn't present anymore in that branch, but `sun.awt.shell.ShellFolder` is a bit more tricky (i.e at this point I don't even know if it is even possible without rewriting the whole file chooser).

**Comment by weisJ** [comment]
Closing in favor of #171.
