### ISSUE TITLE
Use heavyweight popups by default?

### ISSUE THREAD

**Issue by vlsi** [weisJ/darklaf#78]
Light:
<img width="641" alt="Снимок экрана 2020-03-15 в 20 24 47" src="https://user-images.githubusercontent.com/213894/76706760-172ef800-66fb-11ea-8537-dad4dd47b40e.png">

Heavy:
<img width="689" alt="Снимок экрана 2020-03-15 в 20 23 43" src="https://user-images.githubusercontent.com/213894/76706766-21e98d00-66fb-11ea-9a62-f3281384dbb4.png">

**Comment by weisJ** [comment]
On macOS this is indeed viable (looks a lot better). On windows this currently does nothing, but I have used the current JNI code to add the same shadows as on macos to the popup. Of course this only works if decorations are enabled.

**Comment by vlsi** [comment]
As a workaround, I add `popup.setLightWeightPopupEnabled(false);` in JMeter code just before the popup is shown.

However, https://github.com/weisJ/darklaf/pull/79 is still needed otherwise popup background flickers which is especially visible in dark themes.

**Comment by weisJ** [comment]
This property can now be changed using `PopupMenu.defaultLightWeightPopups`. On macOS it will default to `false`. Same on windows if decorations are enabled. Otherwise it will be disabled.
