### ISSUE TITLE
Menu item has inconsistent active background color

### ISSUE THREAD

**Issue by vlsi** [weisJ/darklaf#80]
I think the items should use the same color.
Currently, the color is different for the items that have submenus.

<img width="283" alt="with submenu" src="https://user-images.githubusercontent.com/213894/76708999-54e84c80-670c-11ea-9bf3-d32dc8c7052c.png">

<img width="283" alt="leaf item" src="https://user-images.githubusercontent.com/213894/76709000-59ad0080-670c-11ea-9351-6ed2e25bd754.png">

**Comment by weisJ** [comment]
This ought to be the case. Can you give me an example to reproduce? This doesn't seem to happen for me.

**Comment by vlsi** [comment]
It is connected with `-Dapple.laf.useScreenMenuBar=true`

The solution is to remove this line: https://github.com/weisJ/darklaf/blob/b54db617f810b09fe28783ce24d82609fdc79325/core/src/main/java/com/github/weisj/darklaf/DarkLaf.java#L159

Otherwise `MenuUI` resolves to `com.apple.laf.AquaMenuUI` and it uses its own colors for drawing selected state.

**Comment by vlsi** [comment]
<img width="303" alt="fixed MenuUI" src="https://user-images.githubusercontent.com/213894/76710054-291d9480-6715-11ea-8196-767c04ac9aaa.png">

**Comment by weisJ** [comment]
Fixed. Thank you 😄

**Comment by weisJ** [comment]
Btw. this should also fix the colour of the menu arrow on light themes (e.g. IntelliJ). When hovering it should have been white instead of grey. Based on your other screenshots this wasn't the case.

**Comment by vlsi** [comment]
Yes, both themes look ok:

<img width="303" alt="intellij theme" src="https://user-images.githubusercontent.com/213894/76710366-0771dc80-6718-11ea-951d-13323d0b6e37.png">
