### ISSUE TITLE
Option to automatically change style of icon-only buttons

### ISSUE THREAD

**Issue by weisJ** [weisJ/darklaf#81]
Currently buttons that only consist of an icon, would benefit from a combination of styles that can be set through client properties.

With the property `darklaf.shadowIconButtons=true` (dafault is `false`) these styles are automatically applied with the following result: 

#### Before
![button_standard](https://user-images.githubusercontent.com/31143295/76711349-96c6c200-670f-11ea-9f68-a218790d7b28.png)

#### After
![button_hover](https://user-images.githubusercontent.com/31143295/76711354-9cbca300-670f-11ea-9efe-4754e1f79b9d.gif)

**Comment by vlsi** [comment]
This indeed looks better

The default icon-only buttons are too wide:
<img width="1130" alt="shadowIconButtons=false" src="https://user-images.githubusercontent.com/213894/76745194-81d94580-6786-11ea-9b1a-8afbe1a2fef5.png">

With `shadowIconButtons=true` it becomes too narrow

<img width="716" alt="shadowIconButtons=true" src="https://user-images.githubusercontent.com/213894/76745203-869df980-6786-11ea-95b4-b3ec39a6f828.png">

It might be a bug in ToolBarUI though.

**Comment by weisJ** [comment]
I'll see if I can adjust the spacing for the buttons s.t. they include some margins ond the left/right side.

**Comment by vlsi** [comment]
I tried the following configuration for toolbar buttons, and it produces nice results:

```java
        button.setFocusable(false);
        button.setRolloverEnabled(true);
        button.putClientProperty(DarkButtonUI.KEY_VARIANT, DarkButtonUI.VARIANT_SHADOW);
        button.putClientProperty(DarkButtonUI.KEY_THIN, Boolean.TRUE);
```

<img width="799" alt="light" src="https://user-images.githubusercontent.com/213894/76807125-6147d480-67f4-11ea-9b74-41fc835535f5.png">

<img width="796" alt="dark" src="https://user-images.githubusercontent.com/213894/76807119-5db44d80-67f4-11ea-87ee-dce9713dd45d.png">

**Comment by weisJ** [comment]
I have adapted these changes with the addition of ensuring that shadows are actually square and centered.

**Comment by vlsi** [comment]
Just wondering: is `icon-only` condition needed?

What if every `non-focuseable button with icon` was converted to a `flat` style?
