### ISSUE TITLE
shadow button variant is not accessible

### ISSUE THREAD

**Issue by vlsi** [weisJ/darklaf#83]
Buttons like in https://github.com/weisJ/darklaf/issues/81 can be focused, and they can be triggered via keyboard, however, focus in not visible, and triggering does not produce visual feedback.

Does that mean the `shadow` button should automatically become `non-focuseable`?

Is it possible?

**Comment by weisJ** [comment]
Depending on the desired effect there two possibilities:
1. Set the button to not be focusable if it displays with a shadow. This would eventually cause issues if this property is changed outside of the laf as there is no way to detect it (property change events are only fired if the value actually changed).
2. If the button displays a shadow ignore the keyboard input. The button would still be focusable.

**Comment by vlsi** [comment]
> Set the button to not be focusable if it displays with a shadow

Does that include "autoconverted" buttons?
I don't think it is safe to make non-focuseable all icon-only buttons.

What if `non-focuseable` was an extra condition for rendering icon-only button as "shadow"?

**Comment by vlsi** [comment]
In other way: darklaf should try its best to render a user-provided button.
If the user asks for `focuseable` button, then the rendering must support it.

The current implementation of `shadow` (why is it called like that?) does not support focus rendering, so darklaf should not try automatically convert the button to a `shadow` variant.

---

In JMeter, I guess the buttons on the toolbar must be created as non-focuseable, as their focus makes little sense (i'm inlined to commit `setFocuseable(false)` shortly). The very same actions are available via menu with better accessibility.

**Comment by weisJ** [comment]
>What if `non-focuseable` was an extra condition for rendering icon-only button as "shadow"?

> In other way: darklaf should try its best to render a user-provided button.
> If the user asks for `focuseable` button, then the rendering must support it.
>...
>does not support focus rendering, so darklaf should not try automatically convert the button to a `shadow` variant.

This looks like a good solution to me.

> The current implementation of `shadow` (why is it called like that?) 

I simply had no better name for it. If you suggest a new one this can be changed :D.

**Comment by vlsi** [comment]
>I simply had no better name for it. If you suggest a new one this can be changed :D.

Oh. naming is hard. Does `shadow` differ from `fullShadow`?

Could it be like `flat`?

**Comment by weisJ** [comment]
Well `fullShadow` fills the entire background of the button. I'm not sure `flat` captures it much better. Essentially it should convey that the button will primarily rely on rollover effects when applied.
