### ISSUE TITLE
thin, rollover, square, altArc button configuration is lost after LaF change

### ISSUE THREAD

**Issue by vlsi** [weisJ/darklaf#84]
I guess https://github.com/weisJ/darklaf/blob/e117205b5b7bf22ef4811a54aa9213dcb8db2341/core/src/main/java/com/github/weisj/darklaf/ui/button/DarkButtonUI.java#L86-L89 do not work as designed

Testcase:
1) ButtonDemo
2) rollover + thin + shadow

    <img width="558" alt="state1" src="https://user-images.githubusercontent.com/213894/76807395-4c1f7580-67f5-11ea-8c2e-a8797a9347fd.png">

    So far so good

3) Change theme (e.g. to SolarizedDark)

    Actual result: button is no longer `rollover`

4) Click `rollover` twice

    Actual result (the button is much bigger that it was before):
    <img width="558" alt="state4" src="https://user-images.githubusercontent.com/213894/76807465-812bc800-67f5-11ea-98f1-377d3964f5ff.png">

**Comment by vlsi** [comment]
It looks like there's no way to tell if LaF modifies the component in `javax.swing.plaf.ComponentUI#installUI`.

That means the only reliable way to switch LaF is to re-create components completely.

Nevertheless, I see no reason for `DarkButtonUI` to call `putClientProperty` and/or `setRolloverEnabled`.

**Comment by weisJ** [comment]
This should be fixed now.
