### ISSUE TITLE
Text font size switches when editing a cell in table

### ISSUE THREAD

**Issue by vlsi** [weisJ/darklaf#86]
regular:
<img width="267" alt="Снимок экрана 2020-03-17 в 13 04 57" src="https://user-images.githubusercontent.com/213894/76845461-fa580900-684f-11ea-8d80-c59d0ccfff0c.png">

edit mode:
<img width="259" alt="Снимок экрана 2020-03-17 в 13 05 07" src="https://user-images.githubusercontent.com/213894/76845469-fb893600-684f-11ea-9969-57b53918275d.png">

Note how `John` becomes slightly bigger when switching to edit mode.

**Comment by weisJ** [comment]
This does not happen on windows. Could you show be what `UIManagerDefaults` shows when selection `by values` and then `font`?

**Comment by weisJ** [comment]
`AquaLookAndFeel` uses `viewFont` for `Table.font` and `controlFont` for `TextField.font` and `Label.font`. By default `DefaultTableCellEditor` uses `table.getFont()` for the font of the editor.
Indeed:
````
controlFont -> lucida 13pt
viewFOnt -> lucida 12pt
````
The same applies to editing a tree.

I think the best solution would be to explicitly specify the font size for each `*.font` property and apply it after the fonts have been initialized. This ensures fonts have consistent sizes across platforms.

**Comment by weisJ** [comment]
Fonts should be fixed now.

**Comment by vlsi** [comment]
Thanks. Fonts work in d4ea51f8ccdbde8e065996067099af43f0063f6e.
