### ISSUE TITLE
Selected cell border is hard to spot in every theme but darcula

### ISSUE THREAD

**Issue by vlsi** [weisJ/darklaf#87]
Here's the same state in different themes.

darcula:
<img width="272" alt="darcula" src="https://user-images.githubusercontent.com/213894/76845985-d6e18e00-6850-11ea-8473-998dd5ad5609.png">

intellij:
<img width="272" alt="intellij" src="https://user-images.githubusercontent.com/213894/76846010-e3fe7d00-6850-11ea-8111-349845464a3b.png">

solarized light:
<img width="272" alt="solarized light" src="https://user-images.githubusercontent.com/213894/76846021-e9f45e00-6850-11ea-8a03-7f4cfff9eff8.png">

solarized dark:
<img width="272" alt="solarized dark" src="https://user-images.githubusercontent.com/213894/76846030-ee207b80-6850-11ea-91cc-2d56caa57132.png">

**Comment by weisJ** [comment]
This indeed a problem. At the moment I don't know what colours to use. Best thing would be to reuse one of the already existing named property colours to avoid introducing a colour that is only used in one place. Alternatively if the current colour is changed it should look good in trees (i.e. the other place `%borderFocus` is used is the highlighted tree line).

**Comment by vlsi** [comment]
Could row selection be rendered differently?

For instance, what if `selected` background was not painted at all for the cell in case there are more than 2 columns in the row?

Here's Excel:
<img width="367" alt="Excel" src="https://user-images.githubusercontent.com/213894/76907312-f6130680-68b6-11ea-950c-da929791ea0c.png">

**Comment by vlsi** [comment]
E.g.

<img width="263" alt="Снимок экрана 2020-03-18 в 1 40 28" src="https://user-images.githubusercontent.com/213894/76908342-7e92a680-68b9-11ea-8e0a-ba0ad5a675e7.png">

<img width="339" alt="Снимок экрана 2020-03-18 в 1 40 07" src="https://user-images.githubusercontent.com/213894/76908347-818d9700-68b9-11ea-85d0-73b52a733cb3.png">

<img width="265" alt="Снимок экрана 2020-03-18 в 1 39 39" src="https://user-images.githubusercontent.com/213894/76908357-86524b00-68b9-11ea-9e7a-4ed58da7f969.png">

<img width="257" alt="Снимок экрана 2020-03-18 в 1 42 15" src="https://user-images.githubusercontent.com/213894/76908436-b7328000-68b9-11ea-9e67-1b9ce359b5f1.png">

**Comment by weisJ** [comment]
Not painting the selection background on the lead selection cell looks good. There is one minor issue (in that I don't know what would be beneficial here). At least in one location, the file chooser to be specific) The table treats the whole row as the lead selection cell. This may be confusing when selecting multiple files as the lead selection cell is always at the "edge" of the selection but not highlighted as being part of such.

For example
![FileChooser](https://user-images.githubusercontent.com/31143295/76913377-1b077980-68b7-11ea-960e-125024a370df.png)

Notice how both files are selected (they are both listed in the selected files box). The current behaviour however suggests that indeed only `tree.eps` is selected.

The same still applies for cell selection in standard tables but not as bad, as only a single cell is not painted with the selection background.

**Comment by vlsi** [comment]
> whole row as the lead selection cell.

No idea there. macOS does not make the currently selected row distinct in the file chooser.

* We can keep painting the background for the case of row selection
* We can paint the background, and make row selection blinking. It might be easier to spot than a static 1px rectangle.


PS. The toolbar-like buttons on the file chooser would probably be closer together (and they probably need to be smaller). The icons and text do not look centered on the buttons as well.

**Comment by weisJ** [comment]
I think I'll rather just paint the background in the case of row selection. Not a big fan of blinking ui elements that don't convey any important signal.
