### ISSUE TITLE
1.4.2.0: tooltip for disabled button is hard to read in dark themes

### ISSUE THREAD

**Issue by vlsi** [weisJ/darklaf#88]
Tooltip foreground seems to be always black, so it is hard to read in dark themes.

intellij:
<img width="166" alt="Снимок экрана 2020-03-17 в 13 29 01" src="https://user-images.githubusercontent.com/213894/76847915-df879380-6853-11ea-9137-b79bc73b707f.png">
solarized light:
<img width="151" alt="Снимок экрана 2020-03-17 в 13 29 08" src="https://user-images.githubusercontent.com/213894/76847919-e0b8c080-6853-11ea-9560-d7fb93a01b0c.png">
solarized dark:
<img width="127" alt="Снимок экрана 2020-03-17 в 13 28 54" src="https://user-images.githubusercontent.com/213894/76847921-e31b1a80-6853-11ea-9012-c4ff86ee2ec8.png">
darcula:
<img width="116" alt="darcula" src="https://user-images.githubusercontent.com/213894/76847927-e57d7480-6853-11ea-9d73-c91276271e3c.png">

Master branch produces the following tooltips:
<img width="138" alt="broken tooltip" src="https://user-images.githubusercontent.com/213894/76848052-152c7c80-6854-11ea-8424-c54ea498cb89.png">

**Comment by weisJ** [comment]
I could not reproduce the last picture. Though the foreground text should be good now.

**Comment by vlsi** [comment]
Thanks, it works with b881aeae97e6ab99117e08582700af6beb264611

**Comment by weisJ** [comment]
The sizing issue should also be gone now.

**Comment by vlsi** [comment]
Code:

```java
        JButton button = new JButton(new ImageIcon(imageURL)) {
            @Override
            public void updateUI() {
                super.updateUI();
                // Certain LaFs might alter button configuration, so we revert it to the way we want
                // For instance, https://github.com/weisJ/darklaf/issues/84
                setFocusable(false);
                setRolloverEnabled(true);
                putClientProperty(DarkTooltipUI.KEY_STYLE, DarkTooltipUI.VARIANT_BALLOON);
            }
        };
```

Tooltip:
<img width="149" alt="tooltip" src="https://user-images.githubusercontent.com/213894/76985708-afbeb580-6951-11ea-9d15-812c34a82ab9.png">

The sizing looks OK to me, however, it is not clear how to make it balloon-style.

**Comment by weisJ** [comment]
Well technically that is the balloon style with pointer location set to `CENTER`. Without any further information there is no way to know how to align the tooltip as it's location cannot be manipulated from within the ui.

The result achieved in `ToolTipDemo` makes use of `ToolTipContext` which does the majority of the positioning. See `ToolTipAwareButton.java` on how to use it.

**Comment by vlsi** [comment]
I just thought it would automatically position itself under the button rather than at the cursor position.

I've seen ToolTipAwareButton, however, it does not look like to refactor all the cases to TooltipAwareButton.
On the other hand, `setAlignment` and `setCenterAlignment` could probably be taken from `JComponent`'s properties.

As an alternative option, the `ToolTipContext` itself could be a client property of the component.

Then it won't be needed to create `ToolTipAwareLabel`, `TooltipAwareRadio` and so on.

**Comment by weisJ** [comment]
I originally wanted to do it that way but it is very difficult to change the tooltip location in hindsight because neither the tooltip nor its location are determined by the laf. Sadly `JComponent#getToolTipLocation` also gets called before `JComponent#createToolTip` so there is no good way to change the location. I'll look back into it to see whether I can make it such that the tooltip repositions itself after it has been made visible.

**Comment by weisJ** [comment]
If this works it would also be feasible again to automatically calculate the best fit for the anchor position based on the components location. i.e. the tooltip tries to stay inside the component and if it doesn't fit resorted to being free floating.

**Comment by vlsi** [comment]
Ok. It might make sense to move position/style to a separate issue.

Tooltips in 055955e359e4f255b2f53d7fdb98433899b6174c work like with other LaFs.

**Comment by weisJ** [comment]
With 494bd7dcdc2dd02f6ec274cf2f2625bcc2bb20ac the following code should produce a button with an anchored tooltip.

````java
JButton button = new JButton();
buton.putClientProperty(DarkToolTipUI.KEY_STYLE, ToolTipStyle.BALLOON); //Or DarkToolTipUI.VARIANT_BALLOON
````

**Comment by weisJ** [comment]
I think I'll add an option to change the default style for tooltips s.t. one doesn't need to set the client property on all components they use (which would still take precedence in this case).
