### ISSUE TITLE
Tooltip style should be inherited from a JComponent

### ISSUE THREAD

**Issue by vlsi** [weisJ/darklaf#89]
There should be a way to configure a preferred tooltip style by using `new JButton().putClientProperty(..., ...)`

PS. The code like https://github.com/weisJ/darklaf/blob/5317ae58b885cb35a64dd07b3e3174bc5e040c66/core/src/main/java/com/github/weisj/darklaf/ui/tooltip/DarkTooltipUI.java#L152-L153 should better be written as

```java
javax.swing.LookAndFeel.installProperty(toolTip, KEY_STYLE, ToolTipStyle.BALLOON);
```

**Comment by weisJ** [comment]
> There should be a way to configure a preferred tooltip style by using `new JButton().putClientProperty(..., ...)`

I see. 

> PS. The code like
> 
> https://github.com/weisJ/darklaf/blob/5317ae58b885cb35a64dd07b3e3174bc5e040c66/core/src/main/java/com/github/weisj/darklaf/ui/tooltip/DarkTooltipUI.java#L152-L153
> 
> should better be written as
> ```java
> javax.swing.LookAndFeel.installProperty(toolTip, KEY_STYLE, ToolTipStyle.BALLOON);
> ```

This code will throw an exception as the value of `KEY_STYLE` is not a known property to swing. In fact even most properties swing uses is unknown to it. There is no clever caching mechanism behind `LookAndFeel#installProperty`. It just checks for all values that it knows whether they have been set by the user, in which case the new value is ignored.

**Comment by weisJ** [comment]
If `KEY_STYLE` is set on the component the tooltip is for that value is now prioritized as the tooltip style.

**Comment by vlsi** [comment]
Oh, it is getting interesting:

<img width="152" alt="Снимок экрана 2020-03-19 в 15 53 53" src="https://user-images.githubusercontent.com/213894/77069644-e0f2c080-69f9-11ea-9726-dbddf0b81520.png">

"new" is the left-most button, and it looks like the tooltip is trying its best to be within the window:
<img width="116" alt="Снимок экрана 2020-03-19 в 15 53 57" src="https://user-images.githubusercontent.com/213894/77069648-e3551a80-69f9-11ea-9f84-91ce16ab1902.png">

One more sample
<img width="135" alt="Снимок экрана 2020-03-19 в 15 55 00" src="https://user-images.githubusercontent.com/213894/77069722-02ec4300-69fa-11ea-9b94-615e31f182e2.png">

**Comment by weisJ** [comment]
Do you consider this to be undesired behaviour? Because I specifically made it so that the tooltip tries to stay inside the window.
