### ISSUE TITLE
Table: consider something like JTable#surrendersFocusOnKeystroke

### ISSUE THREAD

**Issue by vlsi** [weisJ/darklaf#91]
By default, typing into `JTable` immediately starts editing, however, the editor does not gain focus.
That is the value is changing, yet the cursor is not visible.

It is a [well-known bug JDK-4274963](https://bugs.openjdk.java.net/browse/JDK-4274963) that is resolved as `won't fix`.

Note: a mere setting of `JTable.setSurrendersFocusOnKeystroke(true)` is not enough. The focus is there, however, it selects the full text, so the subsequent keystroke replaces the text.

I wonder if Darklaf can work around that, so typing into the table would make cursor visible, and double-click into the cell would start editing at the proper position.

Relevant OpenJDK code: https://github.com/openjdk/jdk/blob/efb25e51277ff2760bcd17718a059826bdda249f/src/java.desktop/share/classes/javax/swing/JTable.java#L5300

**Comment by vlsi** [comment]
So it might be either

```java
DarkTableUI {
    @Override
    public void installUI(final JComponent c) {
        super.installUI(c);
        if (c instanceof JTable) {
            ((JTable) c).setSurrendersFocusOnKeystroke(true);
        }
    }
```

or

```java
    public DarkTableCellEditor() {
        this(new JTextField() {
            @Override
            protected boolean processKeyBinding(KeyStroke ks, KeyEvent e, int condition, boolean pressed) {
                boolean hasBinding = super.processKeyBinding(ks, e, condition, pressed);
                // TODO: make this configurable via clientProperty
                if (!hasBinding && condition == JComponent.WHEN_FOCUSED && !isFocusOwner()) {
                    requestFocus();
                }
                return hasBinding;
            }
        });
    }
```

**Comment by weisJ** [comment]
I like the idea of the first solution more, as it respects all cell renderers no just those supplied by the Laf. Though there might be a point to make that editing though key typing only applies for textfields anyway.
In either scenario this could be controllable through a property by the user.

**Comment by vlsi** [comment]
Technically speaking, that property should probably be set at the application side (so it does not depend on a single LaF).
However, an application might have plugins, so it might be non-trivial to control all the JTables.

I tried `TableDemo`, and I see no difference for checkbox renderer.
So `installUI`-like approach might be the way to go even though it alters `setSurrendersFocusOnKeystroke`

**Comment by weisJ** [comment]
Then the first solution it is.
