### ISSUE TITLE
text: selection should not be reset on losing focus

### ISSUE THREAD

**Issue by vlsi** [weisJ/darklaf#92]
Current behavior makes it complicated to copy-paste values out of Darklaf-driven applications.

Test case

1. Select a word in a text field
2. Switch applications (e.g. alt+tab, alt+tab)
3. The selection is lost. So one can't really copy the selected value.

Expected result: selection should not be reset. E.g. try selecting a part of an address bar in the browser and check if it persists when applications are switched.

**Comment by weisJ** [comment]
Fixed. This was originally the case and changed by request in #57 and has now been changed such that the value of `JTextField.keepSelectionOnFocusLost` is `true` by default and needs to be manually set to `false` if selection shouldn't be kept.

**Comment by vlsi** [comment]
What do you think if the selection background was **not** rendered if the field is not focused?
In other words, the selection should be kept intact, yet it should be just hidden.

I guess that would make `keepSelectionOnFocusLost` irrelevant.

**Comment by weisJ** [comment]
I don't know if this is very intuitive. One might automatically start to make a new selection if the visuals don't show a selection (making the whole point of keeping the selection irrelevant). Maybe changing the selection colour to the one tables/trees use for selected cells that are not focused would work better. It signals that the selection is still there but doesn't give the impression the field is still focused.

**Comment by vlsi** [comment]
> I don't know if this is very intuitive

Try writing a comment on this PR, select a word, and try pressing `tab` vs `shift-tab`.
It behaves exactly as I suggest.

The same is for Nimbus LaF, Aqua LaF, Metal LaF.
The same happens in IDEA.

>It signals that the selection is still there but doesn't give the impression the field is still focused.

Suppose there's a window with 10 fields. Do you really want to keep and display 5 selections?
It would make really hard to understand what would get copied if copy-paste is used.

**Comment by weisJ** [comment]
I guess there are different approaches based on OS. On windows the result is exactly as in my version.

**Comment by vlsi** [comment]
>I guess there are different approaches based on OS

Really? Can you please show a video?

I got access to Windows 10, and it behaves like "select all on focus-in".

macOS, Chrome: <img src="http://g.recordit.co/IPTp6kPfiu.gif">

Windows 10: <img src="http://g.recordit.co/CM0m3QI3A4.gif">

I agree there might be a demand for "select all on focus", and it might be either platform-specific or configurable per field. For instance, address bar in the browser should probably always be "select all on focus in" since 99% of the cases are to either copy the full address or type a brand new one (e.g. paste, etc).

On the other hand, some of the fields do not require "select all" behavior.

**Comment by weisJ** [comment]
I see. I tried it by switching to intelliJ which apparently doesn't steal the focus. But with the file explorer it works. Is it sensible to implement this behaviour for every text component or only TextField(and subclasses)/TextArea ?
