### ISSUE TITLE
button: text gets truncated, the contents is not centered

### ISSUE THREAD

**Issue by vlsi** [weisJ/darklaf#93]
d4ea51f8ccdbde8e065996067099af43f0063f6e: <img width="509" alt="button truncation" src="https://user-images.githubusercontent.com/213894/76959598-ec2aeb00-692a-11ea-851e-38a3830fa64a.png">

1) `Add from Clipboard` is truncated
2) Text on buttons is not centered. It looks shifted to the right on all the buttons except `Add from Clipbo...`.

It would probably make sense to add rendering tests as this is not the first time the issue appears :-/

**Comment by weisJ** [comment]
Should be fixed now.

**Comment by weisJ** [comment]
If you have a proposition on how to perform such test I'll be open to add some. Or do you just want to have manual test for this?

**Comment by vlsi** [comment]
Well, manual is the last resort only.

What I mean is as follows:
1) `DarkButtonUI#paint` calls `layout` in order to layout the text and figure out truncated label. You can add a callback there that will signal if the text was truncated.
2) Then you can paint the button into a `BufferedImage`. Here you can check that the button does not get truncated.
3) Optionally you can save the screenshot and compare it (e.g. with some tolerance). An automatic tool might detect a case when the image differs too much, and GitHub does show image diff right in the diff view: https://github.com/apache/jmeter/pull/553/files?short_path=ef15524#diff-ef1552462ecbe39d5e62f1fd2190d890

4) There are [platform-specific tools](https://github.com/openjdk/jdk/commit/5705a551617d10e8c218b0f20f89ff073365c5e9) that might help as well. E.g. prepare a screen with all the features, and capture it via GitHub Actions.

**Comment by vlsi** [comment]
Works in 055955e359e4f255b2f53d7fdb98433899b6174c
