### ISSUE TITLE
filechooser: file format combobox is hard to read

### ISSUE THREAD

**Issue by vlsi** [weisJ/darklaf#94]
The very first option is hovered, and it is almost a white foreground and white background.

<img width="614" alt="Снимок экрана 2020-03-18 в 16 09 42" src="https://user-images.githubusercontent.com/213894/76964465-d837b700-6933-11ea-8ff6-f0ec6d1c8be4.png">

**Comment by weisJ** [comment]
Fixed.

**Comment by vlsi** [comment]
Metal:
<img width="507" alt="chooser" src="https://user-images.githubusercontent.com/213894/76982578-25745280-694d-11ea-879d-5f2283debfb9.png">

Darklaf:
<img width="498" alt="chooser" src="https://user-images.githubusercontent.com/213894/76982642-3b821300-694d-11ea-804b-7afc76e281c7.png">

Note: `detals`/`list` buttons act as radio buttons, so they must be co-located (there should be no gap between them)

**Comment by vlsi** [comment]
Just in case: the toolbar-like buttons feel as non-focuseable in Darklaf, however, they are focuseable in Metal.

Frankly speaking, I think the buttons should be focuseable for accessibility reasons.

**Comment by weisJ** [comment]
Buttons are now focusable again and the view buttons are closer together. The striped background should extend to the end of the view. For me the menu doesn't look that strange.

**Comment by vlsi** [comment]
> view buttons are closer together

I think they should be side by side up to the point the sibling corners are not round.
Otherwise, it is hard to guess the buttons are radio.

Sample:
<img width="331" alt="radio in toolbar" src="https://user-images.githubusercontent.com/213894/77002842-42208280-696d-11ea-8bca-ddbe5184805d.png">

**Comment by weisJ** [comment]
I see. I have to think about how to do this in a way that enables others to also use this.
