### ISSUE TITLE
Custom JSpinner editor support

### ISSUE THREAD

**Issue by MioBlanco** [weisJ/darklaf#99]
If you try to use your own editor in the JSpinner, it works unfortunately only very limited in combination with the look and feel. This is caused, because you cast the editor to a DefaultEditor in the class DarkSpinnerUI.class in the method createEditor().
````java  
editorComponent = ((JSpinner.DefaultEditor) editor).getTextField(); 
````
A better Solution would be something like this
````java  
if instanceof DefaultEditor {
	((Cast) editor).getTextField().addFocusListener...
} else {
	editor.addFocusListener
}
````

**Comment by weisJ** [comment]
Fixed in 8621d74238c30c3e878b63da65dcc4dd6396e41a
